### PR TITLE
config.tf: tco to 0.6.2.

### PR DESCRIPTION
**Pull request by diegs**
Includes fix for missing dex TPR.

### CODE REVIEW

**Comment by diegs** [comment]
Looks like one of the aws nodes never came up.

**Comment by diegs** [comment]
this one is timout out for ever. let's retry!

**Comment by diegs** [comment]
retest this please

**Comment by yifan-gu** [comment]
test upgrade from 1.7.9-tectonic.3 1.7.9-tectonic.3

**Comment by diegs** [comment]
@squat another LGTM please at your convenience

**Pull request merged**
