### PR TITLE
[Release PR] azure/vnet: NSG improvements

### PR DESCRIPTION
**Pull request by justaugustus**
* azure/nsg: Update NSG names

* azure/nsg: Tighten NSG rules

* azure/nsg: Uppercase NSG `protocol` field

When changes to NSG rules are made outside of the
installer, subsequent installer runs recognize the modified NSG
rules as different, due to the protocol not being uppercased

* azure/nsg: Tighten NodePort NSG rules & add UDP

* azure/nsg: Add NSG rule descriptions

* azure/nsg: Update NSG rule priorities

* azure/nsg: Remove `external_nsg_api_id`

API / Console communications happen within the master subnet,
so this is an unnecessary variable

* azure/nsg: Remove duplicate flannel rules

* azure/nsg: Move etcd rules to master subnet NSG

* azure/nsg: Remove `external_nsg_etcd_id`

etcd communication happen within the master subnet, so this is an
unnecessary variable

### CODE REVIEW

**Comment by alexsomesan** [comment]
ok to test

**Comment by justaugustus** [comment]
retest this please

**Comment by justaugustus** [comment]
@alexsomesan Can you chase down these test failures tomorrow?
Looks to be a result of things that were removed in this PR.

**Comment by alexsomesan** [comment]
I'm seeing the same failure in all the tests:
```

* resource 'azurerm_network_interface.etcd_nic' config: unknown variable referenced: 'external_nsg_etcd_id'. define it with 'variable' blocks
* resource 'azurerm_network_interface.etcd_nic' config: unknown resource 'azurerm_network_security_group.etcd' referenced in variable azurerm_network_security_group.etcd.*.id
```

**Pull request closed without merging**
