### PR TITLE
config.tf: update kvo to v1.7.5-kvo.10

### PR DESCRIPTION
**Pull request by diegs**
Also regenerate update payload.

### CODE REVIEW

**Comment by diegs** [comment]
test upgrade from 1.7.3-tectonic.3 1.7.3-tectonic.3

**Comment by yifan-gu** [comment]
test upgrade from 1.7.3-tectonic.3 1.7.3-tectonic.3

**Comment by sudhaponnaganti** [comment]
Why up-grade is being tested from same version ? - can it be done from 1.7.1?

**Comment by yifan-gu** [comment]
@sudhaponnaganti We can, let's upgrade from 173-3 first.

**Comment by sudhaponnaganti** [comment]
@yifan-gu - thank you

**Comment by diegs** [comment]
The upgrade test from 1.7.3-tectonic.3 passed.

**Comment by diegs** [comment]
test upgrade from 1.7.1-tectonic.2 1.7.1-tectonic.2

**Comment by yifan-gu** [comment]
Test ran for a while,  doesn't seem good.
I am inspecting.

**Comment by diegs** [comment]
It's a lot of upgrades...

**Comment by diegs** [comment]
`error updating to 1.7.5+tectonic.1: Failed update of component: daemonset/kube-system/pod-checkpointer due to: error creating patch: patch:`

:(

**Comment by diegs** [comment]
This error is due to skew between 1.7.3 clusters and <1.7.3 clusters.

Fix in the KVO: https://github.com/coreos-inc/kube-version-operator/pull/312

**Comment by diegs** [comment]
test upgrade from 1.7.1-tectonic.2 1.7.1-tectonic.2

**Comment by diegs** [comment]
Upgrade failed with too many buckets. Will try to find a bucket to nuke.

**Comment by diegs** [comment]
test upgrade from 1.7.1-tectonic.2 1.7.1-tectonic.2

**Comment by diegs** [comment]
Successful upgrade from `1.7.1-tectonic.2`, that's pretty good. I'll run an update all the way from `1.6.2` tomorrow morning.

**Comment by diegs** [comment]
And the smoke tests failed because of Azure something something per the usual.

**Comment by diegs** [comment]
@sudhaponnaganti i'm struggling to launch a 1.6.8 cluster and perform an upgrade now, but I think we can merge this since it did upgrade successfully from 1.7.1.

**Comment by sudhaponnaganti** [comment]
Can we try from 1.6.11 which has been released recently? Would it be same? 
If not let us go ahead.

**Comment by diegs** [comment]
1.6.8 issues were related to AWS. I should have a cluster up in a few minutes. I prefer to do an upgrade from a little further back.

**Comment by diegs** [comment]
Ok, running through upgrades starting at 1.6.8-1, should hopefully be done in an hour or so...

**Comment by sudhaponnaganti** [comment]
smoke test failures seem to be consistent with other runs.

**Comment by Quentin-M** [comment]
@diegs did it work?

**Comment by diegs** [comment]
@Quentin-M no

**Comment by diegs** [comment]
test upgrade from 1.7.1-tectonic.2 1.7.1-tectonic.2

**Comment by diegs** [comment]
test upgrade from 1.7.3-tectonic.1 1.7.3-tectonic.1

**Comment by diegs** [comment]
Winner winner chicken dinner!

**Comment by sudhaponnaganti** [comment]
Yay!!

**Pull request merged**
