### PR TITLE
[WIP] Reimplement Azure Scale Sets

### PR DESCRIPTION
**Pull request by justaugustus**
## Background
Currently, Tectonic Installer does not support Azure Scale Sets as a result of a limitation in the Azure VMSS API. The VMSS API does not allow a consumer to access individual nodes in a Scale Sets, meaning integration points, like Kubernetes Cloud Provider and attaching disks to individual nodes (a la Persistent Disks) is not supported.

In an effort to provide the richest feature set to all Azure customers, we made the decision to remove the Scale Sets implementation from the Tectonic Installer.

Support for Azure Scale Sets has been recently called out as a requirement in several venues, and we will need to push on the upstream Kubernetes / Microsoft Azure community to drive this forward.

This PR is intended as a reference implementation of Tectonic Installer using Azure Scale Sets and is here for testing purposes and early review. 
There are no guarantees as to its' functionality and should be considered buyer beware.

Upstream tracking PR: 
* kubernetes/kubernetes#43287
* kubernetes/features#513

Kubernetes related: 
* kubernetes/kubernetes#55833
* kubernetes/kubernetes#47511
* kubernetes/autoscaler#449
* kubernetes/autoscaler#454

Tectonic related:
* #84
* #93
* #168
* #1605

In the meantime, @alexsomesan / @s-urbaniak / @squat, would you mind taking a first pass?

cc: @robszumski / @metral / @sym3tri / @colemickens

### CODE REVIEW

**Comment by cpanato** [comment]
@justaugustus can you please rebase and resolve the conflict? thanks!

**Comment by cpanato** [comment]
@justaugustus can you please rebase and resolve the conflict? thanks!

**Comment by justaugustus** [comment]
@cpanato Thanks for following up on this! I'm going to take a look at updating the PR next week.

**Comment by justaugustus** [comment]
Closing this as it's drifted from upstream and I'm thinking of implementing it slightly differently.
Stay tuned!

**Pull request closed without merging**
