### PR TITLE
AWS - Replaced hyphens with underscores in .tf files 

### PR DESCRIPTION
**Pull request by jasminSPC**
This pull request is addressing #993

### CODE REVIEW

**Comment by cpanato** [comment]
Looks good
I found other places that the variables are using hyphen instead of underscore, like: https://github.com/StackPointCloud/tectonic-installer/blob/master/modules/bootkube/assets.tf

Or this PR will just address some files?

thanks!

**Comment by jasminSPC** [comment]
@cpanato  No I just missed `bootkube` that one.  Also this PR is related only to AWS. Thank you

**Comment by cpanato** [comment]
@jasminSPC thanks for the update

I found some other files, but I dont know if is part of this scope, maybe the route53.

modules/tectonic/crypto.tf
modules/net/calico-network-policy/assets.tf
modules/dns/route53/tectonic.tf
modules/dns/designate/tectonic.tf

**Comment by jasminSPC** [comment]
I'm wondering if we should rename the folder too `modules/net/calico-network-policy/` since data source used in `modules/net/calico-network-policy/assets.tf` was
```
data "template_file" "calico-network-policy" {
```

**Comment by alexsomesan** [comment]
ok to test

**Comment by alexsomesan** [comment]
@jasminSPC Are you also planning to do the same for the rest of the codebase?
I think we should do that, to be able to close #993 with this change.

For example, `modules/tectonic` still has occurrences of `-`. As do the other platforms.

**Comment by jasminSPC** [comment]
@alexsomesan I just realised I didn't push that folder. Sorry for inconveninece.

**Comment by jasminSPC** [comment]
@alexsomesan As for other platforms I was planning to have another PR for other platforms. Maybe it is safer that way in case we realise something was introduced after the merge.

**Comment by alexsomesan** [comment]
retest this please

**Comment by jasminSPC** [comment]
@alexsomesan I see some checks are failing but I don't have access to CI is there anything I need to fix for it to pass?

**Comment by alexsomesan** [comment]
Single flaky test. I'm re-running them.

**Comment by alexsomesan** [comment]
retest this please

**Comment by alexsomesan** [comment]
ok to test

**Pull request merged**
