### PR TITLE
Fix vulnerability in nokogiri

### PR DESCRIPTION
**Pull request by paulfantom**
This should fix a Github warning about vulnerability in nokogiri package

### CODE REVIEW

**Review by spangenberg — DISMISSED** [review]

**Comment by enxebre** [comment]
You might need to rebuild the image https://github.com/coreos/tectonic-installer/blob/track-1/images/tectonic-smoke-test-env/Dockerfile#L20

**Comment by paulfantom** [comment]
ok to test

**Comment by paulfantom** [comment]
ok to test

**Comment by paulfantom** [comment]
@enxebre @spangenberg please review

**Review by squat — APPROVED** [review]

**Pull request merged**
