### PR TITLE
add admin_email variable for designate module

### PR DESCRIPTION
**Pull request by vgkowski**
The admin_email variable was missing

### CODE REVIEW

**Comment by alexsomesan** [comment]
ok to test

**Comment by vgkowski** [comment]
can we move on ?

**Comment by cpanato** [comment]
@vgkowski thanks for your PR and apologizes for the delay to get back to you. There is a conflict in the `modules/dns/designate/variables.tf` can you rebase? Then I will look in detail the test execution.

thanks

**Comment by vgkowski** [comment]
we can close this PR as it has already been implemented

**Pull request closed without merging**
