### PR TITLE
modules/dns: Fix regressions in route53 and designate

### PR DESCRIPTION
**Pull request by lblackstone**
Behavior erroneously changed when DNS was refactored into
pluggable modules: commit 782b1724

- Properly account for experimental and vanilla flags
- Change DNS zone type back to `data`
- Update DNS records to correctly use network port rather than floating IP
- Set k8s API to use master floating IPs
- Move DNS module from dns.tf to main.tf and rename to be generic

/cc @s-urbaniak

### CODE REVIEW

**Comment by lblackstone** [comment]
@coreos/team-installer OpenStack only, good to merge

**Comment by sym3tri** [comment]
Would still like to run smoke tests on this since it's touching the AWS code

**Comment by lblackstone** [comment]
I double-checked, and the dns/route53 module isn't actually used by the AWS platform yet. That's probably the intention, but those resources are still created directly by the AWS plan at this time.

**Comment by alexsomesan** [comment]
@lblackstone your assumption is correct. PR #1293 was a first step in making the DNS support generic and interchangeable across different platforms. We're not there yet, there is still work to be done, especially in AWS.
Thanks for catching these though! I will take a look.

**Comment by alexsomesan** [comment]
ok to test

**Comment by lblackstone** [comment]
@alexsomesan Any comments on this PR? This is blocking some of the other PRs I'm working on. Thanks!

**Comment by lblackstone** [comment]
Thanks @s-urbaniak, and welcome back!

**Pull request merged**
