### PR TITLE
Cherry pick fixes + upgrade to 1.8.9_coreos.2

### PR DESCRIPTION
**Pull request by coverprice**

### CODE REVIEW

**Comment by coverprice** [comment]
ok to test

**Comment by abhinavdahiya** [comment]
test upgrade from 1.8.9-tectonic.3 1.8.9-tectonic.3

**Comment by abhinavdahiya** [comment]
test upgrade from 1.7.14-tectonic.1 1.7.14-tectonic.1

**Comment by abhinavdahiya** [comment]
test upgrade from 1.8.9-tectonic.1 1.8.9-tectonic.1

**Comment by abhinavdahiya** [comment]
> test upgrade from 1.8.9-tectonic.3 1.8.9-tectonic.3

PASSED

> test upgrade from 1.7.14-tectonic.1 1.7.14-tectonic.1

> test upgrade from 1.8.9-tectonic.1 1.8.9-tectonic.1

PASSED

**Comment by coverprice** [comment]
retest this please

**Comment by coverprice** [comment]
retest this please

**Pull request merged**
