### PR TITLE
config.tf: Update tectonic-error-server to 1.1

### PR DESCRIPTION
**Pull request by chancez**
Fixes an issue with error-server always responding with HTTP 200 codes.

### CODE REVIEW

**Comment by squat** [comment]
ok to test

**Comment by chancez** [comment]
Error is weird and seems not quite related:
```
could not find value for key "id" in tfstate file /home/ubuntu/workspace/tectonic-installer_PR-2930-GABJIYKR7Y5BH2M6ZGP5LN2MHJRHDFPJ75ELIYSNJFJKVK7XJY5Q@2/build/aws-pr-2930-3fc476



Pending: (Failures listed here are expected and do not affect your suite's status)



  1) aws-custom-tls with a cluster Interact with tectonic console can login in the tectonic console

     # Temporarily skipped with xdescribe

     # ./lib/shared_examples/k8s.rb:111



  2) aws-custom-tls with a cluster Interact with tectonic console fail to login with wrong credentials

     # Temporarily skipped with xdescribe

     # ./lib/shared_examples/k8s.rb:118



Finished in 38 minutes 33 seconds (files took 1.5 seconds to load)

9 examples, 1 failure, 2 pending



Failed examples:



rspec './spec/aws/custom_tls_spec.rb[1:1:8:1]' # aws-custom-tls with a cluster scale up worker cluster can scale up nodes by 1 worker

```

**Comment by enxebre** [comment]
hey @chancez there's conflicts con the config.tf file, can you please rebase and fix it?

**Comment by chancez** [comment]
@enxebre Rebased, and tests are passing

**Pull request merged**
