### PR TITLE
kubelet.service: Remove deprecated kubelet flags

### LINKED ISSUE #2111: [k8s 1.8] kubelet flag deprecations
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

For Kubernetes 1.8, the [kubelet.service](https://github.com/coreos/tectonic-installer/blob/master/modules/ignition/resources/services/kubelet.service) includes a couple deprecated flags that should be updated/removed.

Related to #1938 
/cc @s-urbaniak 

```
Flag --require-kubeconfig has been deprecated, You no longer need to use --require-kubeconfig. This will be removed in a future version. Providing --kubeconfig enables API server mode, omitting --kubeconfig enables standalone mode unless --require-kubeconfig=true is also set. In the latter case, the legacy default kubeconfig path will be used until --require-kubeconfig is removed.
Flag --minimum-container-ttl-duration has been deprecated, Use --eviction-hard or --eviction-soft instead. Will be removed in a future version.
```

### PR DESCRIPTION
**Pull request by lblackstone**
Fixes #2111

### CODE REVIEW

**Comment by squat** [comment]
ok to test

**Comment by lblackstone** [comment]
Rebased to resolve a conflict with 89a6298bd974eaa59b391c9e6cd8218d9e70665c

**Comment by lblackstone** [comment]
Azure tests passed before, so probably a flake?

**Comment by lblackstone** [comment]
@squat Tests have passed now.

**Comment by squat** [comment]
@diegs I’ll make a corresponding PR in KVO to update these flags as well

**Comment by diegs** [comment]
@squat there is no way to update kubelet service files for existing clusters. We might be able to take this patch if it does not change behavior and we really have to, but it is going to introduce skew.

**Comment by squat** [comment]
This warrants further discussion. We need a story around this because deprecated flags will become incompatible flags and then we are broken.

**Comment by cpanato** [comment]
hello, @lblackstone can you please rebase and fix the conflict? thanks

**Comment by lblackstone** [comment]
@cpanato Rebased

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
tests are green. Need some review @squat can you take a look when you have some time?

**Pull request closed without merging**
