### PR TITLE
tests: Report specific smoke test status to GitHub

### PR DESCRIPTION
**Pull request by mxinden**

### CODE REVIEW

**Comment by mxinden** [comment]
ok to test

**Comment by mxinden** [comment]
@cpanato Could you review this?

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
@mxinden when you click in the `details` for each feedback it redirects to `https://example.com/build/status` and not to our Jenkins. Can you please take a look on that?

**Comment by mxinden** [comment]
ok to test

**Comment by mxinden** [comment]
@sym3tri In the status field of this PR you can see the detailed Jenkins status feedback. Does this look good to you?

**Comment by mxinden** [comment]
@cpanato Could you give this another review?

**Comment by sym3tri** [comment]
@mxinden This is great. 

As a follow-up, it'd be even better if you can override the test title to be a short description instead of just the file path.

**Comment by squat** [comment]
@mxinden looks great so far. Do you want to address Ed's comment in a follow up PR or in this one?

**Comment by mxinden** [comment]
@squat I will address it here. There is an additional feature discussed offline to report the status of the basic tests separately as well and make that one required instead of the overall status.

**Comment by mxinden** [comment]
ok to test

**Comment by mxinden** [comment]
ok to test

**Comment by mxinden** [comment]
ok to test

**Comment by mxinden** [comment]
ok to test

**Comment by mxinden** [comment]
ok to test

**Comment by mxinden** [comment]
@kyoto @ggreer With this PR I would like to introduce running the "GUI Tests" stage only when the `run-gui-tests` Github label is set. This way we don't need to run the tests on pure backend changes. Does this sound reasonable to you two or are there any objections?

**Comment by kyoto** [comment]
@mxinden Adding a `run-gui-tests` label seems reasonable to me, especially as they are likely to get slower over time as we add more checks.

**Comment by mxinden** [comment]
@cpanato Could you give this another review? I fixed the stashing issue by reducing the scope of the stashing to only those files necessary (See https://github.com/coreos/tectonic-installer/pull/2082/commits/50b31d0c60dd56fbe5296d5c0d542dd6e48106ef). Let me know if this looks good to you.

**Comment by cpanato** [comment]
retest this please

**Comment by mxinden** [comment]
@cpanato What is the concern? 

In case you are worried about the delay introduced by this change: The last test execution of this PR was 45 minutes. Last master execution was 48 minutes.

**Comment by cpanato** [comment]
@mxinden more in terms of doing the checkout every time during the build. but this will be fixed when we implement the new builder :)

**Pull request merged**
