### PR TITLE
modules/dns: Only create public DNS records if public IPs exist

### PR DESCRIPTION
**Pull request by lblackstone**
Fix bug introduced by #1875

### CODE REVIEW

**Comment by squat** [comment]
ok to test

**Comment by lblackstone** [comment]
Please hold off on merging. Doing some further testing, and looks like this might not have completely fixed the problem.

**Comment by lblackstone** [comment]
I seem to be hitting this bug: https://github.com/hashicorp/terraform/issues/10857

Going to refactor the logic slightly.

**Comment by lblackstone** [comment]
@s-urbaniak RFR again. Was bitten by some quirks of the Terraform interpolation, but found a workaround.

**Comment by lblackstone** [comment]
Sorry, still not working :(

**Comment by lblackstone** [comment]
I was able to get this working with an ugly hack. I'm open to suggestions on making this cleaner, but I spent most of the day working on it already, and wasn't able to find a better solution with the current version of Terraform.

**Comment by lblackstone** [comment]
@s-urbaniak Are CI failures related to this change? Any suggestion on improving this workflow?

**Comment by squat** [comment]
@lblackstone CI looks beautiful. There was a flake in the bare-metal test that is unrelated to these changes.

**Pull request merged**
