### PR TITLE
module/update-payload: Include TNO in the payload as well.

### PR DESCRIPTION
**Pull request by yifan-gu**
A follow up PR to the release automation repo is required to fully update the payload.

### CODE REVIEW

**Comment by yifan-gu** [comment]
@thorfour Good call, updated (not aware of the depends_on before).
But I found that the next time I run `terraform apply .` it won't generate the manifests for TNO as it thinks that the `./generate/app_versions` and `./generate/operators` already exists, so the the `local_file` resources get executed first...

Not a big deal as in the release automation script, we can always make sure to rm `./generate` first.

**Comment by yifan-gu** [comment]
retest this please

**Comment by yifan-gu** [comment]
Baremetal and aws all passed.
Retesting azure.

**Comment by yifan-gu** [comment]
retest this please

**Comment by cpanato** [comment]
all green

**Pull request merged**
