### PR TITLE
config.tf: bump dex to v2.7.1

### PR DESCRIPTION
**Pull request by rithujohn191**
Cherry-picked the PR off master

### CODE REVIEW

**Comment by sudhaponnaganti** [comment]
Thanks

**Comment by alexsomesan** [comment]
@rithujohn191 Just a quick tip: in order to trigger the smoke tests on a PR it needs to labeled with *run-smoke-tests*. All CoreOS contributors have should have permissions to add that label.
This is to control what gets executed in PR checkers and keep the infra costs in check.

**Comment by rithujohn191** [comment]
Thanks Alex. I have been adding this label to all my PRs to the installer master branch. Didnt add it to this since its the release branch. Next time I'll keep in mind that it's needed for the release branch as well

**Comment by Quentin-M** [comment]
Most tests passed. Merging.

**Pull request merged**
