### PR TITLE
Append the base domain to the VPC name

### PR DESCRIPTION
**Pull request by bsiegel**
Proposing a change - this maintains the same naming convention as the previous Tectonic installer.

### CODE REVIEW

**Comment by ggreer** [comment]
ok to test

**Comment by s-urbaniak** [comment]
@bsiegel Thanks a lot for the PR! This unfortunately needs a rebase.

/cc @alexsomesan for a 2nd opinion

**Comment by bsiegel** [comment]
@s-urbaniak Rebased!

**Comment by cpanato** [comment]
@bsiegel Thanks for your PR, can you please rebase?

**Comment by bsiegel** [comment]
@cpanato rebased!

**Comment by cpanato** [comment]
One flaky in Azure when trying to delete one resource. Might be caused by some MS issue. However, the tests for this specific test was green.

@s-urbaniak @alexsomesan can you guys please review this PR?
thanks

**Pull request merged**
