### PR TITLE
config.tf: bump dex to 2.8.1

### PR DESCRIPTION
**Pull request by rithujohn191**

### CODE REVIEW

**Comment by squat** [comment]
ok to test

**Comment by cpanato** [comment]
I guess our UI tests will fail because of dex changed the interface. I will update the tests

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
retest this please

**Comment by ericchiang** [comment]
All of the CI links 404 for me. What's the correct way to see the test results?

**Comment by cpanato** [comment]
all green now @squat can you review again?

**Pull request merged**
