### PR TITLE
config.tf, payload.json: Bump KVO to v1.6.8-kvo.2

### PR DESCRIPTION
**Pull request by rithujohn191**

### CODE REVIEW

**Comment by rithujohn191** [comment]
test upgrade from 1.6.8-tectonic.1 1.6.8-tectonic.1

**Comment by Quentin-M** [comment]
test upgrade from 1.6.7-tectonic.1 1.6.7-tectonic.1

**Comment by Quentin-M** [comment]
```
=== RUN   TestUpgrade
=== RUN   TestUpgrade/before_upgrade
F0816 22:59:46.758910    2242 client.go:38] Cannot load config for REST client: Error loading config file "/kubeconfig": read /kubeconfig: is a directory
goroutine 51 [running]:
github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog.stacks(0x2665500, 0xc400000000, 0x9a, 0xed)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog/glog.go:769 +0xa5
github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog.(*loggingT).output(0x2645200, 0xc400000003, 0xc4202aae40, 0x25c8b83, 0x9, 0x26, 0x0)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog/glog.go:720 +0x357
github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog.(*loggingT).printf(0x2645200, 0xc400000003, 0x1a46f63, 0x26, 0xc42012de68, 0x1, 0x1)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog/glog.go:655 +0x14c
github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog.Fatalf(0x1a46f63, 0x26, 0xc42012de68, 0x1, 0x1)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog/glog.go:1148 +0x67
github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/coreos-inc/operator-client/pkg/client.NewClient(0xc420010070, 0xb, 0xc420010070, 0xb)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/coreos-inc/operator-client/pkg/client/client.go:38 +0x26f
github.com/coreos-inc/tectonic-upgrade-test/tests.newKubeClient(0xc4202aad80, 0xc420458f58, 0x45f133)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/tests/upgrade_test.go:57 +0x69
github.com/coreos-inc/tectonic-upgrade-test/tests.beforeUpgradeTest(0xc4202aad80)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/tests/upgrade_test.go:70 +0x37
testing.tRunner(0xc4202aad80, 0x1ae3820)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
exit status 255
FAIL	github.com/coreos-inc/tectonic-upgrade-test/tests	0.091s
```

Oh well..

**Comment by diegs** [comment]
```
Running tests
=== RUN   TestUpgrade
=== RUN   TestUpgrade/before_upgrade
=== RUN   TestUpgrade/upgrade
panic: test timed out after 30m0s
```

Looks like the upgrade timed out :(

**Comment by Quentin-M** [comment]
test upgrade from 1.6.7-tectonic.1 1.6.7-tectonic.1

**Comment by Quentin-M** [comment]
Yet another time-out.. This doesn't look too good..

**Comment by Quentin-M** [comment]
Yet another time-out.. This doesn't sound good..
I will push the payload somewhere tomorrow and try manually..

**Comment by diegs** [comment]
It looks like some of the pods are not coming up. Maybe someone should grab the kubeconfig from the logs and look at the cluster while the test is running to see what's up.

**Comment by rithujohn191** [comment]
I'll try that

**Comment by rithujohn191** [comment]
test upgrade from 1.6.7-tectonic.1 1.6.7-tectonic.1

**Comment by rithujohn191** [comment]
test upgrade from 1.6.7-tectonic.1 1.6.7-tectonic.1

**Comment by rithujohn191** [comment]
Should we be worried about:
```
tectonic-monitoring-auth-prometheus-2344627856-qnxb1               0/1       CrashLoopBackOff
```

**Comment by diegs** [comment]
I mean, maybe--logs?

**Comment by rithujohn191** [comment]
Kubeconfig doesn't let me in. Just saw these in the old Jenkins logs.

**Comment by rithujohn191** [comment]
test upgrade from 1.6.7-tectonic.1 1.6.7-tectonic.1

**Comment by diegs** [comment]
error: pathspec '1.6.7-tectonic.1\r\n' did not match any file(s) known to git.

You have to make sure you have no newlines when you trigger the test :(

**Comment by rithujohn191** [comment]
test upgrade from 1.6.7-tectonic.1 1.6.7-tectonic.1

**Comment by Quentin-M** [comment]
```
E0817 18:57:02.770221       1 kube_version_operator.go:188] error updating to 1.6.8+tectonic.1: Failed update of component: deployment/kube-system/kube-scheduler due to: Deployment.apps "kube-scheduler" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"k8s-app":"kube-scheduler", "pod-anti-affinity":"kube-scheduler-1.6.8-tectonic.1", "tier":"control-plane"}: `selector` does not match template `labels`
```

See KVO #225

**Comment by diegs** [comment]
Separately from that we're seeing that the console never comes up. The test shouldn't proceed in that case; I put up https://github.com/coreos-inc/tectonic-upgrade-test/pull/30 to fix that.

**Comment by Quentin-M** [comment]
test upgrade from 1.6.7-tectonic.1 1.6.7-tectonic.1

**Comment by Quentin-M** [comment]
Worked for my 1.6.7 cluster.

**Comment by Quentin-M** [comment]
```
Running tests
=== RUN   TestUpgrade
=== RUN   TestUpgrade/before_upgrade
=== RUN   TestUpgrade/upgrade
=== RUN   TestUpgrade/after_upgrade
--- PASS: TestUpgrade (427.63s)
    --- PASS: TestUpgrade/before_upgrade (0.05s)
    --- PASS: TestUpgrade/upgrade (427.46s)
    	upgrade_test.go:129: upgrade completed: current: 1.6.8-tectonic.1 desired: 1.6.8-tectonic.1 target: 
    --- PASS: TestUpgrade/after_upgrade (0.12s)
PASS
ok  	github.com/coreos-inc/tectonic-upgrade-test/tests	427.705s
Finishing the test
```

**Pull request merged**
