### PR TITLE
Documentation/*: Merge tectonic/Doc into tectonic-installer/Doc

### PR DESCRIPTION
**Pull request by joshix**
- Moves docs from old to new repo
- marker run leaving only false positive or known-TODO links
- renames install/"metal" to "bare-metal"

- Not addressed here/TODO:
   - Links in ldap onboard-* and etcd docs
   - Updates and QA for new TF GUI installs

### CODE REVIEW

**Comment by robszumski** [comment]
Why break all of the links to rename `bare-metal` to `metal`?

**Comment by joshix** [comment]
@robszumski Because I wrote it backwards then followed my own instructions and did it backwards.

**Comment by Quentin-M** [comment]
Forget the CI, go for it! Thanks lots!

**Comment by dghubble** [comment]
@joshix @robszumski This repo should use "metal" as the platform name, not "bare-metal" The way all the platform conventions work dictates this: Makefile used to build docs, corresponds to file names and directories, corresponds to variable names in tfvars.

**Pull request merged**
