### PR TITLE
config.tf: bump hyperkube to 1.6.8

### PR DESCRIPTION
**Pull request by squat**
cc @Quentin-M

### CODE REVIEW

**Comment by Quentin-M** [comment]
Thank you @squat!
/cc @diegs for a KVO bump.

**Comment by Quentin-M** [comment]
```
+ ln -sf /home/ubuntu/workspace/tectonic-installer_PR-1665-M7IPESDFCS3KEHEVP6S6QGNZWHB6O4SPQNLZYJT2QWZE5YP65FWA /go/src/github.com/coreos/tectonic-installer
ln: failed to create symbolic link '/go/src/github.com/coreos/tectonic-installer': Permission denied
```

That's new, did Jenkins got modified?

**Comment by squat** [comment]
@Quentin-M was just wondering that myself

**Comment by Quentin-M** [comment]
ok to test

**Comment by Quentin-M** [comment]
This changed too?

@mxinden Could you help me out? Thank you!

**Comment by mxinden** [comment]
@Quentin-M @squat Our Jenkins configuration is checked into this Github repository via the Jenkinsfile. On the one hand this means we can test old revisions the way we tested them back then. On the other hand this also means we will face the same issues with Jenkins that we have been facing back then, whenever we test old revisions.

We have fixed the permission denied issue before in #1350, #1436 and #1400, but these commits are not part of this PR, or the 1.6.8 branch. My guess from the error message would be, that a cherry-pick of #1350 should fix it, but moving from tectonic-builder `v1.20` to `v1.31` might break things as there will be other changes included in the Docker image as well.

Let me know if I can be of any help here?

**Comment by yifan-gu** [comment]
test upgrade from 1.6.7-tectonic.2 1.6.7-tectonic.2

**Comment by Quentin-M** [comment]
Unfortunately, we are avoiding to cherry-pick anything more than is required for the release.

**Comment by Quentin-M** [comment]
Thanks for pointing these out. We are trying to avoid cherry-picking anything more than is required for the release. These three PRs together have over 400 lines. The first one, as you said, might be enough but what does the builder bump involve?

**Comment by Quentin-M** [comment]
I just tried to cherry-pick #1350 but it is not even cherry-pickable by itself as it requires #1338 first (which is required to make the tests work - since Jenkins changed to using a parameter).

**Comment by Quentin-M** [comment]
@yifan-gu 

```
=== RUN   TestUpgrade/before_upgrade
F0814 22:03:11.682823    2249 client.go:38] Cannot load config for REST client: Error loading config file "/kubeconfig": read /kubeconfig: is a directory
goroutine 35 [running]:
github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog.stacks(0x2665500, 0xc400000000, 0x9a, 0xed)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog/glog.go:769 +0xa5
github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog.(*loggingT).output(0x2645200, 0xc400000003, 0xc420080f00, 0x25c8b83, 0x9, 0x26, 0x0)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog/glog.go:720 +0x357
github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog.(*loggingT).printf(0x2645200, 0xc400000003, 0x1a46f63, 0x26, 0xc42054de68, 0x1, 0x1)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog/glog.go:655 +0x14c
github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog.Fatalf(0x1a46f63, 0x26, 0xc42054de68, 0x1, 0x1)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog/glog.go:1148 +0x67
github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/coreos-inc/operator-client/pkg/client.NewClient(0xc420010070, 0xb, 0xc420010070, 0xb)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/coreos-inc/operator-client/pkg/client/client.go:38 +0x26f
github.com/coreos-inc/tectonic-upgrade-test/tests.newKubeClient(0xc420080e40, 0xc4200d1f58, 0x45f133)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/tests/upgrade_test.go:57 +0x69
github.com/coreos-inc/tectonic-upgrade-test/tests.beforeUpgradeTest(0xc420080e40)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/tests/upgrade_test.go:70 +0x37
testing.tRunner(0xc420080e40, 0x1ae3820)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
exit status 255
FAIL	github.com/coreos-inc/tectonic-upgrade-test/tests	0.084s
```

**Comment by Quentin-M** [comment]
```
=== RUN   Test
=== RUN   Test/Common
=== RUN   Test/Common/APIAvailable
=== RUN   Test/Cluster
=== RUN   Test/Cluster/AllNodesRunning
=== RUN   Test/Cluster/GetIdentityLogs
=== RUN   Test/Cluster/AllPodsRunning
=== RUN   Test/Cluster/KillAPIServer
=== RUN   Test/QA
=== RUN   Test/QA/StatsEmitterLogs
--- PASS: Test (82.83s)
    --- PASS: Test/Common (0.56s)
        --- PASS: Test/Common/APIAvailable (0.56s)
        	common_test.go:20: API server is available.
    --- PASS: Test/Cluster (81.23s)
        --- PASS: Test/Cluster/AllNodesRunning (0.19s)
        	cluster_test.go:67: node ip-10-0-0-155.ca-central-1.compute.internal ready
        	cluster_test.go:67: node ip-10-0-11-41.ca-central-1.compute.internal ready
        	cluster_test.go:67: node ip-10-0-28-35.ca-central-1.compute.internal ready
        	cluster_test.go:67: node ip-10-0-43-81.ca-central-1.compute.internal ready
        	cluster_test.go:94: Successfully found 4 ready nodes.
        --- PASS: Test/Cluster/GetIdentityLogs (0.32s)
        	cluster_test.go:114: Successfully gathered identity logs.
        --- PASS: Test/Cluster/AllPodsRunning (0.23s)
        	cluster_test.go:34: All pods are ready.
        --- PASS: Test/Cluster/KillAPIServer (80.50s)
        	smoke_test.go:112: failed with error: old API server kube-apiserver-97v67 still running
        	smoke_test.go:113: retrying in 10s
        	smoke_test.go:112: failed with error: old API server kube-apiserver-97v67 still running
        	smoke_test.go:113: retrying in 10s
        	smoke_test.go:112: failed with error: old API server kube-apiserver-97v67 still running
        	smoke_test.go:113: retrying in 10s
        	smoke_test.go:112: failed with error: failed to get API server pod: Get https://qmachu-api.tectonic.dev.coreos.systems:443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-apiserver: EOF
        	smoke_test.go:113: retrying in 10s
        	smoke_test.go:112: failed with error: old API server kube-apiserver-97v67 still running
        	smoke_test.go:113: retrying in 10s
        	smoke_test.go:112: failed with error: API server has not yet been running for more than one check
        	smoke_test.go:113: retrying in 10s
        	smoke_test.go:112: failed with error: API server has not yet been running for more than one check
        	smoke_test.go:113: retrying in 10s
        	cluster_test.go:218: API server pods successfully came back up.
    --- PASS: Test/QA (1.04s)
        --- PASS: Test/QA/StatsEmitterLogs (1.04s)
        	qa_test.go:35: Successfully verified stats-emitter success in logs.
PASS
```

**Comment by squat** [comment]
All tests pass for me.

<details>
bin/smoke --cluster --test.v
=== RUN   Test
=== RUN   Test/Common
=== RUN   Test/Common/APIAvailable
=== RUN   Test/Cluster
=== RUN   Test/Cluster/AllNodesRunning
=== RUN   Test/Cluster/GetIdentityLogs
=== RUN   Test/Cluster/AllPodsRunning
=== RUN   Test/Cluster/KillAPIServer
--- PASS: Test (58.78s)
    --- PASS: Test/Common (0.54s)
        --- PASS: Test/Common/APIAvailable (0.54s)
                common_test.go:20: API server is available.
    --- PASS: Test/Cluster (58.24s)
        --- PASS: Test/Cluster/AllNodesRunning (0.19s)
                cluster_test.go:67: node ip-10-0-1-172.ca-central-1.compute.internal ready
                cluster_test.go:67: node ip-10-0-34-53.ca-central-1.compute.internal ready
                cluster_test.go:67: node ip-10-0-40-34.ca-central-1.compute.internal ready
                cluster_test.go:67: node ip-10-0-58-99.ca-central-1.compute.internal ready
                cluster_test.go:94: Successfully found 4 ready nodes.
        --- PASS: Test/Cluster/GetIdentityLogs (0.40s)
                cluster_test.go:114: Successfully gathered identity logs.
        --- PASS: Test/Cluster/AllPodsRunning (0.22s)
                cluster_test.go:34: All pods are ready.
        --- PASS: Test/Cluster/KillAPIServer (57.44s)
                smoke_test.go:112: failed with error: old API server kube-apiserver-b8wtr still running
                smoke_test.go:113: retrying in 10s
                smoke_test.go:112: failed with error: old API server kube-apiserver-b8wtr still running
                smoke_test.go:113: retrying in 10s
                smoke_test.go:112: failed with error: failed to get API server pod: Get https://red-api.tectonic.dev.coreos.systems:443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-apiserver: EOF
                smoke_test.go:113: retrying in 10s
                smoke_test.go:112: failed with error: failed to get API server pod: Get https://red-api.tectonic.dev.coreos.systems:443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-apiserver: EOF
                smoke_test.go:113: retrying in 10s
                smoke_test.go:112: failed with error: API server has not yet been running for more than one check
                smoke_test.go:113: retrying in 10s
                cluster_test.go:218: API server pods successfully came back up.
PASS

**Pull request merged**
