### PR TITLE
aws: use existing security groups for masters/workers [previously #1163]

### PR DESCRIPTION
**Pull request by alexsomesan**
This is just to test rebasing of #1389

### CODE REVIEW

**Comment by alexsomesan** [comment]
PR hooks not working on the original PR

**Comment by sym3tri** [comment]
@alexsomesan Can we close out #1389 now that this replaces it?

**Comment by alexsomesan** [comment]
Yes, I would say so. I'll close that one out.

**Comment by alexsomesan** [comment]
ok to test

**Comment by alexsomesan** [comment]
On closer inspection, it looks like this change duplicates functionality already present in the installer.

We already have input variables `tectonic_aws_*_extra_sg_ids` that allow injecting additional external security groups.
This change aims to introduce new inputs that provide the same functionality.

**Pull request closed without merging**
