### PR TITLE
kvo: 1.7.1-kvo.1, tco: 0.4.0

### PR DESCRIPTION
**Pull request by diegs**

### CODE REVIEW

**Comment by diegs** [comment]
Will need to cherry-pick into 1.7.1-release branch.

**Comment by Quentin-M** [comment]
just cherry-picked it on top of the 1.7.1 branch.

**Comment by yifan-gu** [comment]
Should run upgrade test on this.

**Comment by diegs** [comment]
@yifan-gu we will once 1.6.7+tectonic.2 is ready...

**Pull request merged**
