### PR TITLE
frontend: Upgrade React to v15.6.2 and other dependencies

### PR DESCRIPTION
**Pull request by kyoto**
Upgrade
- React from 15.3.2 to 15.6.2
- React Router from 4.1.2 to 4.2.2
- Redux from 3.5.2 to 3.7.2
- React Redux from 4.4.8 to 5.0.6
- Redux Thunk from 2.1.2 to 2.2.0
- whatwg-fetch from 1.0.0 to 2.0.3
- A few dev dependencies

Also removes `react-modal`, which is no longer being used.

### CODE REVIEW

**Comment by kyoto** [comment]
ok to test

**Comment by squat** [comment]
Seeing this error with the yarn.lock file:

```
+ make dirtycheck
outdated yarn.lock (commit it to fix)
Makefile:73: recipe for target 'dirtycheck' failed
make: *** [dirtycheck] Error 1
script returned exit code 2
```

**Comment by cpanato** [comment]
@kyoto is it possible squash the commits?

**Comment by kyoto** [comment]
@squat I fixed the yarn.lock problem with @cpanato's help. Could you review again? Will squash the commits if you prefer.

**Pull request merged**
