### PR TITLE
config.tf: bump versions for 1.8.4-tectonic.3

### PR DESCRIPTION
**Pull request by diegs**
- console
- kvo
- kubernetes
- tectonic

### CODE REVIEW

**Comment by diegs** [comment]
test upgrade from 1.7.9-tectonic.3 1.7.9-tectonic.3

**Comment by sudhaponnaganti** [comment]
@yifan-gu - can you review and approve it

**Comment by sudhaponnaganti** [comment]
@diegs - Are we updating K8 version as well. I see that line changed in config.tf

**Comment by diegs** [comment]
@sudhaponnaganti yes, that is what signals the KVO to upgrade the components it manages (in this case, console)

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
re-running only on `Azure` because `AWS` and `Bare Metal` already passed.

**Comment by cpanato** [comment]
All tests are green. expect for the `upgrade-test`

**Comment by cpanato** [comment]
Ran conformance tests manually against `AWS` and all good

```
Ran 125 of 699 Specs in 3165.770 seconds
SUCCESS! -- 125 Passed | 0 Failed | 0 Pending | 574 Skipped PASS
```

**Comment by diegs** [comment]
test upgrade from 1.7.9-tectonic.3 1.7.9-tectonic.3

**Comment by diegs** [comment]
test upgrade from 1.7.9-tectonic.3 1.7.9-tectonic.3

**Comment by sudhaponnaganti** [comment]
@yifan-gu - can you do review so this can be merged

**Comment by diegs** [comment]
I just realized that @cpanato disabled the other test platforms (aws, bare metal) but they passed before and the only change is a small KVO bump. I still think this is fine to merge.

**Pull request merged**
