### PR TITLE
Update Terraform to v0.9.6

### PR DESCRIPTION
**Pull request by Quentin-M**
Now that Terraform v0.9.6 is [out](https://github.com/hashicorp/terraform/releases/tag/v0.9.6), there is no need to keep using a custom version anymore. This PR aims at bumping Terraform to the latest official release.

### CODE REVIEW

**Comment by Quentin-M** [comment]
Tests passed. Testing again.

**Comment by Quentin-M** [comment]
ok to test

**Comment by sym3tri** [comment]
please dont merge until we get some other RCs out

**Comment by kans** [comment]
@Quentin-M would you rebase this PR please?

**Comment by Quentin-M** [comment]
Rebased.

**Comment by Quentin-M** [comment]
Rebased.

**Comment by Quentin-M** [comment]
Tests passed. Github had a massive outage towards the end of the test and therefore it seems that Jenkins was not able to report back. Can we merge, so I can cherry-pick to the release branch and we can cut an RC? :octocat: 🐑

**Pull request merged**
