### PR TITLE
Update changelog with 1.7.3-tectonic.2

### PR DESCRIPTION
**Pull request by robszumski**

### CODE REVIEW

**Comment by sudhaponnaganti** [comment]
@robszumski -version number need to be updated in the change log - 1.7.3-tectonic.2 - This is second rev of the release

**Comment by sudhaponnaganti** [comment]
Not sure why the checks are failing

**Comment by yifan-gu** [comment]
test upgrade from 1.7.1-tectonic.2 1.7.1-tectonic.2

**Comment by yifan-gu** [comment]
Can someone kick off the CI test? @alexsomesan @s-urbaniak @Quentin-M ?
Upgrade test works fine (in fact we already released today)

**Comment by cpanato** [comment]
Don't need to run the smoke tests for this PR. I've aborted the Jenkins build.

**Pull request merged**
