### PR TITLE
modules/ignition,platforms/*: Allow NFS configuration on CL nodes

### PR DESCRIPTION
**Pull request by kalmog**
This will allow for the configuration of NFS to, for example, specify
versions of NFS protocol that may be used.  It is flexible enough to
allow any configuration desired by allowing the contents of the config
file to be passed in as a tfvar.

refactoring of #2701

### CODE REVIEW

**Comment by kalmog** [comment]
Retest this please

**Comment by cpanato** [comment]
Retest this please

**Comment by cpanato** [comment]
Retest this please. aws

**Comment by cpanato** [comment]
Retest this please. aws

**Comment by cpanato** [comment]
Retest this please. metal

**Comment by cpanato** [comment]
@kalmog for metal it failed:

```
- resource 'matchbox_group.controller' config: "nfs_config_rendered" is not a valid output for module "ignition_masters"
- resource 'matchbox_group.worker' config: "nfs_config_rendered" is not a valid output for module "ignition_workers"
```

**Comment by kalmog** [comment]
bare-metal is green. retest this please. aws

**Comment by cpanato** [comment]
retest this please. azure/metal

**Comment by kalmog** [comment]
retest this please, govcloud

**Comment by cpanato** [comment]
retest this please, govcloud

**Comment by kalmog** [comment]
retest this please, govcloud

**Pull request merged**
