### PR TITLE
Azure tests: templates to generate external resources needed by tests

### PR DESCRIPTION
**Pull request by alexsomesan**
These templates generate the external resources needed by certain tests, such as a vnet + subnets or a pre-existing DNS zone.

They are not yet fully integrated with the tests and for now need to be created by hand using `terraform apply` in each of these folders.

/cc: @mxinden

### CODE REVIEW

**Comment by mxinden** [comment]
Related to https://github.com/coreos/tectonic-installer/issues/1461

**Comment by mxinden** [comment]
@alexsomesan Can you make the changes in `vars/extern-exper.tfvars` as well?

**Comment by alexsomesan** [comment]
All new changes look good to me. Let's merge.

**Comment by mxinden** [comment]
Removed outdated `pre_vnet` resource group.

**Pull request merged**
