### PR TITLE
monitoring: 1.7.3 release - bump monitoring to 1.5.2, CRD compatiblity

### PR DESCRIPTION
**Pull request by colhom**
cherry-pick of #1776 on to 1.7.3 release branch

\cc @Quentin-M

### CODE REVIEW

**Comment by Quentin-M** [comment]
Unfortunately, it looks like we can't get that in.

**Comment by colhom** [comment]
Ack- we should definitely wait until the monitoring folks say the new versions are ready :)

**Comment by brancz** [comment]
We actually have a story of removing the monitoring manifests all together from the tectonic installer, and instead just let them be provisioned by the TPO, so I think we can actually just close this.

https://github.com/coreos/tectonic-installer/pull/1656

**Comment by s-urbaniak** [comment]
as per comment https://github.com/coreos/tectonic-installer/pull/1779#issuecomment-325579900, closing this.

**Pull request closed without merging**
