### PR TITLE
*: update etcd-operator to 0.5.0 and bootkube to 0.6.2

### PR DESCRIPTION
**Pull request by hongchaodeng**

### CODE REVIEW

**Comment by squat** [comment]
ok to test

**Comment by squat** [comment]
ok to test

**Comment by squat** [comment]
ok to test

**Comment by squat** [comment]
One azure smoke test flaked. Testing again for more confidence.

**Comment by squat** [comment]
ok to test

**Comment by cpanato** [comment]
@squat @hongchaodeng all green now :)

**Comment by hongchaodeng** [comment]
Thanks @cpanato @squat

**Pull request merged**
