### PR TITLE
tectonic: remove monitoring assets

### PR DESCRIPTION
**Pull request by brancz**
As discussed with @sym3tri and @mxinden, we're removing the monitoring assets in favor of them being fully managed by the Tectonic Prometheus Operator.

/cc @fabxc 

This is missing some tests that @mxinden will take care of so until then, hold off on merging.

### CODE REVIEW

**Comment by mxinden** [comment]
Related Jira story: https://coreosdev.atlassian.net/browse/INST-115

**Comment by alexsomesan** [comment]
ok to test

**Comment by brancz** [comment]
@mxinden I know we just yesterday talked about this, but I wasn't aware that friday is already code freeze for the october release. Any chance we can get this done by then? Or get this merged and add the test afterwards?

**Comment by mxinden** [comment]
@brancz I am pretty much done with my sprint goals. I will see what I can achieve tomorrow. Only if this is very urgent I am fine with merging without tests.

**Comment by brancz** [comment]
I spoke to @pst and it seems we actually have time until in two weeks as only then the final code freeze for the october release will be in place. So turns out it was false alarm from my side. Sorry about that!

**Comment by s-urbaniak** [comment]
Just a big 👍 from my side for this PR :-)

**Comment by fabxc** [comment]
🎉 :shipit:

**Comment by cpanato** [comment]
Waiting for monitoring team, then we can merge it

**Comment by cpanato** [comment]
all green @brancz

**Pull request merged**
