### PR TITLE
Change console to serve on port 8080.

### LINKED ISSUE #847: Console should not run on port 80 if possible
Currently the console listens on port 80 (https://github.com/coreos/tectonic-installer/blob/master/modules/tectonic/resources/manifests/console/deployment.yaml#L42). It is behind a service (https://github.com/coreos/tectonic-installer/blob/master/modules/tectonic/resources/manifests/console/service.yaml) also exposing 80.

Listening on a low port requires running the pod as root or granting it `CAP_NET_BIND_SERVICE`. Would it be possible to run the console pod on a non-privileged port such as 8080 and then just set that `targetPort` in the service?

cc @amrutac @aaronlevy @sym3tri

### PR DESCRIPTION
**Pull request by diegs**
Also make it run as non-root.

Fixes #847

### CODE REVIEW

**Comment by squat** [comment]
@diegs this does not correct the ingress resource. handled in #855

**Comment by kans** [comment]
Looks fine - your tests are running in Singapore... and just timed out?  I kicked them off again.

**Comment by diegs** [comment]
I think we're leaving this for the next release. cc @sym3tri

**Comment by amrutac** [comment]
Code looks good, just need to spin up a cluster with these changes and test the console.

**Comment by kans** [comment]
Would you rebase this on master please for better tests?

**Comment by diegs** [comment]
Done.

**Comment by sym3tri** [comment]
@diegs yea. i guess don't merge this until the release goes out. or we need to create a release branch now.

**Comment by diegs** [comment]
Just launched a cluster, non-root console running on 8080 appears to work great.

**Pull request merged**
