### PR TITLE
config.tf: updated version string for 1.7.3 patch release

### PR DESCRIPTION
**Pull request by sudhaponnaganti**

### CODE REVIEW

**Comment by cpanato** [comment]
saw this error on CI
```

outdated payload (run '/home/ubuntu/workspace/tectonic-installer_PR-1883-XAOMN3MLQUZEZHPU2DSNS3NGMCWNPBP3ADYQHIZWEHHYNN3D62MA/modules/update-payload/make-update-payload.sh' to fix)
``` 

cc @sudhaponnaganti @Quentin-M

**Comment by cpanato** [comment]
close and re-open to refresh the labels

**Comment by sudhaponnaganti** [comment]
@Quentin-M seeing different type of error during PR merge

**Comment by Quentin-M** [comment]
You need to run 'make payload' and commit the result.

**Comment by Quentin-M** [comment]
@sudhaponnaganti Most smoke tests passed. This is good to merge imho.

**Pull request merged**
