### PR TITLE
config.tf: Bump tectonic version and kubernetes appversion.

### PR DESCRIPTION
**Pull request by yifan-gu**

### CODE REVIEW

**Comment by yifan-gu** [comment]
test upgrade from 1.7.5-tectonic.1 1.7.5-tectonic.1

**Comment by sudhaponnaganti** [comment]
@yifan-gu  -  Can you check on this. Blocking release

**Comment by yifan-gu** [comment]
Tests are passing, the status is not reported back. I think it's ok to merge.

**Comment by sudhaponnaganti** [comment]
@yifan-gu  @squat - I see that building Docker image has problems. Can this be fixed? 
- Also VMWare tests are not executed. I am not sure if we have any unless they are being used for BM

**Comment by squat** [comment]
@sudhaponnaganti vmware is currently less than pre-alpha and does not have any automated tests to be executed

**Comment by edevil** [comment]
So Tectonic on VMware is still not production ready? Since I saw a guide for it I assumed it was.

**Comment by sym3tri** [comment]
@edevil squat is correct, it is not production-ready yet, we are still working on some remaining issues/features.

**Pull request merged**
