### PR TITLE
frontend: Add loading spinner to restore modal

### PR DESCRIPTION
**Pull request by kyoto**
screenshot-1

### CODE REVIEW

**Comment by kans** [comment]
`Verifying Progress` would be more accurate.

**Comment by robszumski** [comment]
Can we use our dot processing pattern from the Console?

**Comment by kyoto** [comment]
Thanks @robszumski. I changed it to use the 3 dots pattern and updated the screenshot.

**Comment by robszumski** [comment]
Can we swap the order, so the dots are on the left, and text on the right?

**Comment by kyoto** [comment]
ok to test

**Comment by kyoto** [comment]
ok to test

**Comment by kyoto** [comment]
ok to test

**Comment by kyoto** [comment]
ok to test

**Comment by kyoto** [comment]
ok to test

**Pull request merged**
