### PR TITLE
config.tf: Bump kvo, tco, tcluo for 1.9.6

### PR DESCRIPTION
**Pull request by yifan-gu**
Bump kvo to v1.9.6-kvo.3, tco to 0.6.4, tcluo to v0.3.2

### CODE REVIEW

**Comment by yifan-gu** [comment]
test upgrade from 1.8.9-tectonic.2 1.8.9-tectonic.2

**Comment by yifan-gu** [comment]
test upgrade from 1.8.7-tectonic.2 1.8.7-tectonic.2

**Comment by yifan-gu** [comment]
test upgrade from 1.8.7-tectonic.2 1.8.7-tectonic.2

**Comment by yifan-gu** [comment]
test upgrade from 1.8.7-tectonic.2 1.8.7-tectonic.2

**Comment by yifan-gu** [comment]
test upgrade from 1.8.7-tectonic.2 1.8.7-tectonic.2

**Comment by yifan-gu** [comment]
test upgrade from 1.8.7-tectonic.2 1.8.7-tectonic.2

**Comment by abhinavdahiya** [comment]
retest this please. azure only

**Comment by abhinavdahiya** [comment]
retest this please. azure only

**Comment by yifan-gu** [comment]
test upgrade from 1.8.7-tectonic.2 1.8.7-tectonic.2

**Comment by yifan-gu** [comment]
retest this please. azure only

**Pull request merged**
