### PR TITLE
frontend: Upgrade JS dependencies.

### PR DESCRIPTION
**Pull request by ggreer**
- Use 1.x notation instead of ^1.0 notation (which lots of people seem to get confused about).
- Bump patch-level of most outdated dependencies.
- Run `yarn upgrade`

There's no need to pin the version in package.json now that we're using yarn.lock. `yarn install` uses the yarn.lock file. `yarn upgrade` looks in package.json and updates yarn.lock with the latest available version.

### CODE REVIEW

**Comment by ggreer** [comment]
And yes, this does result in a working installer GUI :)

**Comment by sym3tri** [comment]
While you're in there... mind updating the README with whatever is required to get it running? NPM/Node versions etc.

**Comment by ggreer** [comment]
Already in: https://github.com/coreos/tectonic-installer/tree/master/installer#frontend

**Comment by sym3tri** [comment]
oops. thanks!

**Pull request merged**
