### PR TITLE
[TEST ONLY]*: test bootkube with etcd-operator 0.5.0

### PR DESCRIPTION
**Pull request by hongchaodeng**
Build a bootkube image with PR https://github.com/kubernetes-incubator/bootkube/pull/686

Testing the jenkins here as discussed with @squat

### CODE REVIEW

**Comment by hongchaodeng** [comment]
cc @xiang90 @hasbro17

**Comment by squat** [comment]
closing and re-opening to trigger tests.

**Comment by squat** [comment]
One of the azure tests seems to have flaked during bring up. Because it's testing the etcd operator, is like to test again for confidence.

**Comment by squat** [comment]
ok to test

**Comment by hongchaodeng** [comment]
This error is suspicious:

```
module.workers.azurerm_virtual_machine.tectonic_worker.1: Still creating... (2m30s elapsed)
null_resource.tectonic: Still creating... Error applying plan:

1 error(s) occurred:

* null_resource.tectonic: 1 error(s) occurred:

* Script exited with non-zero exit status: 1

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
make: *** [apply] Error 1
```

@squat Any idea what does it mean?

**Comment by squat** [comment]
@hongchao, yes, this is because the tectonic.service unit is failing. Let's debug manually tomorrow.

**Comment by hongchaodeng** [comment]
The latest commit can pass all the tests in some combination.

**Comment by cpanato** [comment]
ok to test

**Comment by cpanato** [comment]
for some weird reason, Jenkins are complaining about the `structure-check` 

`make: *** No rule to make target 'structure-check'.  Stop.`

can you please rebase?

**Comment by hongchaodeng** [comment]
@cpanato 
Sorry for the late update.
We will cut a release of bootkube today and update this PR ( @squat  maybe create a new one?) .

**Comment by squat** [comment]
@hongchaodeng yes, v0.6.2 will be out shortly. We can create a new PR then to eliminate the noise from this thread.

**Comment by hongchaodeng** [comment]
Yep. Closing this.

**Pull request closed without merging**
