### PR TITLE
azure: make root_volume_size configurable for aws parity

### PR DESCRIPTION
**Pull request by rubbish**
The OS image defaults to a 32GiB disk, however, it'd be nice to configure this so we can make it larger.

### CODE REVIEW

**Comment by justaugustus** [comment]
@alexsomesan can you take a peep at this?
We've got a customer asking for this as well.

**Comment by mxinden** [comment]
We did some changes (https://github.com/coreos/tectonic-installer/pull/2082) to the testing process. Please rebase on to current master, so that the `basic-tests` PR status is reported correctly.

**Comment by rubbish** [comment]
@mxinden @justaugustus @alexsomesan Rebased.

**Comment by justaugustus** [comment]
@rubbish would you mind rebasing this again and then running `make structure-check`?
You may also need to run `terraform fmt .` and `make docs examples` prior to pushing.

**Comment by rubbish** [comment]
@justaugustus Done.

**Comment by cpanato** [comment]
@rubbish can you please rebase? then I will run the tests. thanks!

**Comment by rubbish** [comment]
@cpanato Done

**Comment by cpanato** [comment]
ok to test

**Comment by cpanato** [comment]
@rubbish can you please run ` 'make examples'` to fix the issues?

```
outdated examples (run 'make examples' to fix)

Makefile:147: recipe for target 'structure-check' failed

```

**Comment by rubbish** [comment]
@cpanato Updated the examples and rebased again.

**Comment by cpanato** [comment]
@rubbish 
some errors from the init phase:
```
Error getting plugins: 3 problems:


- module "etcd": missing required argument "root_volume_size"

- module "masters": missing required argument "root_volume_size"

- module "workers": missing required argument "root_volume_size"

make: *** [terraform-init] Error 1

```

**Comment by sym3tri** [comment]
Thanks for the contribution, but I'm going close this b/c it looks like the same functionality was just merged in #2944.

**Pull request closed without merging**
