### PR TITLE
Revert "Removed addon operator managed manifests and added installation of addon operator"

### PR DESCRIPTION
**Pull request by cpanato**
Reverts coreos/tectonic-installer#2465

@thorfour @diegs This broke self hosted etcd deployments, because bootkubeexpectes `kube-dns` as part of the target control-plane deployment (see: https://github.com/kubernetes-incubator/bootkube/blob/bf8078176305fd37c3e392e3d097745a3da2e5a3/pkg/bootkube/bootkube.go#L80)

### CODE REVIEW

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
one failure in the destroy phase

**Comment by Quentin-M** [comment]
This revert broke the payload generation again that was fixed by https://github.com/coreos/tectonic-installer/pull/2475 after https://github.com/coreos/tectonic-installer/pull/2465 broke it. Should I revert my fix too?

```
* template_dir.payload_appversions: key "kubernetes_addon" does not exist in map var.tectonic_versions in: ${var.tectonic_versions["kubernetes_addon"]}
```

**Comment by thorfour** [comment]
Yea probably revert those as well. I'm going to open a PR to remove the self-hosted etcd tests and I'll reopen a PR with those fixes.

**Comment by Quentin-M** [comment]
Thank you!

**Comment by Quentin-M** [comment]
https://github.com/coreos/tectonic-installer/pull/2485 Anyone for the green? Ty

**Pull request merged**
