### PR TITLE
modules/aws/vpc Allow us to customise subnets allowed to console

### PR DESCRIPTION
**Pull request by mrwacky42**
Maybe I do not want the entire internet testing the security of the
Tectonic console. Allow me to override.

### CODE REVIEW

**Comment by squat** [comment]
@mrwacky42 by convention, variables in platforms/aws/variables.tf should be AWS-specific configuration, and this prefixed with `tectonic_aws_`. This would really be a good feauture for all platforms. Could you extend this to work for Azure clusters as well and move this variable declaration to config.tf? Otherwise we can keep it specific to AWS and rename the variable to make it clear that it only works for one cloud provider, however this feature disparity is non-ideal since it is not a technical limitation. If you need help or guidance please do not hesitate to ask for a hand. Thanks for the contribution.

**Comment by mrwacky42** [comment]
@squat - I can add the `tectonic_aws` prefix. I'm ignorant of how Azure works, so I'd rather avoid going down that rabbit hole. I've updated the variable name for now.

**Comment by mxinden** [comment]
@mrwacky42 Could you rebase to current master? Otherwise our CI will not start testing your changes. Thanks for the improvements!

I will leave the approval up to @squat.

**Comment by mrwacky42** [comment]
@mxinden - rebased!

**Comment by mxinden** [comment]
ok to test

**Comment by mrwacky42** [comment]
Meanwhile, I'd like some advice on how to proceed here. While this code works, the `kube-apiserver` pods run on the masters and connect to the Tectonic console via the ELB . With this PR, I would have to also pass in the master public IP addresses to the `vpc` module in order to get them blessed to access the console. However, the master nodes are an autoscale group, so the public IPs are unknowable when Terraform runs.

Log excerpt from a `kube-apiserver` pod:
> I1102 18:53:56.363373       8 logs.go:41] go-oidc: provider config sync failed, retrying in 1m0s: Get https://tectonic.redacted.example.com/identity/.well-known/openid-configuration: dial tcp W.X.Y.Z:443: getsockopt: connection timed out

Is there a way to have the api server talk to an internal tectonic-console service instead of the public user facing ELB?

**Comment by mrwacky42** [comment]
*ping*

**Comment by enxebre** [comment]
retest this please

**Comment by enxebre** [comment]
Hey @mrwacky42 thanks a lot for this and apologies for the inactivity. We've been going through big architecture redesign and  the code here will soon be migrating to a new repo where new features requests will be considerated. More detailed information will be shared soon

**Pull request closed without merging**
