### PR TITLE
frontend: Set tectonic_aws_external_vpc_public in output tfvars.

### PR DESCRIPTION
**Pull request by ggreer**
Depends on #664.

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@evfurman is it possible for you to test it this PR in conjunction with #664, i.e. using a local build?

**Comment by sym3tri** [comment]
UI changes:
- Add a checkbox that appears _only_ if user selects a _public_ hosted zone.
- Defaults to checked (value is "")
- When checked off value is same public hosted zone ID from dropdown.
- Text is: "Optimize VPC networking by associating a new private hosted zone ([see AWS documentation]())."

@alexsomesan to provide link to docs.

**Comment by ggreer** [comment]
screen shot 2017-05-18 at 14 19 16

Just need the doc URL and this is ready.

**Comment by ggreer** [comment]
For now I've made the doc URL https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-dns.html#vpc-private-hosted-zones

**Comment by alexsomesan** [comment]
I think this one is a bit more comprehensive and it also explains the
split-view technique that we use and also touches on the exact resolution
steps when using both private and public.

http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zones-private.html

What do you think?

I can also write something up on how this approach allows us to avoid
public DNS outages affecting intra-cluster communications.

**Comment by ggreer** [comment]
OK, link updated.

**Comment by meghanschofield** [comment]
@ggreer We're doing a quick UX round! We will update soon...

**Comment by alexsomesan** [comment]
Merged #664 

There's still some UX work happening here, right?

**Comment by robszumski** [comment]
@alexsomesan Yes, hoping to finish that up today

**Comment by meghanschofield** [comment]
@kans here are the updated mocks! IRL discussion:

- create a dropdown for Optimize DNS
- swap order of screen elements

#### Default Screen, Optimize DNS
default screen - don t optimize

#### Additional drop down choice:
optimize option

^^^ @tlwu2013 check it out!

**Comment by ggreer** [comment]
Continued in #788.

**Pull request closed without merging**
