### PR TITLE
operators: Pin operators to master nodes.

### PR DESCRIPTION
**Pull request by yifan-gu**
Also reorder the yaml manifest fields lexicographically.
https://jira.coreos.com/browse/CORS-459

### CODE REVIEW

**Comment by yifan-gu** [comment]
retest this please

**Comment by yifan-gu** [comment]
cc @cpanato @alexsomesan

**Comment by cpanato** [comment]
@sym3tri  do we need to cherry pick this to track1?

**Comment by sym3tri** [comment]
@cpanato nope.

**Comment by alexsomesan** [comment]
Enabling testing for GPC and GovCloud.

**Comment by alexsomesan** [comment]
retest this please

**Comment by cpanato** [comment]
retest this please. now only on aws and azure

**Comment by cpanato** [comment]
all green

**Comment by yifan-gu** [comment]
All green, merged, thank you @cpanato  @alexsomesan

**Pull request merged**
