### PR TITLE
config.tf: Bump console to v1.7.0

### PR DESCRIPTION
**Pull request by amrutac**

### CODE REVIEW

**Comment by Quentin-M** [comment]
It's really funny to see GitHub states I mentioned this PR, while my comment was edited by @amrutac, who actually made the mention 👍

**Comment by Quentin-M** [comment]
OK on Bare-Metal.

**Comment by Quentin-M** [comment]
ok to test

**Comment by amrutac** [comment]
ok to test

**Comment by amrutac** [comment]
ok to test

**Comment by Quentin-M** [comment]
Testing manually on AWS.

**Comment by Quentin-M** [comment]
Would we happen to have a quick fix for https://github.com/coreos/tectonic-installer/pull/1178#issuecomment-310766690 maybe?

**Comment by Quentin-M** [comment]
Digged a tiny bit in ^, only happens at reboot when an update happened. Not critical enough. Can fix in another version!

**Comment by amrutac** [comment]
@Quentin-M: I have a fix out, will get it in if I tag another release.

**Pull request merged**
