### PR TITLE
Update signing scripts

### PR DESCRIPTION
**Pull request by yifan-gu**
Enable signing a staging payload without yubikey.
Enable overwriting the staging payload when submitting the release payload.

### CODE REVIEW

**Comment by yifan-gu** [comment]
Tested manually, by default it has the same effect as before unless `SIGN_WITH_TEST_KEY=true` is set when running `./sign-payload.sh`

**Comment by yifan-gu** [comment]
I will update the QA / release doc to reflect the changes.

**Comment by yifan-gu** [comment]
Changes in docs https://github.com/coreos-inc/tectonic/pull/1751

**Comment by Quentin-M** [comment]
Thank you~

**Comment by Quentin-M** [comment]
I'm sorry, I didn't see it failed with 

```
In ../modules/update-payload/sign-payload.sh line 52:
  trap "rm -rf '${GNUPGHOME}'" EXIT
                ^-- SC2064: Use single quotes, otherwise this expands now rather than when signalled.
```

**Pull request merged**
