### PR TITLE
[WIP] Revert "Bump console to v2.5.3."

### PR DESCRIPTION
**Pull request by mxinden**
Reverts coreos/tectonic-installer#2498

### CODE REVIEW

**Comment by mxinden** [comment]
ok to test

**Comment by squat** [comment]
Ah my mistake; I didn’t realize that PR didn’t have tests run

**Comment by cpanato** [comment]
did a fix for the tests: https://github.com/coreos/tectonic-installer/pull/2501

**Comment by squat** [comment]
Closing in favor of #2501

**Pull request closed without merging**
