### PR TITLE
tests/ci: Keep Jenkins build logs for at least one week

### PR DESCRIPTION
**Pull request by cpanato**

### CODE REVIEW

**Comment by mxinden** [comment]
@cpanato What does the "-1" mean?

**Comment by cpanato** [comment]
@mxinden means no value. we will keep the build in days only and not in # of builds

**Comment by mxinden** [comment]
@cpanato How about we set it to 1000? Just in case we have a messed up trigger that loops.

**Comment by cpanato** [comment]
@mxinden done

**Pull request merged**
