### PR TITLE
config.tf: Bump TCO to 0.5.3, KVO to v1.7.3-kvo.3.

### PR DESCRIPTION
**Pull request by yifan-gu**
TCO: Minor logging tweaks.
KVO: Add migration for configmap for console.

### CODE REVIEW

**Comment by yifan-gu** [comment]
KVO is not cut yet, blocked by https://github.com/coreos-inc/kube-version-operator/pull/235

**Comment by Quentin-M** [comment]
@yifan-gu Is there still something blocking the 1.7.3-kvo.3 release?

**Comment by Quentin-M** [comment]
Tested in https://github.com/coreos/tectonic-installer/pull/1778.

**Pull request merged**
