### PR TITLE
config.tf: Bump kvo to v1.8.4-kvo.8 which knows how to upgrade from the 1.7.14 release.

### PR DESCRIPTION
**Pull request by yifan-gu**
Such releases are needed when a new 1.7 release is cut, see the [doc](https://github.com/coreos-inc/kube-version-operator/blob/master/RELEASE.md) for more details.

The AppVersion `kubernetes` doesn't need to be bumped, because the 1.8.4+tectonic.2 spec hasn't changed.

### CODE REVIEW

**Comment by yifan-gu** [comment]
test upgrade from 1.7.9-tectonic.4 1.7.9-tectonic.4

**Comment by yifan-gu** [comment]
Need to test upgrade again once we built an rc for the 1.7.14 release.

**Comment by cpanato** [comment]
Tests for bare metal will fail because the certificate for matchbox is expired.

**Comment by cpanato** [comment]
fixed the metal certificates for the tests, and rebase. testing it again

**Comment by yifan-gu** [comment]
test upgrade from 1.7.9-tectonic.4 1.7.9-tectonic.4

**Pull request merged**
