### PR TITLE
config.tf: Bump kvo to v1.7.14-kvo.1 and tectonic version to 1.7.14-tectonic.1

### PR DESCRIPTION
**Pull request by yifan-gu**

### CODE REVIEW

**Comment by yifan-gu** [comment]
test upgrade from 1.7.9-tectonic.4 1.7.9-tectonic.4

**Comment by yifan-gu** [comment]
test upgrade from 1.7.9-tectonic.4 1.7.9-tectonic.4

**Comment by yifan-gu** [comment]
test upgrade from 1.7.9-tectonic.4 1.7.9-tectonic.4

**Comment by yifan-gu** [comment]
test upgrade from 1.7.9-tectonic.4 1.7.9-tectonic.4

**Comment by yifan-gu** [comment]
restest this please

**Comment by yifan-gu** [comment]
ok to test

**Comment by cpanato** [comment]
Tests will not work in this branch. I will run manually in some platforms/configs and will merge this if works

**Comment by cpanato** [comment]
Tests failed due to the tests with the console which is outdated.
I tested manually in aws/azure, was able to log in and perform some actions.

**Comment by cpanato** [comment]
merging.

**Pull request merged**
