### PR TITLE
Fix syntax error in Jenkinsfile

### PR DESCRIPTION
**Pull request by ethernetdan**
There missing a closing }

### CODE REVIEW

**Comment by ethernetdan** [comment]
Validating here: https://jenkins-tectonic-installer.prod.coreos.systems/job/coreos%20-%20tectonic-installer/job/tectonic-installer/job/fix-jenkinsfile/1/console

/cc @Quentin-M @sym3tri

**Comment by ethernetdan** [comment]
Fixed the syntax error but revealed:
```
wrong files: modules/azure/master/variables.tf modules/azure/worker/variables.tf modules/bootkube/assets.tf modules/bootkube/assets_tls.tf modules/tectonic/assets.tf platforms/azure/variables.tf
```
any ideas?

**Comment by Quentin-M** [comment]
@ethernetdan Fix is in https://github.com/coreos/tectonic-installer/pull/275.

**Comment by ethernetdan** [comment]
Rebasing on #275

**Comment by ethernetdan** [comment]
Closing in favor of #269 so we can test jenkins on the branch

**Pull request closed without merging**
