### PR TITLE
config.tf: Update tectonic-cluo-operator to v0.3.1

### PR DESCRIPTION
**Pull request by dghubble**
https://github.com/coreos-inc/tectonic-cluo-operator/releases/tag/v0.3.1

### CODE REVIEW

**Comment by alexsomesan** [comment]
smoke tests label missing. re-testing.

**Comment by alexsomesan** [comment]
retest this please

**Comment by sym3tri** [comment]
This PR needs to be made against the `1.8.7` branch

**Comment by cpanato** [comment]
retest this please.

**Comment by dghubble** [comment]
Looks like this got cherry-picked already. Thanks https://github.com/coreos/tectonic-installer/pull/2871

**Comment by cpanato** [comment]
retest this please. azure/govcloud

**Comment by cpanato** [comment]
retest this please. azure

**Pull request merged**
