### PR TITLE
Replace CNI providers with tectonic-network-operator

### PR DESCRIPTION
**Pull request by dghubble**
Tectonic wants to use tectonic-network-operator to setup flannel, calico, canal, etc. This PR attempts to add it and replace the templates manifests previously used.

* Add `tectonic-network-operator` to bootkube module to bootstrap chosen CNI provider
* Copy Tectonic pull secret to the bootkube module. `tectonic-network-operator` is private so the pull secret must exist in both `kube-system` and `tectonic-system`.
* Remove `net/*` modules. Referencing them in top-level platform `tectonic.tf` because those modules read files that exist in the bootkube module (wtf)
* Move `tectonic-network-operator` ConfigMap into the `bootkube` module and the `kube-system` cluster config so it exists during control plane bootstrapping

### Breakage

This breaks vanilla k8s mode (if it ever worked?). Its going to be pretty tricky to try to maintain both static network provider manifests of different sorts and tectonic-network-operator modes of bootstrapping.

rel: #2484

### CODE REVIEW

**Comment by dghubble** [comment]
I don't think the Tectonic pull secret has access to the Quay repo.

```
  Warning  Failed                 5s (x3 over 50s)   kubelet, node3.example.com  Failed to pull image "quay.io/coreos/tectonic-network-operator-dev:462d0bc29d48ff361ad88a0036879e59b999b092": rpc error: code = Unknown desc = Error: Status 403 trying to pull repository coreos/tectonic-network-operator-dev: "{\"error\": \"Permission Denied\"}"
```

**Comment by dghubble** [comment]
Hooray. I got the components to start on bare-metal. Not able to bootstrap the control plane yet:

```
NAMESPACE     NAME                                                  READY     STATUS    RESTARTS   AGE
kube-system   bootstrap-kube-apiserver-node1.example.com            1/1       Running   0          40s
kube-system   bootstrap-kube-controller-manager-node1.example.com   1/1       Running   0          29s
kube-system   bootstrap-kube-scheduler-node1.example.com            1/1       Running   0          44s
kube-system   kube-apiserver-x5pxf                                  1/1       Running   0          1m
kube-system   kube-controller-manager-656854d8f6-9wjpr              0/1       Pending   0          1m
kube-system   kube-proxy-jflqk                                      1/1       Running   0          1m
kube-system   kube-proxy-q5766                                      1/1       Running   0          1m
kube-system   kube-proxy-rwxvq                                      1/1       Running   0          1m
kube-system   kube-scheduler-585b65cb77-9lxwc                       0/1       Pending   0          1m
kube-system   pod-checkpointer-fm4wv                                1/1       Running   0          1m
kube-system   pod-checkpointer-fm4wv-node1.example.com              1/1       Running   0          1m
kube-system   tectonic-network-operator-kvwt9                       1/1       Running   0          1m
kube-system   tectonic-network-operator-v9d4t                       1/1       Running   0          1m
```

```
I1214 21:13:52.005440       1 run.go:30] tectonic-network-operator starting
I1214 21:13:52.007489       1 leaderelection.go:174] attempting to acquire leader lease...
E1214 21:13:52.604664       1 event.go:260] Could not construct reference to: '&v1.ConfigMap{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"network-config", GenerateName:"", Namespace:"tectonic-system", SelfLink:"/api/v1/namespaces/tectonic-system/configmaps/network-config", UID:"af89c5a5-e113-11e7-818b-525400a19cae", ResourceVersion:"526", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63648882832, loc:(*time.Location)(0x5647c86b7800)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"control-plane.alpha.kubernetes.io/leader":"{\"holderIdentity\":\"node3.example.com\",\"leaseDurationSeconds\":90,\"acquireTime\":\"2017-12-14T21:13:52Z\",\"renewTime\":\"2017-12-14T21:13:52Z\",\"leaderTransitions\":0}"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Data:map[string]string(nil)}' due to: 'no kind is registered for the type v1.ConfigMap'. Will not report event: 'Normal' 'LeaderElection' 'node3.example.com became leader'
I1214 21:13:52.604841       1 leaderelection.go:184] successfully acquired lease tectonic-system/network-config
I1214 21:13:52.605001       1 run.go:42] started leading: running tectonic-network-operator
E1214 21:13:52.605263       1 render.go:130] failed to populate templates: failed to create temp dir: mkdir 895730119: permission denied
E1214 21:13:53.705153       1 update.go:243] error checking for pause status: the server could not find the requested resource
E1214 21:13:53.705344       1 update.go:49] Error checking for pause status: the server could not find the requested resource
E1214 21:14:04.709078       1 update.go:243] error checking for pause status: the server could not find the requested resource
E1214 21:14:04.709112       1 update.go:49] Error checking for pause status: the server could not find the requested resource
E1214 21:14:15.713315       1 update.go:243] error checking for pause status: the server could not find the requested resource
E1214 21:14:15.713332       1 update.go:49] Error checking for pause status: the server could not find the requested resource
```

**Comment by dghubble** [comment]
It takes a lot of work to get the installer to function, so I'll leave some notes. I use the bare-metal variant and setup a local QEMU/KVM environment (see [docs](https://github.com/coreos/matchbox/blob/master/Documentation/getting-started-docker.md)). Start the environment.

```
sudo ./scripts/devnet create
```

Build tectonic-installer:

```
cd installer
make
./bin/linux/installer
```

Type in all the info needed (see matchbox scripts/libvirt for MAC addresses, run `ssh-add -L` for ssh your ssh pubkey, get license and pull secret from tectonic.com). At the end there is no "save progress". At the end click manual download, NOT Submit.

Get the assets.zip and extract it.

```
unzip assets.zip
cd cluster_2017-12-14_15-36-33
terraform plan platform/metal
terraform apply platform/metal
```

Now boot the VMs.

```
sudo ./scripts/libvirt create
```

Watch them with virt-manager or ssh in `ssh core@node1.example.com`. Use the generated kubeconfig once bootstrapping in progress.

```
KUBECONFIG=cluster_2017-12-14_15-36-33/generated/auth/kubeconfig
kubectl get nodes
```

So far, the cluster doesn't get past control plane bootstrapping.

**Comment by dghubble** [comment]
Newer tectonic-network-operator image gets a bit futher:

```
I1214 23:57:47.256813       1 run.go:30] tectonic-network-operator starting                                                                                                                                        
I1214 23:57:47.458417       1 leaderelection.go:174] attempting to acquire leader lease...                                                                                                                         
E1214 23:57:47.856292       1 event.go:260] Could not construct reference to: '&v1.ConfigMap{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"network-config", GenerateName:"", Namespa
ce:"tectonic-system", SelfLink:"/api/v1/namespaces/tectonic-system/configmaps/network-config", UID:"95e688e8-e12a-11e7-8970-525400a19cae", ResourceVersion:"551", Generation:0, CreationTimestamp:v1.Time{Time:time
.Time{wall:0x0, ext:63648892667, loc:(*time.Location)(0x55ec5231b7a0)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{
"control-plane.alpha.kubernetes.io/leader":"{\"holderIdentity\":\"node2.example.com\",\"leaseDurationSeconds\":90,\"acquireTime\":\"2017-12-14T23:57:47Z\",\"renewTime\":\"2017-12-14T23:57:47Z\",\"leaderTransitio
ns\":0}"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Data:map[string]string(nil)}' due to: 'no kind is registered for the type v1.
ConfigMap'. Will not report event: 'Normal' 'LeaderElection' 'node2.example.com became leader'                                                                                                                     
I1214 23:57:47.856510       1 leaderelection.go:184] successfully acquired lease tectonic-system/network-config                                                                                                    
I1214 23:57:47.857987       1 run.go:42] started leading: running tectonic-network-operator                                                                                                                        
E1214 23:57:49.561205       1 update.go:233] error checking for pause status: the server could not find the requested resource                                                                                     
E1214 23:57:49.561306       1 update.go:29] Error checking for pause status: the server could not find the requested resource                                                                                      
E1214 23:58:00.565296       1 update.go:233] error checking for pause status: the server could not find the requested resource
```

**Comment by cpanato** [comment]
@dghubble can you please rebase and resolve the conflicts?

**Comment by enxebre** [comment]
FYI Vanilla kubernetes support it's being removed https://github.com/coreos/tectonic-installer/pull/2629

**Pull request closed without merging**
