### PR TITLE
aws/azure: bump terraform provider

### PR DESCRIPTION
**Pull request by cpanato**

### CODE REVIEW

**Comment by cpanato** [comment]
retest this please

**Comment by squat** [comment]
Azure just errored again with:

```
Error: Error applying plan:

1 error(s) occurred:

* module.vnet.azurerm_virtual_network.tectonic_vnet: 1 error(s) occurred:

* azurerm_virtual_network.tectonic_vnet: Error waiting for completion of Virtual Network "exa-pr-2902-39dcff" (Resource Group "tectonic-cluster-exa-pr-2902-39dcff"): Long running operation terminated with status 'Failed': Code="InternalServerError" Message="An error occurred."
```

Could this be hitting a resource limit? @cpanato

**Comment by cpanato** [comment]
@squat I guess not. I think it is an azure issue.

**Comment by cpanato** [comment]
I will update gcp in another PR

cc @alexsomesan

**Comment by justaugustus** [comment]
I was just thinking of submitting this!
@cpanato / @alexsomesan, can we bump azurerm to `1.1.1` instead?

**Comment by cpanato** [comment]
sure, i will update this @justaugustus

**Comment by cpanato** [comment]
@squat  / @alexsomesan  can I get your reviews again?

**Pull request merged**
