### PR TITLE
tectonic-channel-operator: 0.3.4

### PR DESCRIPTION
**Pull request by diegs**

### CODE REVIEW

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by yifan-gu** [comment]
Fixes https://github.com/coreos/tectonic-installer/issues/925

**Comment by yifan-gu** [comment]
Upgrade tests passed. Trying a couple more times.

**Comment by yifan-gu** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
@yifan-gu @kans tests look solid

**Pull request merged**
