### PR TITLE
config.tf: kvo v1.7.5-kvo.6

### PR DESCRIPTION
**Pull request by diegs**

### CODE REVIEW

**Comment by diegs** [comment]
test upgrade from 1.7.3-tectonic.2 1.7.3-tectonic.2

**Comment by Quentin-M** [comment]
The PR is on master, for which upgrade tests are broken until I find time with Yifan to fix them.. :(
So sorry about the inconvenience.
Making the PR against 1.7.5 (once the console bump goes into 1.7.5) will work tho.

**Comment by diegs** [comment]
Sure, I'll put up a 1.7.5 PR with the payload now.

**Comment by diegs** [comment]
https://github.com/coreos/tectonic-installer/pull/1987

**Pull request merged**
