### PR TITLE
Pending Items from track-1

### PR DESCRIPTION
**Pull request by cpanato**

### CODE REVIEW

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
github/jenkins are bit weird:

build is running here: https://jenkins-tectonic-installer.prod.coreos.systems/blue/organizations/jenkins/tectonic-installer/detail/PR-2891/2/pipeline/

**Comment by enxebre** [comment]
this branch probably need rebase, the govcloud commits are already in 1.8.7
https://github.com/coreos/tectonic-installer/commit/a9b7c12fcbf786c757d38ff153acce5ae7fb3132
https://github.com/coreos/tectonic-installer/commit/e3086a29087020657b6848f8772e9979eaea1910
https://github.com/coreos/tectonic-installer/commit/e3086a29087020657b6848f8772e9979eaea1910
https://github.com/coreos/tectonic-installer/commit/eb88b44a34be7705ef7907f8dabdcac2f386c722
https://github.com/coreos/tectonic-installer/commit/20784f3b235ab0024cbefb0af330da3f2c020a0a

**Comment by cpanato** [comment]
then this PR makes no sense. closing.

**Pull request closed without merging**
