### PR TITLE
modules/bootkube: always deploy etcd operator

### PR DESCRIPTION
**Pull request by squat**
The etcd operator should always be deployed, even if k8s etcd is *not*
self-hosted. This was cluster users can still manage hosted clusters.

fixes: https://github.com/coreos/tectonic-installer/issues/1549

cc @Quentin-M @alexsomesan @robszumski

### CODE REVIEW

**Comment by Quentin-M** [comment]
That's awesome! Thank you!

**Comment by Quentin-M** [comment]
```
misformatted files (run 'terraform fmt .' to fix): modules/bootkube/assets.tf
```

**Comment by squat** [comment]
@Quentin-M just fixed it. Plz cherry-pick again

**Comment by xiang90** [comment]
@squat @Quentin-M Can you ping etcd operator team when we make change like this? Thanks!

**Pull request merged**
