### PR TITLE
Fix spelling of console zone id output

### PR DESCRIPTION
**Pull request by mrwacky42**
Before creating your PR, please make sure to add the appropriate GitHub labels
like e.g. `run-smoke-tests` + `platform/<xxx>`. For more details see
[tests/README.md](../tests/README.md).

(In case you don't have permissions to add labels, please ask a
[Maintainer](../MAINTAINERS).)

### CODE REVIEW

**Comment by enxebre** [comment]
hey @mrwacky42 thanks a lot! we'll need to change the references as well /aws/main.tf lines 230 and 232

**Comment by mrwacky42** [comment]
@enxebre - Fixed!

**Comment by enxebre** [comment]
ok to test

**Comment by enxebre** [comment]
retest this please

**Pull request merged**
