### PR TITLE
azure-terraform: extract correct cloud config for custom vnet

### LINKED ISSUE #3192: azure: wrong values for vnetName and subnetName in k8s cloud config when external vnet/subnet is specified
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

### Tectonic version:
```
1.8.9-tectonic.2
```

### Terraform version:

```
Terraform v0.11.5
```
### Platform:

```
azure
```

### What happened?

When providing custom/external vnet using Terraform variable `tectonic_azure_external_vnet_id`, the complete vnet id is passed to the Kubernetes cloud config variable `vnetName`.

Similar when providing custom/external subnet for workers using Terraform variable `tectonic_azure_external_worker_subnet_id`, the name of the vnet is passed to the Kubernetes cloud config variable `subnetName` instead of the actual name of the subnet.

### What you expected to happen?
Pass correct vnet name and subnet name.

### How to reproduce it (as minimally and precisely as possible)?

1. Follow normal installation instructions and provide custom values for `tectonic_azure_external_vnet_id` and/or `tectonic_azure_external_worker_subnet_id`
2. `/etc/kubernetes/cloud/config` will have wrong values for `vnetName` and/or `subnetName`

### References

- Fixed in proposed pull request #3188

### PR DESCRIPTION
**Pull request by torresdal**
The cloud config `/etc/kubernetes/cloud/config` for Azure had id's in `vnetName` and `subnetName` when custom vnet (`tectonic_azure_external_vnet_id`) was used, instead of just names. This fixes this issue by extracting names from the vnet id and subnet id, to correctly generate cloud config for Azure.

Fixes #3192

### CODE REVIEW

**Comment by torresdal** [comment]
ok to test

**Comment by enxebre** [comment]
hey @torresdal thanks! can you please rebase the PR?

**Comment by enxebre** [comment]
rebase seems incorrect, this PR should be only one commit on top of track-1

**Comment by spangenberg** [comment]
Will be closed in favour of https://github.com/coreos/tectonic-installer/pull/3325

**Pull request closed without merging**
