### PR TITLE
Bumped Hyperkube, KVO, and Tectonic versions to support 1.8.14

### PR DESCRIPTION
**Pull request by coverprice**

### CODE REVIEW

**Comment by coverprice** [comment]
ok to test

**Comment by abhinavdahiya** [comment]
following https://github.com/coreos/tectonic-installer/pull/3103

**Comment by abhinavdahiya** [comment]
retest this please

**Comment by abhinavdahiya** [comment]
test upgrade from 1.8.9-tectonic.3 1.8.9-tectonic.3

**Comment by abhinavdahiya** [comment]
```console
[tectonic-installer_PR-3334-4A35BICLRJJHQMT4RO3MUPVLWOERXLQT5LEVKUNJ52YQKJOOHOXQ] Running shell script

+ cd tests/rspec

+ bundler exec rubocop --cache false spec lib

/usr/lib/ruby/vendor_ruby/bundler/definition.rb:179:in `rescue in specs': Your bundle is locked to nokogiri (1.8.1), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of nokogiri (1.8.1) has removed it. You'll need to update your bundle to a different version of nokogiri (1.8.1) that hasn't been removed in order to install. (Bundler::GemNotFound)

	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:173:in `specs'

	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:233:in `specs_for'

	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:222:in `requested_specs'

	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:118:in `block in definition_method'

	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:19:in `setup'

	from /usr/lib/ruby/vendor_ruby/bundler.rb:99:in `setup'

	from /usr/lib/ruby/vendor_ruby/bundler/setup.rb:20:in `<top (required)>'

	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

script returned exit code 1
```
:fearful: 

from https://jenkins-tectonic-installer.prod.coreos.systems/blue/organizations/jenkins/tectonic-installer/detail/PR-3334/2/pipeline

**Comment by coverprice** [comment]
ok to test

**Comment by abhinavdahiya** [comment]
test upgrade from 1.8.9-tectonic.3 1.8.9-tectonic.3

**Comment by abhinavdahiya** [comment]
retest this please

**Comment by abhinavdahiya** [comment]
test upgrade from 1.8.9-tectonic.3 1.8.9-tectonic.3

**Comment by abhinavdahiya** [comment]
@coverprice 
`jenkins/upgrade-test` is green
all aws except `smoke-tests/aws/vpc_internal` is green.

**Comment by coverprice** [comment]
retest this please

**Comment by coverprice** [comment]
retest this please

**Comment by coverprice** [comment]
retest this please

**Comment by abhinavdahiya** [comment]
retest this please

**Comment by coverprice** [comment]
retest this please

**Comment by abhinavdahiya** [comment]
retest this please

**Comment by abhinavdahiya** [comment]
retest this please

**Comment by coverprice** [comment]
This PR is abandoned as we are not releasing a 1.8.14 at this time.

**Pull request closed without merging**
