### PR TITLE
Bumped KVO and Tectonic versions to support upgrading from 1.8.6-tectonic.4

### PR DESCRIPTION
**Pull request by coverprice**

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
retest

**Comment by abhinavdahiya** [comment]
ok to test

**Comment by coverprice** [comment]
retest this please

**Comment by abhinavdahiya** [comment]
test upgrade from 1.8.9-tectonic.3 1.8.9-tectonic.3

**Comment by abhinavdahiya** [comment]
test upgrade from 1.8.9-tectonic.3 1.8.9-tectonic.3

**Comment by coverprice** [comment]
retest this please

**Comment by coverprice** [comment]
retest this please

**Comment by coverprice** [comment]
retest this please

**Pull request merged**
