### PR TITLE
Move sanity tests

### PR DESCRIPTION
**Pull request by squat**
This PR move the "sanity" tests to the smoke test directory, since that is what they really are. This is just a first step as we refactor the project's testing infrastructure, add integration tests, and automate the QA checklist.

cc @kans @ggreer

### CODE REVIEW

**Comment by kans** [comment]
maybe you broke the vendoring?

```k8s_test.go:11:2: cannot find package "k8s.io/client-go/kubernetes" ```

**Comment by squat** [comment]
figured it out.. it's an unfortunate combination of issues between go not letting you use vendor directories outside of a $GOPATH and Make resolving the symlink of the current directory so that it is no longer technically in a $GOPATH. the fix is to not explicitly use $TOP_DIR, just like before.

**Comment by rithujohn191** [comment]
would stuff on Jenkins need to be updated too? :thinking:

**Comment by squat** [comment]
This does update all the jenkins stuff. PTAL at the Jenkinsfile changes

**Comment by Quentin-M** [comment]
Oops it got merged while I was reading. This opens the way to re-implementing our bash scripts in Go, looks good, thanks! 👍

**Pull request merged**
