### PR TITLE
frontend: Add explanation text to restore modal

### PR DESCRIPTION
**Pull request by kyoto**
Also capitalized "P" of "progress" in header.

screenshot-1

### CODE REVIEW

**Comment by kyoto** [comment]
ok to test

**Comment by kyoto** [comment]
ok to test

**Comment by robszumski** [comment]
Small nit, but can this be black text instead of the grey help text?

**Comment by kyoto** [comment]
Thanks @robszumski. I changed it to black text and updated the screenshot.

**Comment by kyoto** [comment]
ok to test

**Pull request merged**
