### PR TITLE
bootkube/tectonic: remove cluster-config.

### PR DESCRIPTION
**Pull request by diegs**
These are not going to be used in the helium release, so temporarily
removing them. We will restore them after the release branch is cut.

### CODE REVIEW

**Comment by diegs** [comment]
retest this please

**Comment by diegs** [comment]
@cpanato test failed with some script error:

```
[tectonic-installer_PR-2376-5JJ6IWBIS2GKLE7AWJPHD4XD2Y7TMV73DY6ECHELHDC3HDTYYHCA] Running shell script
+ ./tests/jenkins-jobs/scripts/report-status-to-github.sh failure spec/aws/ca_spec.rb 81001cfc6671c94c161363a89d80a8ad0f62144c
/home/ubuntu/workspace/tectonic-installer_PR-2376-5JJ6IWBIS2GKLE7AWJPHD4XD2Y7TMV73DY6ECHELHDC3HDTYYHCA@tmp/durable-5ce62a0a/script.sh: line 2: ./tests/jenkins-jobs/scripts/report-status-to-github.sh: No such file or directory
script returned exit code 127
```

**Comment by diegs** [comment]
Adding @s-urbaniak as an FYI, this needs to go in for Helium.

**Comment by cpanato** [comment]
retest this please

**Pull request merged**
