### PR TITLE
Self-hosted etcd UI

### PR DESCRIPTION
**Pull request by ggreer**
- Hide experimental option (which is really just self-hosted etcd option)
- Unify booleans (self-hosted, external) to a single UI state var: etcd_option.
- Update toAWS & toBareMetal to correctly change UI state to tfvars.
- Update test cases & progress files to pass with new etcd UI.
- UI tests: Give better error message if missing env vars.

Here's what the new radio buttons look like:

screenshot from 2017-06-20 14-28-09

And when provision nodes is selected:

screenshot from 2017-06-20 14-38-02

For #1037.

### CODE REVIEW

**Comment by ggreer** [comment]
I assume some copy needs to be updated, but besides that it should be good.

Also important: this changes the default to self-hosted etcd.

**Comment by Quentin-M** [comment]
UI looks good to me! Thanks a lot for the change!

**Comment by robszumski** [comment]
To make it clear that we're creating vs connecting to existing, how about "Create self-hosted etcd cluster (alpha)"

My thinking is using a verb will help you grok this.

**Comment by ggreer** [comment]
So we need the default to be self-hosted on bare metal, but provisioned on AWS? With the current UI framework, our options are:

- Leave the default as self-hosted for both baremetal & AWS.
- Change the default to provisioned. Bare metal users will see no option selected.

Anything requiring "dynamic defaults" (that change based on other form values changing) means writing a new feature in the UI framework. That'd probably take Matt & I a day.

**Comment by robszumski** [comment]
@ggreer where did the bare metal requirement come from? Self-hosted etcd has not graduated to stable and should not be the default anywhere.

**Comment by ggreer** [comment]
We can't boot AWS instances for bare metal, so the only choices are external etcd & self-hosted.

**Comment by Quentin-M** [comment]
Unlike what's stated in Slack (no support for external) or in PR (no support for provisioned etcd), the bare-metal platform supports both: on controller provisioned etcd, external etcd, and self-hosted etcd.

**Comment by ggreer** [comment]
OK, all three options enabled and default is provision or use controllers, not self hosted.

Here's what it looks like now:

screenshot from 2017-06-20 17-54-41

screenshot from 2017-06-20 17-55-49

**Pull request merged**
