### PR TITLE
platforms/openstack: Don’t create console DNS on vanilla

### PR DESCRIPTION
**Pull request by lblackstone**
Only create a DNS record for the Tectonic console if
tectonic_vanilla_k8s=false.

### CODE REVIEW

**Comment by lblackstone** [comment]
Didn't realize that was a thing. :) Updated.

**Comment by s-urbaniak** [comment]
ok to test

**Comment by lblackstone** [comment]
Looking at it again, realized I had used the wrong flag for the conditionals. Should be correct now.

**Comment by s-urbaniak** [comment]
whops, agree :-D

**Comment by s-urbaniak** [comment]
ok to test

**Pull request merged**
