### PR TITLE
AWS: implement custom DNS prefixes

### PR DESCRIPTION
**Pull request by alexsomesan**
This fixes https://github.com/coreos/tectonic-installer/issues/228

@Quentin-M @s-urbaniak

### CODE REVIEW

**Comment by Quentin-M** [comment]
I am confused. How much do we need that? This was present due to the hard requirement by a customer that his CloudFormation name was specifically something (policies). We don't have CloudFormation anymore.

**Comment by alexsomesan** [comment]
I'm not very familiar with the history of this feature, but we had an issue attached to the milestone to fix it.
To me it made sense since the UI exposes it now so we have to support it to claim feature parity.

@sym3try Thoughts?

**Comment by alexsomesan** [comment]
@sym3tri ^

**Comment by sym3tri** [comment]
Having this helps achieve feature parity WRT available customizations. 

IIRC customers have specific required formats they need to use for both CF and for their DNS.

**Pull request merged**
