### PR TITLE
Parameterize github repository in Jenkinsfile

### PR DESCRIPTION
**Pull request by coverprice**
This is to support making changes to the Jenkinsfile safely from another repo, and in future from another Jenkins instance.

Of note, the .trim() line was added because the "originalCommitId" had a hidden trailing newline.

### CODE REVIEW

**Comment by coverprice** [comment]
ok to test

**Comment by cpanato** [comment]
conformance tests will not pass.

**Comment by cpanato** [comment]
retest this please

**Comment by coverprice** [comment]
@cpanato Re: your conformance test comment above: Is there a problem with conformance tests in this PR, or in general?

**Comment by cpanato** [comment]
in general

**Comment by mxinden** [comment]
ok to test

**Pull request merged**
