### PR TITLE
Azure smoke tests: align all nodes on same VM type

### PR DESCRIPTION
**Pull request by alexsomesan**
This change aims to further consolidate the smoke test behaviour.

The D1 instance type we were using for some nodes is not available in most regions. It's old and being deprecated. We should just use D2 for everything, to be on the safe side.

### CODE REVIEW

**Comment by alexsomesan** [comment]
ok to test

**Comment by alexsomesan** [comment]
ok to test

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
retest this please

**Comment by alexsomesan** [comment]
ok to test

**Comment by cpanato** [comment]
retest this please

**Pull request merged**
