### PR TITLE
modules/ignition,platforms/*: Add HTTP proxy to missing platforms

### PR DESCRIPTION
**Pull request by kalmog**
fix conflicting merge issue in #2609

### CODE REVIEW

**Comment by kalmog** [comment]
test this please

**Comment by kalmog** [comment]
@lander2k2 please take a look here - builds are failing due to  `local.tectonic_http_proxy_enabled` not being defined.

**Comment by cpanato** [comment]
retest this please. Azure only

**Comment by cpanato** [comment]
failing due:

```
Error: module.etcd.var.ign_systemd_default_env_id: local.tectonic_http_proxy_enabled: no local value of this name has been declared

Error: module.masters.var.ign_profile_env_id: local.tectonic_http_proxy_enabled: no local value of this name has been declared

Error: module.workers.var.ign_profile_env_id: local.tectonic_http_proxy_enabled: no local value of this name has been declared

Error: module.etcd.var.ign_profile_env_id: local.tectonic_http_proxy_enabled: no local value of this name has been declared

Error: module.masters.var.ign_systemd_default_env_id: local.tectonic_http_proxy_enabled: no local value of this name has been declared

Error: module.workers.var.ign_systemd_default_env_id: local.tectonic_http_proxy_enabled: no local value of this name has been declared
```

**Comment by kalmog** [comment]
test this please

**Comment by kalmog** [comment]
check is green, but was not reported back to github: https://jenkins-tectonic-installer.prod.coreos.systems/blue/organizations/jenkins/tectonic-installer/detail/PR-2714/12/pipeline

**Pull request merged**
