### PR TITLE
config.tf: Update tectonic-alm-operator to v0.3.0

### PR DESCRIPTION
**Pull request by ecordell**
This release includes subscriptions (OCS Updating) and chargeback, as well as the latest versions of Vault, Etcd, and Prometheus OCS.

### CODE REVIEW

**Comment by cpanato** [comment]
ok to test

**Comment by cpanato** [comment]
I need to take a look at what changed in the tectonic console, tests failed in that. I will do that tomorrow first thing if this is fine @ecordell

**Comment by cpanato** [comment]
@ecordell one comment:
the `tectonic-alm-operator` is in `crashloop`
```
➜ kubectl get pods -n tectonic-system
NAME                                                   READY     STATUS             RESTARTS   AGE
alertmanager-main-0                                    2/2       Running            0          5m
alertmanager-main-1                                    2/2       Running            0          5m
container-linux-update-agent-ds-t84dv                  1/1       Running            0          6m
container-linux-update-agent-ds-vcdkn                  1/1       Running            0          6m
container-linux-update-operator-57678f4cd6-9t5tz       1/1       Running            0          7m
default-http-backend-5dd46478c9-vkvqt                  1/1       Running            0          7m
etcd-operator-57584f6dfb-lsz2z                         1/1       Running            0          7m
grafana-9cc9bd94c-6x9xx                                2/2       Running            0          4m
kube-state-metrics-7df6fbd6db-qx8q9                    4/4       Running            0          4m
kube-version-operator-d4c4fd4f6-rx2x8                  1/1       Running            0          7m
node-agent-p6vwj                                       1/1       Running            0          7m
node-agent-trwls                                       1/1       Running            0          7m
node-exporter-rt2nv                                    2/2       Running            0          4m
node-exporter-tsgtq                                    2/2       Running            0          4m
prometheus-k8s-0                                       2/2       Running            0          6m
prometheus-operator-8696544d6b-97mrw                   1/1       Running            0          7m
tectonic-alm-operator-96fcff8cc-nk99b                  0/1       CrashLoopBackOff   6          7m
tectonic-channel-operator-6756c66c9-snbz9              1/1       Running            0          7m
tectonic-cluo-operator-6c8c857dcf-nrvc5                1/1       Running            0          7m
tectonic-console-7b678cc5cc-7vjtm                      1/1       Running            0          7m
tectonic-console-7b678cc5cc-b7bdp                      1/1       Running            0          7m
tectonic-identity-7484d469d7-d6qw6                     1/1       Running            0          7m
tectonic-identity-7484d469d7-s9hx2                     1/1       Running            1          7m
tectonic-ingress-controller-c44f7cb74-cdf5t            1/1       Running            0          7m
tectonic-monitoring-auth-alertmanager-d65797df-4gtlq   1/1       Running            0          5m
tectonic-monitoring-auth-grafana-654b574b48-jqdzl      1/1       Running            0          4m
tectonic-monitoring-auth-prometheus-878cd9c85-72stm    1/1       Running            0          6m
tectonic-prometheus-operator-755c6b97d9-8nzzc          1/1       Running            0          7m
tectonic-stats-emitter-7dd77c4b48-rqsjr                2/2       Running            0          7m
```

**Comment by ecordell** [comment]
@cpanato I updated the tectonic-alm-operator deployment, it should work now. There were some command changes we missed for the new x-operator based image.

**Comment by cpanato** [comment]
@ecordell thanks, I will look into

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
`tectonic-alm-operator` is not more on crashloop

**Comment by cpanato** [comment]
waiting the tests become green then we can merge it

**Pull request merged**
