### PR TITLE
docs: fixes command line errors for scaling workers ...

### PR DESCRIPTION
**Pull request by kans**
in metal/azure/openstack.

### CODE REVIEW

**Comment by Quentin-M** [comment]
ok to test

**Comment by Quentin-M** [comment]
ok to test

**Comment by Quentin-M** [comment]
ok to test

**Comment by mxinden** [comment]
@kans Could you resolve the merge conflict and rebase onto master so #1350 fixes your Jenkins issues, that you faced in build number [3](https://jenkins-tectonic-installer.prod.coreos.systems/job/tectonic-installer/job/PR-1349/3/console)?

**Comment by kans** [comment]
sure

**Pull request merged**
