### PR TITLE
monitoring: bump TPO to v1.5.0

### PR DESCRIPTION
**Pull request by brancz**
This bumps the TPO to `v1.5.0`, which includes the TPR->CRD migration for the `AppVersion` objects.

Note: this _needs to_ land in the next release, but should be low risk as the TPO's functionality didn't change in this release, just the TPR->CRD migration was implemented by bumping the vendored dependencies.

@fabxc @pst @alexsomesan @s-urbaniak 

/cc @robszumski

### CODE REVIEW

**Comment by Quentin-M** [comment]
Thank you!

Could you run 'make payload' and commit the diff? Otherwise I can add the commit myself if it's too late in Germany! 👍

**Comment by yifan-gu** [comment]
@Quentin-M Why the signature is checked in at first place?

**Comment by Quentin-M** [comment]
@yifan-gu exactly

**Comment by Quentin-M** [comment]
retest this please

**Comment by Quentin-M** [comment]
retest this please

**Comment by s-urbaniak** [comment]
ok to test

**Comment by brancz** [comment]
Tests are passing and @yifan-gu gave me a lgtm via slack. Ultimately we can only really test/QA this end to end once the new TCO version is also merged.

@Quentin-M I'd propose that you coordinate that the TCO change and this change is merged simultaneously, as merging either one of them will break for the time until the other one is merged, because the new TCO and old TPO would not work together and the new TPO and old TCO likewise.

**Comment by yifan-gu** [comment]
@brancz I can make the PR towards the `crd_migration` branch, so we can test it.

**Comment by Quentin-M** [comment]
Closing for https://github.com/coreos/tectonic-installer/pull/1738.

**Pull request closed without merging**
