### PR TITLE
Create Security Groups in AWS with custom CIDRs

### PR DESCRIPTION
**Pull request by notnamed**
This PR creates a new variable named custom_sg_cidrs. This is an optional variable. When defined, this variable replaces the default behavior of allowing inbound traffic from 0.0.0.0/0 with allowing inbound traffic from a defined list of CIDRs. To support limiting this traffic, several additional SG rules were created to allow intra-cluster communication. This solves Jira ticket https://jira.prod.coreos.systems/browse/FR-326

### CODE REVIEW

**Comment by squat** [comment]
@notnamed can you please run `terraform fmt` on the modified files? Jenkins is complaining about the static terraform tests.

**Comment by sir-rob** [comment]
@squat & @notnamed any update on this PR?

**Comment by cpanato** [comment]
@notnamed can you please rebase your PR and resolve the conflicts?  thanks!

**Comment by cpanato** [comment]
ok to test

**Comment by cpanato** [comment]
@notnamed can you please squash your commits? And I think you need to make the changes in the Govcloud as well

cc @squat

**Comment by sym3tri** [comment]
Going to close this out since it's stale. We're considering this for the converged platform.

**Pull request closed without merging**
