### PR TITLE
platforms/metal: add support for external/self-hosted etcd clusters

### PR DESCRIPTION
**Pull request by Quentin-M**

### CODE REVIEW

**Comment by Quentin-M** [comment]
- Tested 3x with self-hosted etcd
- Tested 1x with an external etcd cluster

**Comment by dghubble** [comment]
Simply deleting the etcd pod in a single master setup (most common) seems to not reconcile and create a new pod, which causes a cluster outage. If others can reproduce, this feature is less resilient than the default on-host setup and other control plane pods, which can recover from pod failures.

Please ensure the new self-hosted etcd feature has all the appropriate warnings. Self-hosted etcd is listed as beta by upstream, so that should be the maximum stability category claimed by the Tectonic Installer use of it.

cc @sym3tri @mfburnett @Quentin-M @s-urbaniak

**Comment by Quentin-M** [comment]
The self-hosted etcd pod is checkpointed and is therefore able to recover in single master setups.

**Comment by dghubble** [comment]
I'm aware that's the desired behavior. I've reproduced twice with 10-15 minutes for checkpointing and recovery, even after a clean reboot. Are you able to reproduce?

**Comment by Quentin-M** [comment]
```
core@node1 ~ $ ls /etc/kubernetes/inactive-manifests/kube-system-kube-etcd-0000.json
/etc/kubernetes/inactive-manifests/kube-system-kube-etcd-0000.json
core@node1 ~ $ sudo reboot

core@node1 ~ $ uptime
 18:10:53 up 1 min,  1 user,  load average: 8.27, 2.49, 0.87

core@node1 ~ $ kubectl get pods -n=kube-system
NAME                                       READY     STATUS    RESTARTS   AGE
etcd-operator-2011959399-qpjxp             1/1       Running   2          20m
heapster-1767220581-0dssc                  2/2       Running   2          3m
kube-apiserver-sfjxc                       1/1       Running   9          20m
kube-controller-manager-2144231279-09n7g   1/1       Running   3          20m
kube-controller-manager-2144231279-8qtbt   1/1       Running   1          20m
kube-dns-2431531914-z3090                  3/3       Running   3          20m
kube-etcd-0000                             1/1       Running   1          8m
kube-etcd-network-checkpointer-htksz       1/1       Running   1          20m
kube-flannel-76c5p                         2/2       Running   5          16m
kube-flannel-qspjs                         2/2       Running   2          20m
kube-flannel-x0c2t                         2/2       Running   1          14m
kube-proxy-bnmfh                           1/1       Running   0          16m
kube-proxy-sj3t3                           1/1       Running   0          14m
kube-proxy-x440d                           1/1       Running   1          20m
kube-scheduler-170664151-1f558             1/1       Running   2          20m
kube-scheduler-170664151-x9wk4             1/1       Running   2          20m
pod-checkpointer-3hv42                     1/1       Running   1          20m
pod-checkpointer-3hv42-node1.example.com   1/1       Running   1          15m

core@node1 ~ $ kubectl get nodes --show-labels
NAME                STATUS    AGE       VERSION           LABELS
node1.example.com   Ready     20m       v1.6.2+coreos.0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,container-linux-update.v1.coreos.com/group=stable,container-linux-update.v1.coreos.com/id=coreos,container-linux-update.v1.coreos.com/version=1353.7.0,kubernetes.io/hostname=node1.example.com,node-role.kubernetes.io/master=
node2.example.com   Ready     16m       v1.6.2+coreos.0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,container-linux-update.v1.coreos.com/group=stable,container-linux-update.v1.coreos.com/id=coreos,container-linux-update.v1.coreos.com/version=1353.7.0,kubernetes.io/hostname=node2.example.com,node-role.kubernetes.io/node=
node3.example.com   Ready     14m       v1.6.2+coreos.0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,container-linux-update.v1.coreos.com/group=stable,container-linux-update.v1.coreos.com/id=coreos,container-linux-update.v1.coreos.com/version=1353.7.0,kubernetes.io/hostname=node3.example.com,node-role.kubernetes.io/node=
```

**Comment by dghubble** [comment]
That's not what I reported about. Reboots seem ok. Try deleting `kubectl delete pod kube-etcd-0000`.

**Comment by Quentin-M** [comment]
You delete the only etcd pod from the API Server. The checkpointer figures out that this pod is not to be checkpointed anymore and removes the local copy - without bringing it back up. etcd-operator tries to bring back an etcd-pod up, but there is no working API server anymore since you explicitly wiped the database instance set - so it can't.

**Comment by aaronlevy** [comment]
Right, the checkpointer looks and says "I was able to contact an api-server, and looks like this pod is no longer scheduled -- it should be removed". Essentially GC (otherwise a checkpoint would exist forever -- even if the parent has successfully moved elsewhere).

We might be able to do something like add a mode for "don't remove even if unscheduled" -- but that could get weird (when *should* it be removed)?

**Comment by dghubble** [comment]
Thanks for reproducing.

In on-host setups, one could simply `systemctl restart etcd` if a peer failed and data was still present. Looking forward to when the operator or recovery can handle this.

**Comment by aaronlevy** [comment]
@dghubble can you open a new issue for this (bootkube probably, as it likely would be a checkpointer change)

**Pull request merged**
