### PR TITLE
platforms/aws: fix disabling private endpoints

### PR DESCRIPTION
**Pull request by squat**
This PR fixes a regression in the AWS platform of the installer that prevented clusters that disabled private endpoints from being created. This is not a cherry-pick, since the variable names changed in master since 179 was cut, but a release-branch equivalent of https://github.com/coreos/tectonic-installer/pull/2392.

I tested this manually and a the cluster successfully came up without private endpoints.

cc @s-urbaniak @soggiest @sudhaponnaganti

### CODE REVIEW

**Comment by s-urbaniak** [comment]
ok to test

**Comment by kalmog** [comment]
LGTM

**Comment by cpanato** [comment]
we need to update the jenkinsfile for 1.7.9 branch and as well the rspec folder.

**Comment by squat** [comment]
@cpanato every time I run tests Jenkins says there are no build steps. Can you help debug?

**Comment by cpanato** [comment]
tests failed now due the dns issue, need to update this branch 1.7.9 to get the changes in the tests

**Comment by kalmog** [comment]
LGTM +1

**Comment by squat** [comment]
Thanks @kalmog. All tests passed. Status is not being updated by Jenkins. Merging.

**Pull request merged**
