### PR TITLE
{Jenkinsfile,tests/smoke/aws/smoke.sh}: Fail stage upon assume-role err.

### PR DESCRIPTION
**Pull request by Quentin-M**
* Use bash envs for `Smoke Test` steps, like in `Build & Test`
* Thus, this allows us to use export / source to get the credentials, which will trigger stage failure
* Restore -x

### CODE REVIEW

**Comment by ggreer** [comment]
Looks like credentials aren't being exported correctly, causing terraform plan to fail.

**Comment by squat** [comment]
hmm plan is working for all of the steps. It's the apply that is failing. However, more troubling is that there are a lot of `Creation complete`s in the make apply. So the credentials are valid.

**Comment by ggreer** [comment]
Oh. It's almost as if `TECTONIC_INSTALLER_ROLE` doesn't have all the necessary roles. :thinking:

**Comment by squat** [comment]
unless the privilege boundary *just* expanded they should be valid :sweat:

**Comment by Quentin-M** [comment]
```
* aws_instance.etcd_node.1: UnauthorizedOperation: You are not authorized to perform this operation.
    status code: 403, request id: 5d2de736-3c24-4e47-af72-348135c75a8c
* module.etcd.aws_instance.etcd_node[2]: 1 error(s) occurred:
* aws_s3_bucket.tectonic: "aaws-pr-1023-4012345678901234-27d29fcd4ac41d0ec3fca4aadd4583b3": AccessDenied: Access Denied
    status code: 403, request id: 9BD3D70AC8E8E456, host id: vzTd75Kg6lID+/zeUT/az7jaYLXQwAfPZJfYxa9ytzXHAjKcBXQWLoSyL2Q13lbB5MQDYjtQ7dM=
```

**Comment by Quentin-M** [comment]
I fixed the AWS IAM policy, which became invalid on May 22. All set 👍.

**Comment by Quentin-M** [comment]
ok to test

**Comment by squat** [comment]
ok to test

**Comment by squat** [comment]
Reset policy with set-role tool and retested. Looks good. Merging.

**Pull request merged**
