### PR TITLE
fix/azure/nsg: Fix NSG rules

### PR DESCRIPTION
**Pull request by justaugustus**
#991 Introduced a few NSG priority errors.
This PR fixes them.

### CODE REVIEW

**Comment by justaugustus** [comment]
@s-urbaniak @alexsomesan take a look when you have a chance.

**Comment by s-urbaniak** [comment]
@justaugustus thanks a ton! I was hitting this very hard today ;-)

**Comment by justaugustus** [comment]
@s-urbaniak yeah, was something that popped up from one of my downstream branches. Sorry about that!

**Comment by s-urbaniak** [comment]
@justaugustus I cherry-picked this PR but it doesn't seem to work still:
```
core@tectonic-master-000000 /opt/tectonic $ grep etcd manifests/kube-apiserver.yaml 
        - --etcd-servers=http://52.168.79.147:2379
        # no etcd-ca.crt given
        # no etcd-client.crt given
        # no etcd-client.key given
        - --etcd-quorum-read=true
        - --storage-backend=etcd3
core@tectonic-master-000000 /opt/tectonic $ curl http://52.168.79.147:2379/version
<hanging>
```

Also, can you include the removal of `tectonic_azure_enable_ssh_external`, it seems to be unused.

Finally `tectonic_use_jumpbox` seems to be defunct, the variable is unused.

**Comment by Quentin-M** [comment]
ok to test

**Comment by justaugustus** [comment]
@s-urbaniak or @alexsomesan I've tested this. Should be good to go now.

**Comment by s-urbaniak** [comment]
@justaugustus I gave this PR a try this morning but am unfortunately still out of luck:
```
core@tectonic-master-000000 ~ $ ssh core@40.114.47.125
ssh: connect to host 40.114.47.125 port 22: Connection timed out

core@tectonic-master-000000 ~ $ grep etc /opt/tectonic/manifests/kube-apiserver.yaml 
        - --etcd-servers=http://40.114.47.125:2379
```

**Comment by s-urbaniak** [comment]
After waiting a while it seems that the http based communication seems to work towards etcd machines, since I can curl/kubectl and the cluster comes up:
```
$ kubectl get po --all-namespaces 
NAMESPACE         NAME                                              READY     STATUS    RESTARTS   AGE
kube-system       heapster-1767220581-5vq7k                         2/2       Running   0          24m
kube-system       kube-apiserver-3cpkb                              1/1       Running   0          26m
...
```

I have the following ssh settings which should relax ssh connectivity:
```
tectonic_azure_ssh_network_external = "*"
tectonic_azure_ssh_network_internal = "*"
```

**Comment by s-urbaniak** [comment]
@justaugustus so I think the only thing left to fix is ssh connectivity.

**Comment by s-urbaniak** [comment]
I think we can address ssh connectivity separately. At least this gives a functioning cluster. Thanks a lot!

**Pull request merged**
