### PR TITLE
frontend: Adds helper text for etcd instances

### PR DESCRIPTION
**Pull request by amrutac**
screen shot 2017-06-20 at 2 42 10 pm

### CODE REVIEW

**Comment by Quentin-M** [comment]
Can you run `terraform fmt .`? I believe you'd have to regenerate the docs as well.

**Comment by amrutac** [comment]
@Quentin-M: How do I regenerate the documentation?

**Comment by Quentin-M** [comment]
@amrutac It should be: `make docs && make examples`

**Comment by amrutac** [comment]
ok to test

**Comment by ggreer** [comment]
Tests failed because of AWS resource limits and some weird terraform timeout/flaking. Your changes shouldn't affect those.

**Comment by amrutac** [comment]
Yeah, should I wait till the tests are green or just merge this?

**Comment by squat** [comment]
On principle we should just wait, @amrutac. @bison is restoring the test aws account as we speak so we can set tests back up soon and re-run this PR.

**Comment by amrutac** [comment]
Will do.

**Comment by Quentin-M** [comment]
We should probably merge tho, every tests that could be broken by it already passed (docs, fmt, examples).

**Pull request merged**
