### PR TITLE
modules/bootkube: move kenc to experimental dir

### PR DESCRIPTION
**Pull request by squat**
Fixes: #824

### CODE REVIEW

**Comment by sym3tri** [comment]
Do you need to modify any of the bash scripts as well?
https://github.com/coreos/tectonic-installer/blob/master/modules/tectonic/resources/tectonic.sh

Please wait for CI to pass on this one

**Comment by squat** [comment]
@sym3tri no need. all the bootkube manifests are handled by bootkube.sh [0], which runs in the `/opt/tectonic/` directory.

[0] https://github.com/coreos/tectonic-installer/blob/master/modules/bootkube/resources/bootkube.sh#L10

**Comment by aaronlevy** [comment]
lgtm

**Comment by sym3tri** [comment]
rebase & re-run tests please

**Comment by squat** [comment]
failing due to resource limits :(

**Pull request merged**
