### PR TITLE
modules/vmware: add missing ignition config for HTTP proxy

### PR DESCRIPTION
**Pull request by kalmog**

### CODE REVIEW

**Comment by kalmog** [comment]
ok to test

**Comment by lander2k2** [comment]
LGTM

**Comment by kalmog** [comment]
retest this please

**Comment by kalmog** [comment]
ok to test

**Comment by cpanato** [comment]
retest this please

**Comment by kalmog** [comment]
previous run for azure self hosted etcds succeeded: https://jenkins-tectonic-installer.prod.coreos.systems/blue/rest/organizations/jenkins/pipelines/tectonic-installer/branches/PR-2767/runs/16/nodes/108/log/?start=0

so I'm merging this PR

**Pull request merged**
