### PR TITLE
config.tf: Bump kvo to v1.7.9-kvo.6 to include the console v2.3.5 bump.

### PR DESCRIPTION
**Pull request by yifan-gu**

### CODE REVIEW

**Comment by yifan-gu** [comment]
test upgrade from 1.7.5-tectonic.1 1.7.5-tectonic.1

**Comment by yifan-gu** [comment]
test upgrade from 1.7.5-tectonic.1 1.7.5-tectonic.1

**Comment by yifan-gu** [comment]
test upgrade from 1.7.5-tectonic.1 1.7.5-tectonic.1

**Comment by yifan-gu** [comment]
retest this please

**Comment by yifan-gu** [comment]
retest this please

**Comment by yifan-gu** [comment]
retest this please

**Comment by yifan-gu** [comment]
retest this please

**Comment by squat** [comment]
@yifan-gu we have to cherry pick some CI changes into this branch for tests to pass

**Comment by squat** [comment]
AWS tests should pass now that #2397 merged.

**Comment by squat** [comment]
retest this please

**Comment by sudhaponnaganti** [comment]
@yifan-gu - once tests are done can you merge this. I will make RC 1 build

**Comment by yifan-gu** [comment]
Rebased the branch.

**Comment by yifan-gu** [comment]
retest this please

**Comment by yifan-gu** [comment]
Not sure why the status wasn't reported back, but the `basic-tests` is passing https://jenkins-tectonic-installer.prod.coreos.systems/job/tectonic-installer/view/change-requests/job/PR-2399/11/

So I am going to merge it.

**Pull request merged**
