### PR TITLE
fix external etcd cluster support.

### PR DESCRIPTION
**Pull request by coresolve**
With this change:
If you set `tectonic_etcd_tls_enabled`
- We will use the `https` scheme.
- The default remains true

If you set `tectonic_etcd_servers`
- We will assume we are not generating certs for the etcd cluster
- Optionally, you can provide `tectonic_etcd_ca_cert_path` if needed.

### CODE REVIEW

**Comment by squat** [comment]
ok to test

**Comment by squat** [comment]
ok to test

**Comment by coresolve** [comment]
Got it will address

**Comment by coresolve** [comment]
ok to test

**Comment by coresolve** [comment]
Looks like this flaked on the `azure_private_external` test. Thoughts @squat?

**Comment by coresolve** [comment]
ok to test

**Pull request merged**
