### PR TITLE
steps: rename steps/assets to steps/assets/AWS

### PR DESCRIPTION
**Pull request by squeed**
This is a minor step in splitting the "assets" step in to AWS and generic parts. All this PR does is move the files - I've filed it now in an attempt to prevent hellish merges later.

### CODE REVIEW

**Comment by squeed** [comment]
Rebased; no more merge conflicts.

**Comment by squat** [comment]
ok to test

**Comment by abhinavdahiya** [comment]
Any reason why it is `AWS` not `aws` ? This value is going to be plumbed through cluster-config to operators. As far as I know they expect `aws`. 

//cc: @yifan-gu @aaronlevy

**Comment by squeed** [comment]
It's AWS because that's the platform name in `examples/tectonic.aws.yaml`. Should probably be put to lowercase for sanity's sake.

**Comment by abhinavdahiya** [comment]
+1 for lowercase `aws`

**Comment by squeed** [comment]
Closing this; have a slightly different approach.

**Pull request closed without merging**
