### PR TITLE
openstack: Fix non-self-hosted etcd security groups

### PR DESCRIPTION
**Pull request by coreypobrien**
Security groups for controller nodes were broken when experimental was false
because they attempted to reference the self-hosted etcd secrurity group
which doesn't exist in that configuration.

This change consolidates all security groups into their own openstack module
to ensure that shared groups are only created once per plan. Both the self-
hosted and non-self-hosted etcd security groups need to be created so that
references to them resolve even if they ultimately aren't used due to
the conditional logic from tectonic_experimental.

### CODE REVIEW

**Comment by s-urbaniak** [comment]
ok to test

**Comment by s-urbaniak** [comment]
@coreypobrien CI unfortunately complains with:
```
misformatted files (run 'terraform fmt .' to fix): platforms/openstack/nova/main.tf
```

**Comment by s-urbaniak** [comment]
and there is a conflict because I just merged another OpenStack PR ;-)

**Comment by s-urbaniak** [comment]
CI failure seems unrelated:

```
Error applying plan:

1 error(s) occurred:

* module.etcd.aws_instance.etcd_node[0]: 1 error(s) occurred:

* aws_instance.etcd_node.0: InvalidInstanceID.NotFound: The instance ID 'i-0a8ac7efc18e0ca58' does not exist
	status code: 400, request id: 687476cd-bd34-43b9-a764-f835bf264e6a

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
make: *** [apply] Error 1
```

I will restart it.

**Comment by s-urbaniak** [comment]
retest this please

**Comment by Quentin-M** [comment]
ok to test

**Comment by lblackstone** [comment]
@s-urbaniak ✅  :)

**Pull request merged**
