### PR TITLE
1.8.7: backport testing framework from master

### PR DESCRIPTION
**Pull request by colhom**
\cc @coverprice @mxinden

### CODE REVIEW

**Comment by coverprice** [comment]
ok to test

**Comment by coverprice** [comment]
@mxinden I'll let @colhom write the PR overview, but I will add that many of his changes were made to support being able to develop changes safely in a separate Jenkins sandbox instance, since a lot of the code was hard-wired to assume it was running on the Prod Jenkins instance.

I understand that usually changes are made on master and cherry-picked into other branches as necessary. However these changes were done on 1.8.7 directly because our sprint goal is to show the test results for the Li release (since that is going out first), and we are supposed to demo this on Friday. Neither of us feel this situation is ideal, but I believe this is a "one-off" and hopefully won't happen again!

**Comment by colhom** [comment]
> This is in need of some serious rebasing and explanation/justification of
the changes.

Normally I would agree, but given the state of test framework as-is I'm
inclined to suggest we just shoot to make the tests green for 1.8.7. I'd
rather not waste time on incremental improvement rituals, as it's pretty
evident that Jenkinsfile and test/ folder consist almost entirely of
spaghetti and bit rot and need to be gutted ASAP. (If your tests are less
good than your application, you have a quality deficit. I'm not sure our
tests could be worse tbh)

**Comment by coverprice** [comment]
I think it's important to follow procedure, and although our demo is urgent, merging is not, so let's close this PR and we'll try again in a more harmonious way.

**Pull request closed without merging**
