### PR TITLE
modules/tectonic/resources/manifests/updater: Change all AppVersion TPRs to CRDs.

### PR DESCRIPTION
**Pull request by rithujohn191**

### CODE REVIEW

**Comment by rithujohn191** [comment]
Smoke test will only pass after the tco bump

**Comment by Quentin-M** [comment]
This is blocked by the need of a TCO bump.

**Comment by yifan-gu** [comment]
LGTM, I will merge it into the branch.

**Comment by dghubble** [comment]
Spinning up a new cluster, I find the tectonic.service gets blocked waiting for TPRs [here](https://github.com/coreos/tectonic-installer/blob/master/modules/tectonic/resources/tectonic.sh#L46)

```
Aug 21 22:07:22 node1.example.com bash[2508]: [ 1149.611312] hyperkube[5]: Error from server (NotFound): thirdpartyresources.extensions "channel-operator-config.coreos.com" not found
Aug 21 22:07:22 node1.example.com bash[2508]: [ 1149.614040] hyperkube[5]: TPR channel-operator-config.coreos.com not available yet, retrying in 5 seconds (102)
```

**Comment by squat** [comment]
clusters currently fail to boot because this TPR kind was not ported: https://github.com/coreos/tectonic-installer/blob/master/modules/tectonic/resources/manifests/updater/tectonic-channel-operator-kind.yaml

**Comment by Quentin-M** [comment]
maybe @yifan-gu will do it in his PR?

**Comment by dghubble** [comment]
I'm working on a fix.

**Comment by Quentin-M** [comment]
Actually ... https://github.com/coreos/tectonic-installer/commit/70f90d525b1e9165ff84c06ba152d8adcbe0d32b

**Comment by squat** [comment]
One of the operators is still expecting TPRs instead of CRDs

**Comment by dghubble** [comment]
Which? PR #1737 just addressed the type and name change.

**Comment by squat** [comment]
@dghubble it's all good. I was saying tectonic.service was still operating on TPRs rather than CRDs. Your PR is the right fix. :tada:

**Pull request merged**
