### PR TITLE
Bump tectonic-alm-operator to 0.2.1

### PR DESCRIPTION
**Pull request by ecordell**

### CODE REVIEW

**Comment by yifan-gu** [comment]
Actually this should wait for https://github.com/coreos/tectonic-installer/pull/2409 right @ecordell

**Comment by yifan-gu** [comment]
test upgrade from 1.7.9-tectonic.1 1.7.9-tectonic.1

**Comment by sudhaponnaganti** [comment]
@ecordell - Can you resolve this failure?

**Comment by ecordell** [comment]
I rebased, but #2409 probably needs to go in first.

**Comment by cpanato** [comment]
@ecordell  can you please rebase and resolve the conflict? thanks!

**Comment by ecordell** [comment]
Looks like 0.2.1 is already  in master, closing this

**Pull request closed without merging**
