### PR TITLE
GitHub issue template

### PR DESCRIPTION
**Pull request by everett-toews**
Similar to the [kubeadm issue template](https://github.com/kubernetes/kubeadm/blob/master/.github/ISSUE_TEMPLATE.md).

### CODE REVIEW

**Comment by s-urbaniak** [comment]
That is a nice template, thanks a lot for the contribution!

@alexsomesan @Quentin-M WDYT in respect to the terraform side of things?

/cc @sym3tri

**Comment by s-urbaniak** [comment]
That is a nice template, thanks a lot for the contribution!

@alexsomesan @Quentin-M WDYT in respect to the terraform side of things?

/cc @sym3tri

**Comment by alexsomesan** [comment]
Generally looks good to me.

**Comment by everett-toews** [comment]
@s-urbaniak Oh right, Terraform is completely vendored in at https://github.com/coreos/tectonic-installer/tree/master/installer/vendor/github.com/hashicorp/terraform

The [release](https://github.com/coreos/tectonic-installer/releases) or commit hash of Tectonic will tell you what "version" of Terraform is being used.

I'm happy to remove it from the Versions section.

**Comment by Quentin-M** [comment]
Thanks for your contribution!

> Oh right, Terraform is completely vendored in at https://github.com/coreos/tectonic-installer/tree/master/installer/vendor/github.com/hashicorp/terraform
>
> The release or commit hash of Tectonic will tell you what "version" of Terraform is being used.

Not until we actually use Terraform as a library and hijack the binary Terraform calls when it reaches its providers/provisioners. Right now, the installer is shelling-out using whatever Terraform we can find on the host (next to the installer, cwd, path).

**Pull request merged**
