### PR TITLE
operators: Install the tectonic-alm-operator under TVO management

### PR DESCRIPTION
**Pull request by jakedt**
I haven't tested this because I do not know how.

### CODE REVIEW

**Comment by mxinden** [comment]
ok to test

**Comment by mxinden** [comment]
ok to test

Retriggering tests to include the console test fix in https://github.com/coreos/tectonic-installer/pull/2514. Rebase should not be needed, as we merge the changes into the target branch before testing. If they still fail, please rebase the PR onto current `1.8.4` branch.

**Comment by jakedt** [comment]
rebased

**Comment by squat** [comment]
all the specs are failing te same way at the console integration tests:
```
1) aws-network-canal Interact with tectonic console can login in the tectonic console
     Failure/Error: expect(displayed?(USERNAME_INPUT)).to be_truthy

       expected: truthy value
            got: nil
     ...

  2) aws-network-canal Interact with tectonic console fail to login with wrong credentials
     Failure/Error: expect(displayed?(USERNAME_INPUT)).to be_truthy

       expected: truthy value
            got: nil
```

**Comment by squat** [comment]
retest this please

**Comment by squat** [comment]
bringing up a cluster manually to test

**Comment by squat** [comment]
ok to test

**Comment by cpanato** [comment]
@squat this is because console made some changes in the elements we use to make some checks, I fixed that here: https://github.com/coreos/tectonic-installer/pull/2514

**Comment by sudhaponnaganti** [comment]
looks like #2514 is done. can this be restarted?

**Comment by cpanato** [comment]
I will restart soon

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
retest this please

**Comment by Quentin-M** [comment]
This should not have been merged, it is not in master (https://github.com/coreos/tectonic-installer/pull/2409).

**Pull request merged**
