### PR TITLE
tests/ci: add grafiti trigger as a jenkins code

### PR DESCRIPTION
**Pull request by cpanato**
as part of INST-84

### CODE REVIEW

**Comment by cpanato** [comment]
then we will need to setup the seed jobs for grafiti as well. if you agree, I will close this

**Comment by mxinden** [comment]
@cpanato Agreed. Let me know if you want me to do this.

**Comment by cpanato** [comment]
closing

**Comment by cpanato** [comment]
open here: https://github.com/coreos/grafiti/pull/119

**Pull request closed without merging**
