### PR TITLE
*: bump Tectonic Monitoring to 1.9.4

### PR DESCRIPTION
**Pull request by ant31**
Bump prometheus to 1.9.4  (fix upgrade)

### CODE REVIEW

**Comment by mxinden** [comment]
ok to test

**Comment by cpanato** [comment]
govcloud should fail.

**Comment by coverprice** [comment]
retest this please

**Comment by coverprice** [comment]
AWS VPC was the only failure in the last test run, but it passed in this run, so it's just this test being flaky again. So I'm going to merge.

**Pull request merged**
