### PR TITLE
platforms: Standardize flannel-vxlan references

### PR DESCRIPTION
**Pull request by lblackstone**
Some earlier refactoring caused mismatched references between
flannel_vxlan and flannel-vxlan. Change all references to flannel_vxlan.

### CODE REVIEW

**Comment by lblackstone** [comment]
@squat This is currently breaking the OpenStack plan. If this change is too broad, I can limit it to fixing the broken dependency for OpenStack.

**Comment by squat** [comment]
@lblackstone can we actually do the opposite and use `_` rather than `-`? We made a decision several months ago to standardize around snake case.
cc @s-urbaniak

**Comment by lblackstone** [comment]
@coreos/team-installer Bump. Still breaking the OpenStack plan. I can limit scope to OpenStack plan if needed to get this merged.

**Comment by squat** [comment]
ok to test

**Comment by lblackstone** [comment]
@squat Did CI testing complete? From here it looks like tests have been running for a couple hours.

**Comment by s-urbaniak** [comment]
ok to test

**Comment by s-urbaniak** [comment]
@lblackstone we are seeing flakes in CI, I rekicked it. Please hang on, once green, we'll merge.

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
Saw some flaky in bare metal. I will retrigger this PR. 🐻  with me

**Comment by lblackstone** [comment]
Rebased due to conflicts with 1.8.2 changeset

**Comment by lblackstone** [comment]
@s-urbaniak @cpanato Could you give this another peek?

**Pull request merged**
