### PR TITLE
tests: Transition AWS plan to RSpec

### PR DESCRIPTION
**Pull request by mxinden**
This commit transitions all AWS plan smoke tests to RSpec. In addition
it adds a make target so developers can easily run the RSpec tests
locally inside a Docker container.

### CODE REVIEW

**Comment by mxinden** [comment]
TODO: Add installer-env to dependencies

**Comment by cpanato** [comment]
@mxinden can you please rebase?

**Comment by mxinden** [comment]
@cpanato Done. Could you have a second look?

**Comment by mxinden** [comment]
@cpanato failed bare metal test is not related. Ready to merge?

**Pull request merged**
