### PR TITLE
Fix undefined variables in upload-payload/assets.tf.

### PR DESCRIPTION
**Pull request by yifan-gu**
Also plans to add a check in jenkins job for each PR so 'make payload'
won't get broken.

### CODE REVIEW

**Comment by yifan-gu** [comment]
Here https://github.com/yifan-gu/tectonic-installer/blob/23fc5aeb7ad1474268af80708507c92d7356e5e9/modules/update-payload/assets.tf#L3

It's used by the [cluo manifest](https://github.com/coreos/tectonic-installer/blob/master/modules/tectonic/resources/manifests/updater/operators/container-linux-update-operator.yaml#L27)

**Comment by dghubble** [comment]
What is that line doing in the CLUO manifest? cc @colhom

**Comment by yifan-gu** [comment]
Working on making the verification of `make payload` as part of the CI, so it will be more clear. I can either create a new PR or add commits to this one.

**Comment by yifan-gu** [comment]
@dghubble 
```
@@ -31,7 +31,9 @@
               {
                 "command": [
                   "/bin/update-operator",
-                  "--manage-agent=true"
+                  "--manage-agent=true",
+                  "-agent-image-repo",
+                  "quay.io/coreos/container-linux-update-operator"
                 ],
```

**Comment by dghubble** [comment]
Hm, I suppose its needed for now for the image replacement Colin is doing. It'll be removed next release when that flag is removed. A higher level operator (take to internal chat) will take on creating these manifests and if you need to edit the images it deploys, better ask for that feature soon @colhom

**Pull request merged**
