### PR TITLE
Remove platforms - azure/gcp/govcloud/vmware/openstack

### PR DESCRIPTION
**Pull request by cpanato**
Cleaning master by removing `azure`, `govcloud`, `metal`, `gcp`, `openstack` and `vmware`.

Those platforms will be readded, when we advance in the new installer flow. For now we are focus on `AWS`.

### CODE REVIEW

**Comment by cpanato** [comment]
@squat it uses the variables.bzl i changed that only. let me know if this is not good

**Comment by enxebre** [comment]
as we are not supporting track-1 in this branch anymore we can remove bootkube module, rename bootkube-ut2 to bootkube and update the references in the steps folder now.

**Comment by enxebre** [comment]
- can we also remove modules/openstack?
- Also I'd be in favour of removing non platform specific but unused modules e.g modules/bootstrap-ssh, dns/azure, dns/gcp wdyt?
- In the root BUILD.bazel there's glob pointing to "platforms" folder that should be removed now
- Also modules/ignition can be cleanup now, but let's do that in a different PR

**Comment by sym3tri** [comment]
@squat I agree with @enxebre

**Comment by bluecmd** [comment]
FYI, this broke a link on https://coreos.com/tectonic/docs/latest/install/vmware/vmware-terraform.html
> Edit the parameters with details of the VMware infrastructure. View all of the VMware specific options and the common Tectonic variables.

**Pull request merged**
