### PR TITLE
frontend/tests: More Nightwatch test improvements

### PR DESCRIPTION
**Pull request by kyoto**
Stop using the .progress input file (was only used for one value).

Add a few more checks and minor clean ups.

### CODE REVIEW

**Comment by kyoto** [comment]
ok to test

**Comment by kyoto** [comment]
ok to test

**Comment by kyoto** [comment]
ok to test

**Comment by kyoto** [comment]
ok to test

**Comment by kyoto** [comment]
ok to test

**Comment by cpanato** [comment]
The tests for UI passed. The test failed in one AWS step. not related to these changes.

**Comment by cpanato** [comment]
@kyoto can you rebase this PR please?

**Comment by kyoto** [comment]
@cpanato Rebased

**Comment by cpanato** [comment]
Since it was approved before and we just rebased I will approve since is also LGTM and merge it.
all tests are green

**Pull request merged**
