### PR TITLE
config.tf: Bump kvo to v1.7.9-kvo.5

### PR DESCRIPTION
**Pull request by yifan-gu**
This contains the new console (v2.3.4)

### CODE REVIEW

**Comment by s-urbaniak** [comment]
ok to test

**Comment by alexsomesan** [comment]
retest this please

**Comment by yifan-gu** [comment]
retest this please

**Comment by squat** [comment]
Everything passes but azure private. @cpanato, is that expected?

**Comment by cpanato** [comment]
@squat @yifan-gu we can save merge this, the build number 5 was green. but we had an issue to report the status back to github

**Comment by squat** [comment]
Thanks, @cpanato. Merging.

**Comment by squat** [comment]
@yifan-gu this needs to be cherry picked into 179, right?

**Comment by yifan-gu** [comment]
@squat I'ts already in, I created the PR on 179 branch first.

**Pull request merged**
