### PR TITLE
Add govcloud support

### PR DESCRIPTION
**Pull request by enxebre**
This introduces support for aws govcloud:
- Duplication has been generally chosen over abstraction to keep it as simple as possible and being non intrusive with conventional aws platform for now. 
- As a follow up, both internal aws and govcloud could use the same bastion infrastructure created here contrib/govcloud
- Jenkins credentials need to be setup

### CODE REVIEW

**Comment by enxebre** [comment]
ok to test

**Comment by enxebre** [comment]
ping @alexsomesan @squat @cpanato

**Comment by cpanato** [comment]
sorry for the delay @enxebre  I will try to work on that today or tomorrow morning. my bad

**Comment by enxebre** [comment]
Closing and creating against master first https://github.com/coreos/tectonic-installer/pull/2608

**Pull request closed without merging**
