### PR TITLE
platforms/vmware: make license and pull secret optional

### PR DESCRIPTION
**Pull request by squat**
fixes: #1111

### CODE REVIEW

**Comment by alekssaul** [comment]
LGTM

**Comment by alekssaul** [comment]
LGTM
Tested against VMware stack with:
- `tectonic_vanilla_k8s = true`
```
kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE       IP             NODE
kube-system   etcd-operator-580334893-6cjnb              1/1       Running   1          7m        10.2.2.6       master0
kube-system   kube-apiserver-469jf                       1/1       Running   0          7m        192.168.2.61   master0
kube-system   kube-controller-manager-2248957630-m5wcl   1/1       Running   0          7m        10.2.2.5       master0
kube-system   kube-controller-manager-2248957630-m9l9h   1/1       Running   0          7m        10.2.2.7       master0
kube-system   kube-dns-2431531914-ns907                  3/3       Running   0          7m        10.2.2.2       master0
kube-system   kube-etcd-0000                             1/1       Running   0          4m        192.168.2.61   master0
kube-system   kube-etcd-network-checkpointer-kqkbk       1/1       Running   0          7m        192.168.2.61   master0
kube-system   kube-flannel-ks361                         2/2       Running   1          7m        192.168.2.71   worker0
kube-system   kube-flannel-n0qch                         2/2       Running   1          7m        192.168.2.72   worker1
kube-system   kube-flannel-xlrnt                         2/2       Running   0          7m        192.168.2.61   master0
kube-system   kube-proxy-n4bg3                           1/1       Running   0          7m        192.168.2.72   worker1
kube-system   kube-proxy-v7295                           1/1       Running   0          7m        192.168.2.71   worker0
kube-system   kube-proxy-wtk75                           1/1       Running   0          7m        192.168.2.61   master0
kube-system   kube-scheduler-1310662694-2d1fj            1/1       Running   0          7m        10.2.2.4       master0
kube-system   kube-scheduler-1310662694-f3qq0            1/1       Running   0          7m        10.2.2.3       master0
kube-system   pod-checkpointer-kzfhv                     1/1       Running   0          7m        192.168.2.61   master0
kube-system   pod-checkpointer-kzfhv-master0             1/1       Running   0          7m        192.168.2.61   master0
```
- `tectonic_vanilla_k8s = false`
```
kubectl get pods --all-namespaces -o wide
NAMESPACE         NAME                                              READY     STATUS    RESTARTS   AGE       IP             NODE
kube-system       etcd-operator-580334893-nw1m7                     1/1       Running   1          6m        10.2.1.2       master0
kube-system       heapster-1767220581-wc278                         2/2       Running   0          1m        10.2.0.10      worker0
kube-system       kube-apiserver-2xvln                              1/1       Running   0          6m        192.168.2.61   master0
kube-system       kube-controller-manager-2248957630-dn0qs          1/1       Running   0          6m        10.2.1.7       master0
kube-system       kube-controller-manager-2248957630-w2mxv          1/1       Running   0          6m        10.2.1.3       master0
kube-system       kube-dns-2431531914-1rkx7                         3/3       Running   0          6m        10.2.1.6       master0
kube-system       kube-etcd-0000                                    1/1       Running   0          4m        192.168.2.61   master0
kube-system       kube-etcd-network-checkpointer-v5qj1              1/1       Running   0          6m        192.168.2.61   master0
kube-system       kube-flannel-mlxns                                2/2       Running   0          6m        192.168.2.61   master0
kube-system       kube-flannel-slfqj                                2/2       Running   0          6m        192.168.2.71   worker0
kube-system       kube-flannel-z1qr6                                2/2       Running   0          6m        192.168.2.72   worker1
kube-system       kube-proxy-41z0b                                  1/1       Running   0          6m        192.168.2.61   master0
kube-system       kube-proxy-fkpdc                                  1/1       Running   0          6m        192.168.2.72   worker1
kube-system       kube-proxy-p2frr                                  1/1       Running   0          6m        192.168.2.71   worker0
kube-system       kube-scheduler-1310662694-9bw19                   1/1       Running   0          6m        10.2.1.5       master0
kube-system       kube-scheduler-1310662694-m3q7x                   1/1       Running   0          6m        10.2.1.4       master0
kube-system       pod-checkpointer-qbr0v                            1/1       Running   0          6m        192.168.2.61   master0
kube-system       pod-checkpointer-qbr0v-master0                    1/1       Running   0          5m        192.168.2.61   master0
tectonic-system   alertmanager-main-0                               2/2       Running   0          2m        10.2.0.4       worker0
tectonic-system   alertmanager-main-1                               2/2       Running   0          1m        10.2.2.11      worker1
tectonic-system   container-linux-update-agent-ds-4c2rd             1/1       Running   0          58s       10.2.2.12      worker1
tectonic-system   container-linux-update-agent-ds-j3k1t             1/1       Running   0          58s       10.2.0.11      worker0
tectonic-system   container-linux-update-agent-ds-wfw92             1/1       Running   0          58s       10.2.1.9       master0
tectonic-system   container-linux-update-operator-886082281-h1bn7   1/1       Running   0          1m        10.2.2.10      worker1
tectonic-system   default-http-backend-784379803-cdrm9              1/1       Running   0          1m        10.2.0.6       worker0
tectonic-system   kube-state-metrics-959915017-d7mkj                1/1       Running   0          2m        10.2.2.5       worker1
tectonic-system   kube-version-operator-89406705-bx9gs              1/1       Running   0          1m        10.2.0.8       worker0
tectonic-system   node-agent-4mnvl                                  1/1       Running   0          1m        10.2.2.8       worker1
tectonic-system   node-agent-hh49f                                  1/1       Running   0          1m        10.2.0.7       worker0
tectonic-system   node-agent-jc2ls                                  1/1       Running   0          1m        10.2.1.8       master0
tectonic-system   node-exporter-38351                               1/1       Running   0          2m        192.168.2.71   worker0
tectonic-system   node-exporter-g5ktx                               1/1       Running   0          2m        192.168.2.72   worker1
tectonic-system   node-exporter-vcdwd                               1/1       Running   0          2m        192.168.2.61   master0
tectonic-system   prometheus-k8s-0                                  2/2       Running   0          2m        10.2.0.5       worker0
tectonic-system   prometheus-operator-775778252-tkvvs               1/1       Running   0          28s       10.2.0.12      worker0
tectonic-system   tectonic-channel-operator-2230218413-l026p        1/1       Running   0          1m        10.2.2.9       worker1
tectonic-system   tectonic-console-962128392-89fp7                  1/1       Running   1          2m        10.2.2.2       worker1
tectonic-system   tectonic-console-962128392-b2f30                  1/1       Running   1          2m        10.2.0.3       worker0
tectonic-system   tectonic-identity-3240565221-wxsgk                1/1       Running   0          2m        10.2.2.4       worker1
tectonic-system   tectonic-identity-3240565221-xlwd8                1/1       Running   0          2m        10.2.0.2       worker0
tectonic-system   tectonic-ingress-controller-1dwwn                 1/1       Running   0          1m        192.168.2.72   worker1
tectonic-system   tectonic-ingress-controller-xs0p7                 1/1       Running   0          1m        192.168.2.71   worker0
tectonic-system   tectonic-prometheus-operator-2937135703-m2sjn     1/1       Running   0          1m        10.2.0.9       worker0
tectonic-system   tectonic-stats-emitter-2611508926-qz1cf           2/2       Running   0          1m        10.2.2.7       worker1
```

**Comment by kans** [comment]
The AWS smoke test timed out - it looks like cluster creation took ~30 minutes ( no time for the tests).

**Comment by squat** [comment]
ok to test

**Comment by squat** [comment]
PTAL @kans @Quentin-m

**Pull request merged**
