### PR TITLE
Prometheus requires security group rule to access etcd from workers

### PR DESCRIPTION
**Pull request by alexsomesan**
This changes allows Prometheus running on a worker to scrape etcd.
/cc: @brancz 

required by:
https://github.com/coreos-inc/tectonic-prometheus-operator/pull/49
https://github.com/coreos/tectonic-installer/issues/579

### CODE REVIEW

**Comment by philips** [comment]
Agreed, we should't do this. What is the use case? What alternatives were considered or are available?

**Comment by alexsomesan** [comment]
We shouldn't run Prometheus on masters because of it's high demand for
resources, so that's not really an option.

Also not an option to create a ClusterIP service for etcd, which falls
under the same security concerns raised here.

I will have to check with @brancz and brainstorm on alternatives.

**Comment by alexsomesan** [comment]
A possible option would be enabling client cert auth on etcd to secure it against unauthorized access and still go with allowing access via ClusterIP.

@philips @sym3tri Thoughts?

**Comment by brancz** [comment]
Use case is that Prometheus can scrape etcd metrics. Client cert authentication could be a solution, but we would also want to make sure that only the metrics are accessible with that client cert, not actually using etcd. Does etcd have an authz model of some sort that we could leverage for this? If not then we have to consider whether monitoring and alerting or security outweighs the other.

Until we figure out how to do this we won't be able to collect etcd metrics.

/cc @fabxc

**Comment by brancz** [comment]
We can also consider whether putting metrics on different port and only allow access to that is isolation enough. It might be a compromize, but I'm not sure whether etcd allows this today.

**Comment by sym3tri** [comment]
I'm open to other suggestions, but we should not try to rush this in.

Design constraint is: customers need to completely block network access from worker nodes to etcd (whether authenticated or not).

**Comment by alexsomesan** [comment]
I just realized another option here:

We can deploy a statically configured Prometheus on the master nodes, that
just scrapes etcd and exports it's metrics onwards for the main Prometheus
to scrape.
On this Prometheus instance we could have tight resource constrains to make
sure it won't brown out the control plane components running on the same
master.

@brancz Is this feasible?

**Comment by brancz** [comment]
Funnily enough that is exactly what @mxinden just suggested.

Yes that would work in theory, but currently the Prometheus Operator does not support tolerations and node affinity, so we'll have to implement that support before we can do that. Other than that this would also require federation support in the Prometheus Operator which we have conceptually thought about, but have not implemented yet either.

**Comment by fabxc** [comment]
Federation technically works with the current operator as we support the `honorLabels` paramters now, which is the only thing differentiating a federation target from a regular one. 

With some feature additions to prometheus-operator, we can place a proxy on the master node that Prometheus can scrape etcd through.
It would mean that we still expose an endpoints object for etcd. So the IPs of etcd nodes are still visible but cannot be routed to from worker nodes. Are we okay with that? The setup proxy would then just let `GET /metrics` through. If there are DDoS concerns, we can also rate-limit that to only match roughly Prometheus' scrape interval.

**Comment by sym3tri** [comment]
Closing for now. Please open another issue that details the requirements and we can agree on a solution there.

**Pull request closed without merging**
