### PR TITLE
azure/vnet: Use subnet NSGs instead of NIC NSGs

### PR DESCRIPTION
**Pull request by justaugustus**

### CODE REVIEW

**Comment by sym3tri** [comment]
What's the purpose of the change?

**Comment by alexsomesan** [comment]
I recently made the switch in the opposite direction, from subnet to nic to harden security (instances lunched in the subnet don't automatically get cluster access).

Is there an issue with this arrangement that I didn't account for?

**Comment by alexsomesan** [comment]
retest this please

**Comment by justaugustus** [comment]
@sym3tri @alexsomesan the reason for this change is that Azure differentiates between NIC-type NSGs and subnet-type NSGs. If a NSG is bound to either NIC or subnet, it cannot be used for the other.

This comes into play when a customer provides an `external_nsg_*_id` which is already bound to a subnet and then the installer attempts to bind that subnet NSG to the installer NICs.

This results in the following error:
```shell
Error applying plan:

8 error(s) occurred:

* module.vnet.azurerm_network_interface.tectonic_worker[2]: 1 error(s) occurred:

* azurerm_network_interface.tectonic_worker.2: network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="LinkedAuthorizationFailed" Message="The client '<service-principal-id>' with object id '<service-principal-id>' has permission to perform action 'Microsoft.Network/networkInterfaces/write' on scope '/subscriptions/<subscription-id>/resourceGroups/tectonic-cluster-aug-c01/providers/Microsoft.Network/networkInterfaces/aug-c01-worker-2'; however, it does not have permission to perform action 'Microsoft.Network/networkSecurityGroups/join/action' on the linked scope(s) '<nsg-id>'."
* module.vnet.azurerm_network_interface.tectonic_worker[1]: 1 error(s) occurred:

* azurerm_network_interface.tectonic_worker.1: network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="LinkedAuthorizationFailed" Message="The client '<service-principal-id>' with object id '<service-principal-id>' has permission to perform action 'Microsoft.Network/networkInterfaces/write' on scope '/subscriptions/<subscription-id>/resourceGroups/tectonic-cluster-aug-c01/providers/Microsoft.Network/networkInterfaces/aug-c01-worker-1'; however, it does not have permission to perform action 'Microsoft.Network/networkSecurityGroups/join/action' on the linked scope(s) '<nsg-id>'."
* module.vnet.azurerm_network_interface.etcd_nic[0]: 1 error(s) occurred:

* azurerm_network_interface.etcd_nic.0: network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="LinkedAuthorizationFailed" Message="The client '<service-principal-id>' with object id '<service-principal-id>' has permission to perform action 'Microsoft.Network/networkInterfaces/write' on scope '/subscriptions/<subscription-id>/resourceGroups/tectonic-cluster-aug-c01/providers/Microsoft.Network/networkInterfaces/aug-c01-etcd-nic-0'; however, it does not have permission to perform action 'Microsoft.Network/networkSecurityGroups/join/action' on the linked scope(s) '<nsg-id>'."
* module.vnet.azurerm_network_interface.tectonic_worker[0]: 1 error(s) occurred:

* azurerm_network_interface.tectonic_worker.0: network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="LinkedAuthorizationFailed" Message="The client '<service-principal-id>' with object id '<service-principal-id>' has permission to perform action 'Microsoft.Network/networkInterfaces/write' on scope '/subscriptions/<subscription-id>/resourceGroups/tectonic-cluster-aug-c01/providers/Microsoft.Network/networkInterfaces/aug-c01-worker-0'; however, it does not have permission to perform action 'Microsoft.Network/networkSecurityGroups/join/action' on the linked scope(s) '<nsg-id>'."
* module.vnet.azurerm_network_interface.tectonic_master[0]: 1 error(s) occurred:

* azurerm_network_interface.tectonic_master.0: network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="LinkedAuthorizationFailed" Message="The client '<service-principal-id>' with object id '<service-principal-id>' has permission to perform action 'Microsoft.Network/networkInterfaces/write' on scope '/subscriptions/<subscription-id>/resourceGroups/tectonic-cluster-aug-c01/providers/Microsoft.Network/networkInterfaces/aug-c01-master-0'; however, it does not have permission to perform action 'Microsoft.Network/networkSecurityGroups/join/action' on the linked scope(s) '<nsg-id>'."
* module.vnet.azurerm_network_interface.etcd_nic[1]: 1 error(s) occurred:

* azurerm_network_interface.etcd_nic.1: network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="LinkedAuthorizationFailed" Message="The client '<service-principal-id>' with object id '<service-principal-id>' has permission to perform action 'Microsoft.Network/networkInterfaces/write' on scope '/subscriptions/<subscription-id>/resourceGroups/tectonic-cluster-aug-c01/providers/Microsoft.Network/networkInterfaces/aug-c01-etcd-nic-1'; however, it does not have permission to perform action 'Microsoft.Network/networkSecurityGroups/join/action' on the linked scope(s) '<nsg-id>'."
* module.vnet.azurerm_network_interface.etcd_nic[2]: 1 error(s) occurred:

* azurerm_network_interface.etcd_nic.2: network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="LinkedAuthorizationFailed" Message="The client '<service-principal-id>' with object id '<service-principal-id>' has permission to perform action 'Microsoft.Network/networkInterfaces/write' on scope '/subscriptions/<subscription-id>/resourceGroups/tectonic-cluster-aug-c01/providers/Microsoft.Network/networkInterfaces/aug-c01-etcd-nic-2'; however, it does not have permission to perform action 'Microsoft.Network/networkSecurityGroups/join/action' on the linked scope(s) '<nsg-id>'."
* module.vnet.azurerm_network_interface.tectonic_master[1]: 1 error(s) occurred:

* azurerm_network_interface.tectonic_master.1: network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="LinkedAuthorizationFailed" Message="The client '<service-principal-id>' with object id '<service-principal-id>' has permission to perform action 'Microsoft.Network/networkInterfaces/write' on scope '/subscriptions/<subscription-id>/resourceGroups/tectonic-cluster-aug-c01/providers/Microsoft.Network/networkInterfaces/aug-c01-master-1'; however, it does not have permission to perform action 'Microsoft.Network/networkSecurityGroups/join/action' on the linked scope(s) '<nsg-id>'."
```

The easiest way to address this for most customer cases is to remove the parameter and just provide the tighter guidelines for subnet NSGs, which can be seen here: #1929

**Comment by sym3tri** [comment]
@justaugustus thanks for clarifying. I'll leave review up to @alexsomesan though.

**Comment by alexsomesan** [comment]
@justaugustus Wasn't aware this would block external NSGs. Your case makes sense, let's flip it back to subnets then.

Also, I'll file an issue to write a smoke test that works through the external NSG use case to keep this in check in the future.

**Comment by alexsomesan** [comment]
@justaugustus This change needs to also re-introduce the `network_security_group_id` on subnets in order to work as expected (current master doesn't have those anymore).

**Pull request merged**
