### PR TITLE
config.tf, payload.json: Bump TCO to 0.4.2

### PR DESCRIPTION
**Pull request by yifan-gu**

### CODE REVIEW

**Comment by yifan-gu** [comment]
e2e test

**Comment by yifan-gu** [comment]
test upgrade from 1.6.7-tectonic.2 1.6.7-tectonic.2

**Comment by yifan-gu** [comment]
test upgrade from 1.7.1-tectonic.1 1.7.1-tectonic.1

**Comment by yifan-gu** [comment]
test upgrade from 1.6.7-tectonic.2 1.6.7-tectonic.2

**Comment by Quentin-M** [comment]
Most tests passed (except Azure), including the upgrade tests. Merging!

**Pull request merged**
