### PR TITLE
config.tf, payload.json: Bump TCO to 0.4.2

### PR DESCRIPTION
**Pull request by yifan-gu**

### CODE REVIEW

**Comment by yifan-gu** [comment]
e2e test

**Comment by yifan-gu** [comment]
test upgrade from 1.6.7-tectonic.2 1.6.7-tectonic.2

**Comment by Quentin-M** [comment]
@yifan-gu 

```
I0814 23:39:24.537195       1 leaderelection.go:179] attempting to acquire leader lease...
E0814 23:39:25.836286       1 event.go:260] Could not construct reference to: '&v1.ConfigMap{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"tectonic-channel-operator", GenerateName:"", Namespace:"tectonic-system", SelfLink:"/api/v1/namespaces/tectonic-system/configmaps/tectonic-channel-operator", UID:"ce9f5dc0-8149-11e7-b25a-028d7d66ef67", ResourceVersion:"15534", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:63638350765, nsec:0, loc:(*time.Location)(0x2aa62e0)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"control-plane.alpha.kubernetes.io/leader":"{\"holderIdentity\":\"tectonic-channel-operator-fb0ba044\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2017-08-14T23:39:24Z\",\"renewTime\":\"2017-08-14T23:39:24Z\",\"leaderTransitions\":0}"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Data:map[string]string(nil)}' due to: 'no kind is registered for the type v1.ConfigMap'. Will not report event: 'Normal' 'LeaderElection' 'tectonic-channel-operator-fb0ba044 became leader'
I0814 23:39:25.935581       1 leaderelection.go:189] successfully acquired lease tectonic-system/tectonic-channel-operator
I0814 23:39:34.035935       1 main.go:514] Tectonic Channel Operator starts watching updates from core update
```

**Comment by yifan-gu** [comment]
test upgrade from 1.6.7-tectonic.2 1.6.7-tectonic.2

**Comment by yifan-gu** [comment]
test upgrade from 1.6.7-tectonic.2 1.6.7-tectonic.2

**Comment by yifan-gu** [comment]
The tests failed because I accidentally removed the vpc during a clean up... Kicking it off again.

**Comment by yifan-gu** [comment]
test upgrade from 1.6.7-tectonic.1 1.6.7-tectonic.1

**Comment by Quentin-M** [comment]
test upgrade from 1.6.7-tectonic.1 1.6.7-tectonic.1

**Pull request merged**
