### PR TITLE
monitoring: bump monitoring to 1.5.2, CRD compatiblity

### PR DESCRIPTION
**Pull request by colhom**
This will need to be cherry-picked on to 1.7.3 branch as well.

\cc @brancz

### CODE REVIEW

**Comment by Quentin-M** [comment]
@colhom Can you make the PR to the release branch too?

**Comment by brancz** [comment]
The Prometheus Operator is not ready to be shipped yet with the Tectonic Prometheus Operator in this release. Only bumping the AppVersion and TPO to 1.5.2 is what we want for this release, not PO v0.12.0. The TPO would override this anyways.

Monitoring manifests should never be bumped without previously bumping them in the TPO repository.

**Comment by Quentin-M** [comment]
I might have misunderstood what we need to bump in the flow of information!
Thanks.

**Comment by brancz** [comment]
Yes the only thing we need to bump is the tectonic-monitoring AppVersion and the image of the TPO to `v1.5.2`, it is just a minor change in the TPO itself. This version of the TPO is not compatible yet with the latest release of the open source Prometheus Operator, that is targeted to land in the next release.

**Comment by colhom** [comment]
@brancz ack, sorry for the misunderstanding.

Also +1 for distributing assets canonically within TPO

**Pull request closed without merging**
