### PR TITLE
config.tf: update TPO to 1.5.2

### PR DESCRIPTION
**Pull request by Quentin-M**

### CODE REVIEW

**Comment by Quentin-M** [comment]
https://github.com/coreos/tectonic-installer/pull/1776

**Comment by Quentin-M** [comment]
https://github.com/coreos/tectonic-installer/pull/1776

**Comment by brancz** [comment]
The "tectonic-monitoring" version needs to be bumped to the same version (`v1.5.2`). Same goes for the other PR.

**Comment by brancz** [comment]
lgtm

**Pull request merged**
