### PR TITLE
[TECREL] vars/*: Ensure proxy vars are set as optional

### PR DESCRIPTION
**Pull request by justaugustus**
Fixes: https://jira.coreos.com/browse/TECREL-158

cc: @sudhaponnaganti / @cricci82

### CODE REVIEW

**Comment by squat** [comment]
ok to test

**Comment by squat** [comment]
cc @alexsomesan

**Comment by sudhaponnaganti** [comment]
@cpanato can you check the failed tests ?
@justaugustus  - once tests are passed this can be merged as all other approvals are done. Pl make sure this is done by Friday
cc/ @coverprice

**Comment by cpanato** [comment]
@sudhaponnaganti  re-running the failed tests.

**Pull request merged**
