### PR TITLE
config.tf: update TPO to 1.5.2

### PR DESCRIPTION
**Pull request by Quentin-M**

### CODE REVIEW

**Comment by Quentin-M** [comment]
test upgrade from tectonic-1.7.1-tectonic.1 tectonic-1.7.1-tectonic.1

**Comment by yifan-gu** [comment]
test upgrade from 1.7.1-tectonic.1 1.7.1-tectonic.1

**Comment by Quentin-M** [comment]
https://github.com/coreos/tectonic-installer/pull/1776

**Comment by Quentin-M** [comment]
test upgrade from 1.7.1-tectonic.1 1.7.1-tectonic.1

**Comment by brancz** [comment]
I mentioned this in the other PR, but just repeating here to make sure we catch it. This also needs to bump the "tectonic-monitoring" version to `v1.5.2`. (TPO and tectonic-monitoring versions are always in sync)

**Comment by Quentin-M** [comment]
test upgrade from 1.7.1-tectonic.1 1.7.1-tectonic.1

**Comment by brancz** [comment]
lgtm

**Pull request merged**
