### PR TITLE
config.tf: 1.8.9-tectonic.3, bump tco, kvo, console and tcluo

### PR DESCRIPTION
**Pull request by yifan-gu**
- tco: 0.6.4
- kvo: v1.8.9-kvo.4
- console: v5.0.6
- tcluo: v0.3.2

### CODE REVIEW

**Comment by yifan-gu** [comment]
test upgrade from 1.8.7-tectonic.2 1.8.7-tectonic.2

**Comment by yifan-gu** [comment]
test upgrade from 1.8.9-tectonic.2 1.8.9-tectonic.2

**Comment by abhinavdahiya** [comment]
retest this please, aws and azure only.

**Comment by yifan-gu** [comment]
test upgrade from 1.8.9-tectonic.2 1.8.9-tectonic.2

**Comment by yifan-gu** [comment]
test upgrade from 1.8.9-tectonic.2 1.8.9-tectonic.2

**Comment by abhinavdahiya** [comment]
retest this please. aws and azure only

**Comment by abhinavdahiya** [comment]
retest this please. aws, azure only

**Comment by yifan-gu** [comment]
retest this please

**Comment by abhinavdahiya** [comment]
retest this please.

**Comment by yifan-gu** [comment]
test upgrade from 1.8.9-tectonic.2 1.8.9-tectonic.2

**Pull request merged**
