### PR TITLE
kvo: bump to v1.7.1-kvo.5

### PR DESCRIPTION
**Pull request by diegs**

### CODE REVIEW

**Comment by diegs** [comment]
test upgrade from 1.6.7-tectonic.2 1.6.7-tectonic.2

**Comment by Quentin-M** [comment]
ok to test

**Comment by Quentin-M** [comment]
I was waiting for the tests to pass. They did not get triggered. Oookkay.

**Comment by diegs** [comment]
@Quentin-M azure tests failed, bare metal didn't run?

**Comment by Quentin-M** [comment]
I am on my phone right now but:
- Azure used to fail due to subscription - I heard this was solved, so
maybe it's different
- Packet is broken since last week due to a modification in their API and
we never updated JClouds

**Comment by diegs** [comment]
It looks like Azure did fail due to some subscription thing. Up to you how to proceed.

**Comment by sym3tri** [comment]
@diegs @mxinden is looking into Azure failures and should have a fix soon.

**Comment by mxinden** [comment]
@diegs Please rebase to current master to have the fixes from #1558 in here.

**Comment by Quentin-M** [comment]
Smoke tests always automatically rebase on master (thus the name `continuous-integration/jenkins/pr-merge`). There is no need for him to rebase if you'd like to test that PR with master changes, just re-trigger the tests.

**Comment by mxinden** [comment]
@Quentin-M right, forgot about that. Thanks for the reminder. I have retriggered the tests.

**Comment by Quentin-M** [comment]
Azure is still failing.

**Comment by mxinden** [comment]
@Quentin-M I am not sure we are rebasing properly onto master. The builds of this PR are still using the `test-ext-group`, which we [deleted](https://github.com/coreos/tectonic-installer/pull/1558/files#diff-3df783df6b9b60d22a589d0d356d99d1L7) in #1558.

This might be due to the simple [`checkout scm`](https://github.com/coreos/tectonic-installer/blob/master/Jenkinsfile#L464) on each worker node that we use instead of the full rebase Jenkins does automatically on the master node.

**Comment by Quentin-M** [comment]
@mxinden I see! Thank you for the explanation and sorry about the misunderstanding!

**Comment by diegs** [comment]
I will rebase.

**Comment by Quentin-M** [comment]
Only a single failure on Azure. Cool 👍

**Pull request merged**
