### PR TITLE
[WIP] modules/bootkube: Make log verbosity configurable

### LINKED ISSUE #2002: Feature request: configurable log verbosity for k8s services
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

It would be useful to expose a variable to increase the log verbosity for troubleshooting k8s. I'm proposing an optional variable called something like `k8s_log_verbosity` that will add the relevant configuration to the k8s component manifests (kube-apiserver, etc.).

It would look something like this:

_build/my-cluster/terraform.tfvars_
```
...
k8s_log_verbosity = 4
```

_tectonic-installer/modules/bootkube/resources/manifests/kube-controller-manager.yaml_
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-controller-manager
  namespace: kube-system
  labels:
    tier: control-plane
    k8s-app: kube-controller-manager
    tectonic-operators.coreos.com/managed-by: kube-version-operator
spec:
  replicas: ${master_count}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      tier: control-plane
      k8s-app: kube-controller-manager
  template:
    metadata:
      labels:
        tier: control-plane
        k8s-app: kube-controller-manager
        pod-anti-affinity: kube-controller-manager-${kubernetes_version}
        tectonic-operators.coreos.com/managed-by: kube-version-operator
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                pod-anti-affinity: kube-controller-manager-${kubernetes_version}
            namespaces:
              - kube-system
            topologyKey: kubernetes.io/hostname
      containers:
      - name: kube-controller-manager
        image: ${hyperkube_image}
        command:
        - ./hyperkube
        - controller-manager
        - --allocate-node-cidrs=true
        - --configure-cloud-routes=false
        - --cluster-cidr=${cluster_cidr}
        - --root-ca-file=/etc/kubernetes/secrets/ca.crt
        - --service-account-private-key-file=/etc/kubernetes/secrets/service-account.key
        - --leader-elect=true
        - --node-monitor-grace-period=${node_monitor_grace_period}
        - --pod-eviction-timeout=${pod_eviction_timeout}
        - --v=${k8s_log_verbosity}
        - --cloud-provider=${cloud_provider}
        ${cloud_provider_config_flag}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10252  # Note: Using default port. Update if --port option is set differently.
          initialDelaySeconds: 15
          timeoutSeconds: 15
        volumeMounts:
        - name: secrets
          mountPath: /etc/kubernetes/secrets
          readOnly: true
        - mountPath: /etc/kubernetes/cloud
          name: cloud-config
          readOnly: true
        - name: ssl-host
          mountPath: /etc/ssl/certs
          readOnly: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: secrets
        secret:
          secretName: kube-controller-manager
      - name: cloud-config
        secret:
          secretName: kube-cloud-cfg
      - name: ssl-host
        hostPath:
          path: /usr/share/ca-certificates
      dnsPolicy: Default # Don't use cluster DNS.
```

### PR DESCRIPTION
**Pull request by lblackstone**
Add a variable to optionally configure the log verbosity of k8s components. This is useful for troubleshooting bugs in Kubernetes.

Fixes #2002

### CODE REVIEW

**Comment by lblackstone** [comment]
I've implemented this for OpenStack so far. If this approach looks good, I can add the other platforms as well.

**Comment by mxinden** [comment]
We did some changes (https://github.com/coreos/tectonic-installer/pull/2082) to the testing process. Please rebase on to current master, so that the `basic-tests` PR status is reported correctly.

**Comment by lblackstone** [comment]
@coreos/team-installer Could somebody take a look at this WIP and let me know if this approach is ok?

**Comment by mxinden** [comment]
@lblackstone I am sorry for the late reply. @s-urbaniak just added the ability to add debug configuration for the kubelet (https://github.com/coreos/tectonic-installer/pull/2359).

@s-urbaniak Can you advice on how to further proceed here?

**Comment by lblackstone** [comment]
ping @s-urbaniak

**Comment by cpanato** [comment]
Hello @lblackstone can you please rebase and resolve the conflicts then I can take a look.

**Comment by lblackstone** [comment]
@cpanato It looks like the bootkube manifests are being generated at runtime now, so this would require more major refactoring than I have time for at the moment. I can take another look at some point if you think it's worth the effort.

**Comment by cpanato** [comment]
ok, let me check that. thanks

**Comment by enxebre** [comment]
@lblackstone thanks a lot for this contribution. We're going through master refactor that will allow easier customisation so this would require a different approach now as you just rightly pointed. @cpanato let's close it for now and will reopen if needed

**Pull request closed without merging**
