### PR TITLE
tests: add logstash project to track1

### PR DESCRIPTION
**Pull request by erikkn**
Add the Logstash project to the track-1 branch.

### CODE REVIEW

**Comment by erikkn** [comment]
test again please

**Comment by erikkn** [comment]
retest this please

**Comment by erikkn** [comment]
@mxinden

**Comment by erikkn** [comment]
Waiting for Logstash to stream the log file into ES. Check this again tomorrow.

**Comment by erikkn** [comment]
Missing the BUILD_RESULT attribute in ES/Kibana. Working on this.

**Comment by erikkn** [comment]
ok to test

**Comment by erikkn** [comment]
ok to test

**Comment by erikkn** [comment]
ok to test

**Comment by mxinden** [comment]
ok to test

**Comment by erikkn** [comment]
@mxinden , flakes?

**Comment by erikkn** [comment]
ok to test

**Comment by erikkn** [comment]
@mxinden

**Comment by mxinden** [comment]
Unrelated test failures over multiple test runs, in sum being all green. I will merge with azure/example failing on #14.

**Pull request merged**
