### PR TITLE
config.tf: Bump flannel version v0.8.0->v0.9.1

### PR DESCRIPTION
**Pull request by tomdee**
Release notes:
* https://github.com/coreos/flannel/releases/tag/v0.9.0
* https://github.com/coreos/flannel/releases/tag/v0.9.1

### CODE REVIEW

**Comment by squat** [comment]
ok to test

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
@tomdee can you please rebase and fix the conflict?

**Comment by tomdee** [comment]
@cpanato I tried to update this but I can't see where the flannel version is stored anymore. It's no longer in config.tf

**Comment by cpanato** [comment]
@tomdee ahh, yeah, this is managed by an operator now, called tectonic-tno. We don't manage any more flannel versions the operator takes care.

so, I guess we can close this PR.

**Comment by tomdee** [comment]
Can you point me at the source for tectonic-tno so I can update the flannel version there?

**Comment by cpanato** [comment]
@tomdee  https://github.com/coreos-inc/tectonic-operators/blob/master/tectonic-network-operator/manifests/flannel/kube-flannel-daemonset.yaml#L27

**Comment by sym3tri** [comment]
confirmed this change was already made in TNO here: https://github.com/coreos-inc/tectonic-operators/blob/master/operator/network/manifests/flannel/kube-flannel-daemonset.yaml#L23

**Pull request closed without merging**
