### PR TITLE
modules/tectonic: set correct utility config kind

### PR DESCRIPTION
**Pull request by squeed**

### CODE REVIEW

**Comment by squat** [comment]
ok to test

**Comment by squat** [comment]
ok to test

**Comment by enxebre** [comment]
Not sure how the logic behind it fully works yet but something else probably need to be changed as the operators seems to be only happy with kind AddonConfig and kind UtilityConfig rather than TectonicUtilityOperatorConfig and TectonicUtilityOperatorConfig

**Comment by squeed** [comment]
I think you're right. The Kind needs to match exactly the kind defined in tectonic-config, e.g. https://github.com/coreos/tectonic-config/blob/master/config/tectonic-utility/config.go
I'll update this PR and check.

**Comment by squeed** [comment]
I think I'll actually fix this in #2917

**Comment by squat** [comment]
Closing in favor of #2917

**Pull request closed without merging**
