### PR TITLE
Revert "modules/update-payload: fix payload gen failure introduced by #2465"

### PR DESCRIPTION
**Pull request by Quentin-M**
Reverts coreos/tectonic-installer#2475

### CODE REVIEW

**Comment by cpanato** [comment]
ok to test

**Comment by cpanato** [comment]
@Quentin-M all tests in all platforms are green

**Comment by Quentin-M** [comment]
```
$ terraform init

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

$ while true; do echo "place_holder_for_terraform_input"; done | terraform apply ./
var.tectonic_admin_email
  (internal) The e-mail address used to:
  1. login as the admin user to the Tectonic Console.
  2. generate DNS zones for some providers.

  Note: This field MUST be in all lower-case e-mail address format and set manually prior to creating the cluster.

  Enter a value:
var.tectonic_admin_password
  (internal) The admin user password to login to the Tectonic Console.

  Note: This field MUST be set manually prior to creating the cluster. Backslashes and double quotes must
  also be escaped.

  Enter a value:
var.tectonic_base_domain
  The base DNS domain of the cluster. It must NOT contain a trailing period. Some
  DNS providers will automatically add this if necessary.

  Example: `openstack.dev.coreos.systems`.

  Note: This field MUST be set manually prior to creating the cluster.
  This applies only to cloud platforms.

  [Azure-specific NOTE]
  To use Azure-provided DNS, `tectonic_base_domain` should be set to `""`
  If using DNS records, ensure that `tectonic_base_domain` is set to a properly configured external DNS zone.
  Instructions for configuring delegated domains for Azure DNS can be found here: https://docs.microsoft.com/en-us/azure/dns/dns-delegate-domain-azure-dns

  Enter a value:
var.tectonic_cluster_name
  The name of the cluster.
  If used in a cloud-environment, this will be prepended to `tectonic_base_domain` resulting in the URL to the Tectonic console.

  Note: This field MUST be set manually prior to creating the cluster.
  Warning: Special characters in the name like '.' may cause errors on OpenStack platforms due to resource name constraints.

  Enter a value:
template_dir.payload_appversions: Refreshing state... (ID: a5b63bbf4bf41f242fcd3b2913c9cb9265a4b90d)
template_dir.payload_operators: Refreshing state... (ID: b730eba5f94106cafa5a916a28e64ff75b314b1b)

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

Thanks Carlos! All good now.

**Comment by Quentin-M** [comment]
cc @thorfour

**Comment by Quentin-M** [comment]
Received Go from Sudha.

**Pull request merged**
