### PR TITLE
remove vanilla kubernetes

### PR DESCRIPTION
**Pull request by enxebre**
The Tectonic Installer is now undergoing some major architectural changes. Since our focus will be on these new changes and the complete Tectonic product, we are removing the 'Vanilla Kubernetes' mode of installation for the time being. Once the architectural changes are complete we will reevaluate the best way to support this feature going forward. If you would like to use 'vanilla Kubernetes' mode, we suggest using an older version of the installer versioned 1.8.4 or lower.

### CODE REVIEW

**Comment by cpanato** [comment]
needs rebase @enxebre

**Comment by enxebre** [comment]
retest this please

**Comment by enxebre** [comment]
retest this please

**Comment by enxebre** [comment]
retest this please

**Comment by enxebre** [comment]
retest this please

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
all green 🎉

**Comment by enxebre** [comment]
retest this please

**Comment by enxebre** [comment]
retest this please

**Comment by rowleyaj** [comment]
@enxebre is it possible to get some insight into the major architectural changes that are being made?

**Comment by enxebre** [comment]
hey @rowleyaj As a rough overview we are refactoring the bootstrapping process to allow cleaner boundaries between infra and cluster config by relying on customisable Ignition profiles. Hope that give you an idea

**Pull request merged**
