### PR TITLE
Added cloud provider to addon-operator config

### PR DESCRIPTION
**Pull request by thorfour**
Have addon-operator track the cloud provider: CORS-389 
For future addition of adding a default storage class.

Related tectonic-operators PR: https://github.com/coreos-inc/tectonic-operators/pull/148

### CODE REVIEW

**Comment by diegs** [comment]
@thorfour probably needs some smoke test labels yes?

**Comment by diegs** [comment]
coreosbot test this please

**Comment by thorfour** [comment]
ok to test

**Comment by squat** [comment]
The VPC test failed because Jenkins failed to download the Terraform matchbox provider due to some transient network error. Restarting tests.

**Comment by squat** [comment]
retest this please

**Pull request merged**
