### PR TITLE
WIP tests: tag aws testing resources

### PR DESCRIPTION
**Pull request by kans**

### CODE REVIEW

**Comment by kans** [comment]
testing jenkins

**Comment by kans** [comment]
testing jenkins

**Comment by Quentin-M** [comment]
Sorry for the spam. Was repairing Jenkins.

**Comment by sym3tri** [comment]
@kans @Quentin-M 
What's going on here? Looks like just CI testing. I'm closing for now. Reopen if needed.

**Comment by kans** [comment]
@sym3tri

This is an actual PR that we were abusing to test Jenkins.

**Comment by sym3tri** [comment]
oops. sorry.

**Comment by kans** [comment]
I think we should be tagging with the build id (PR number) instead.

**Pull request closed without merging**
