### PR TITLE
config.tf: bump versions for 1.7.9-tectonic.4

### PR DESCRIPTION
**Pull request by diegs**
- console
- kvo
- kubernetes
- tectonic

### CODE REVIEW

**Comment by diegs** [comment]
test upgrade from 1.7.5-tectonic.1 1.7.5-tectonic.1

**Comment by sudhaponnaganti** [comment]
@yifan-gu @Quentin-M - can you review this

**Comment by diegs** [comment]
@cpanato any ideas about the azure failures? Also seeing them in #2654

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
re-running only on `Azure` because `AWS` and `Bare Metal` already passed.

**Comment by cpanato** [comment]
I ran mannualy the conformance tests on `AWS` and it passed:

```
Ran 124 of 699 Specs in 3115.225 seconds
SUCCESS! -- 124 Passed | 0 Failed | 0 Pending | 575 Skipped PASS
```

**Comment by cpanato** [comment]
All tests are green, jenkins did not report back the status to github.

**Comment by sudhaponnaganti** [comment]
@cpanato - why status is not being exiting - looks like all checks are done.

**Comment by cpanato** [comment]
for this branch the github/jenkins sometimes don't report properly. @sudhaponnaganti 
All tests are green. good to go.

**Comment by diegs** [comment]
@cpanato @yifan-gu will need an approval to merge

**Comment by diegs** [comment]
Thanks, I will also need @cpanato or @yifan-gu to merge since I do not have privileges to override the stuck status check.

**Comment by cpanato** [comment]
@diegs done

**Pull request merged**
