### PR TITLE
config.tf: Bump TCO to 0.5.3, KVO to v1.7.3-kvo.3.

### PR DESCRIPTION
**Pull request by yifan-gu**
TCO: Minor logging tweaks.
KVO: Add migration for configmap for console.

### CODE REVIEW

**Comment by yifan-gu** [comment]
KVO is not cut yet, blocked by https://github.com/coreos-inc/kube-version-operator/pull/235

**Comment by Quentin-M** [comment]
@yifan-gu Can you make it on master too? Tyy

**Comment by yifan-gu** [comment]
@Quentin-M Of course I did already.

**Comment by yifan-gu** [comment]
test upgrade from 1.6.7-tectonic.2 1.6.7-tectonic.2

**Comment by Quentin-M** [comment]
@yifan-gu KVO is not cut - ain't gonna work 💯

**Comment by yifan-gu** [comment]
test upgrade from 1.6.7-tectonic.2 1.6.7-tectonic.2

**Comment by yifan-gu** [comment]
test upgrade from 1.6.7-tectonic.2 1.6.7-tectonic.2

**Comment by yifan-gu** [comment]
Increased timeout since it's going through several versions.

**Comment by Quentin-M** [comment]
```
=== RUN   TestUpgrade/after_upgrade
--- FAIL: TestUpgrade (1801.25s)
    --- PASS: TestUpgrade/before_upgrade (0.20s)
    --- FAIL: TestUpgrade/upgrade (1800.63s)
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "Unable to connect to the server: EOF\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "Unable to connect to the server: EOF\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:99: failed to run kubectl: exit status 1, output: "the server doesn't have a resource type \"appversions\" in group \"tco.coreos.com\"\n"
    	upgrade_test.go:112: timed out waiting for the condition
    --- FAIL: TestUpgrade/after_upgrade (0.42s)
    	upgrade_test.go:151: expected current version 1.7.3+tectonic.1 got 1.7.1+tectonic.1 for AppVersion kubernetes
FAIL
```

**Comment by yifan-gu** [comment]
I thought I ran the test with timeout = 60m, hmm

**Comment by yifan-gu** [comment]
test upgrade from 1.6.7-tectonic.2 1.6.7-tectonic.2

**Comment by yifan-gu** [comment]
OK, there is another timeout value in the test itself, I just removed it.

**Comment by yifan-gu** [comment]
test upgrade from 1.6.7-tectonic.2 1.6.7-tectonic.2

**Comment by yifan-gu** [comment]
kvo image was not available last time. Trying again.

**Comment by Quentin-M** [comment]
test upgrade from 1.6.7-tectonic.2 1.6.7-tectonic.2

**Comment by Quentin-M** [comment]
Smoke tests are OK. Just need the upgrade tests.

**Pull request merged**
