### PR TITLE
*: Add RollingUpdate strategy to DS manifests

### PR DESCRIPTION
**Pull request by derekparker**
New KVO uses upstream DS rolling updates, and so now we need to specifiy
the correct strategy.

### CODE REVIEW

**Comment by derekparker** [comment]
Fixes https://github.com/coreos/tectonic-installer/issues/514

**Comment by derekparker** [comment]
Don't have access to the failing job.

**Comment by Quentin-M** [comment]
Will it still work with single master?

**Comment by derekparker** [comment]
@Quentin-M specifically which component? API server, yes, it should, can run more manual tests to verify.

**Comment by derekparker** [comment]
@Quentin-M actually, yes it will, we have checkpointing and such. Same as how it already worked on single masters.

**Comment by sym3tri** [comment]
failed during destroy. re-triggered.

**Comment by derekparker** [comment]
@sym3tri still red, didn't seem to re-trigger, or just failed fast for some reason. Still can't see output.

**Comment by sym3tri** [comment]
somehow `git clone` was failing in jenkins. seems ok now.

**Comment by s-urbaniak** [comment]
retriggered build, seems green enough for me.

**Comment by sym3tri** [comment]
@Quentin-M please review

**Pull request merged**
