### PR TITLE
config.tf: bump kvo, node-agent, and tco versions.

### PR DESCRIPTION
**Pull request by diegs**
- kvo: v1.7.5-kvo.5
- node-agent: v1.7.5-kvo.3
- tco: v0.5.4

Also regenerate the update payload to match.

### CODE REVIEW

**Comment by diegs** [comment]
test upgrade from 1.7.3-tectonic.2 1.7.3-tectonic.2

**Comment by diegs** [comment]
`Timed out waiting for Tectonic Console`

**Comment by diegs** [comment]
test upgrade from 1.7.3-tectonic.2 1.7.3-tectonic.2

**Comment by diegs** [comment]
```
Error applying plan:

1 error(s) occurred:

* aws_s3_bucket.tectonic: 1 error(s) occurred:

* aws_s3_bucket.tectonic: Error creating S3 bucket: TooManyBuckets: You have attempted to create more buckets than allowed
	status code: 400, request id: E4665A978FAE0E4E, host id: 40y7W5jNdBygLf2UktpGKYDjCJECN3Rr98EHaT90KQUcZLbTcp8lHd52x32m+6hRFgHUhC2x+Zc=
```

Will try again tomorrow.

**Comment by yifan-gu** [comment]
test upgrade from 1.7.3-tectonic.2 1.7.3-tectonic.2

**Comment by yifan-gu** [comment]
Upgrade test passed, trying from older versions as well.

**Comment by yifan-gu** [comment]
test upgrade from 1.7.1-tectonic.1 1.7.1-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.7.1-tectonic.1 1.7.1-tectonic.1

**Comment by diegs** [comment]
Will redo this PR to upgrade to kvo `v1.7.5-kvo.2` once that is ready.

**Comment by diegs** [comment]
test upgrade from 1.7.3-tectonic.2 1.7.3-tectonic.2

**Comment by diegs** [comment]
test upgrade from 1.7.3-tectonic.2 1.7.3-tectonic.2

**Comment by diegs** [comment]
test upgrade from 1.7.3-tectonic.2 1.7.3-tectonic.2

**Comment by sudhaponnaganti** [comment]
@diegs  - would you be able to resolve the conflicts?

**Comment by diegs** [comment]
test upgrade from 1.7.3-tectonic.2 1.7.3-tectonic.2

**Comment by diegs** [comment]
@sudhaponnaganti resolved conflicts

**Comment by diegs** [comment]
well, upgrade tests won't work without an update payload IIUC

**Comment by sudhaponnaganti** [comment]
Due to permission issues not able to see failed checks jenks/upgrade-test. Will review it with Quentin and proceed.

**Pull request merged**
