### PR TITLE
config.tf: Update console to v2.6.3

### PR DESCRIPTION
**Pull request by yifan-gu**
Bump console to v2.6.3

/cc @ggreer

### CODE REVIEW

**Comment by yifan-gu** [comment]
test upgrade from 1.7.9-tectonic.3 -1.7.9-tectonic.3

**Comment by yifan-gu** [comment]
test upgrade from 1.7.9-tectonic.3 -1.7.9-tectonic.3

**Comment by cpanato** [comment]
ok to test

**Comment by sudhaponnaganti** [comment]
@yifan-gu @ggreer - tests are failing. But I guess this is in 1.8.4 already. Need to resolve for master

**Comment by yifan-gu** [comment]
Close as 2.6.4 is cut.

**Pull request closed without merging**
