### PR TITLE
config.tf: update tectonic versions

### PR DESCRIPTION
**Pull request by squat**
cc @amrutac @Quentin-M @kans

### CODE REVIEW

**Comment by squat** [comment]
ok to test

**Comment by squat** [comment]
@kans had to rebase off master to get tests to pass. can you PTAL again?

**Comment by s-urbaniak** [comment]
ok to test

**Comment by squat** [comment]
One of the tests timed out. Retesting.

**Comment by squat** [comment]
ok to test

**Comment by kans** [comment]
@squat 

Just merge it.

**Pull request merged**
