### PR TITLE
.gitignore: Ignore generated files

### PR DESCRIPTION
**Pull request by lblackstone**

### CODE REVIEW

**Comment by lblackstone** [comment]
Just noticed that this duplicates https://github.com/coreos/tectonic-installer/pull/556

Use `make apply` puts the `generated/` directory under `build/`, but it gets added to the current directory if `terraform apply ...` is run manually as documented in the [OpenStack Readme](https://github.com/coreos/tectonic-installer/blob/master/Documentation/install/openstack/openstack-terraform.md#deploy-the-cluster)

**Comment by s-urbaniak** [comment]
I agree the readme can be enhanced in this regard, one paragraph earlier we state to create build/${cluster} but omit to describe to cd into it, see https://github.com/coreos/tectonic-installer/blob/master/Documentation/install/openstack/openstack-terraform.md#customize-the-deployment.

**Comment by lblackstone** [comment]
@s-urbaniak Does this look ok, or should I close the PR?

**Comment by s-urbaniak** [comment]
@lblackstone just went through the backlog, I suggest to close it tbh as we would like users to use `build` which is ignored.

**Pull request closed without merging**
