### PR TITLE
tnc-config: Fix typo in the config.

### PR DESCRIPTION
**Pull request by yifan-gu**
See:

https://github.com/coreos-inc/tectonic-operators/blob/master/controller/node/pkg/types/config.go#L13
https://github.com/coreos-inc/tectonic-operators/blob/master/controller/node/pkg/types/config.go#L20

### CODE REVIEW

**Comment by yifan-gu** [comment]
cc @enxebre @thorfour @abhinavdahiya

**Comment by yifan-gu** [comment]
retest this please

**Comment by enxebre** [comment]
doesn't this requires to build and point to a new docker image? or is that version of the golang code in the links included in the one currently used by config.tf?

**Comment by yifan-gu** [comment]
@enxebre Yeah, these are the correct values used by the image that's defined in the config.tf

**Comment by yifan-gu** [comment]
retest this please

**Comment by yifan-gu** [comment]
I believe the failure is not related to the PR itself
```
Error: Error applying plan:

1 error(s) occurred:

* aws_route53_record.tectonic_tnc: 1 error(s) occurred:

* aws_route53_record.tectonic_tnc: [ERR]: Error building changeset: InvalidChangeBatch: RRSet of type CNAME with DNS name awsbas-pr-3127-5c0052-tnc.tectonic-ci.de. is not permitted as it conflicts with other records with the same DNS name in zone tectonic-ci.de.
	status code: 400, request id: e3b24fe7-2c80-11e8-99b7-430c9c1f3614
```

Same error happens for https://github.com/coreos/tectonic-installer/pull/3126

**Comment by enxebre** [comment]
retest this please

**Pull request merged**
