### PR TITLE
monitoring: bump TPO to v1.5.0

### PR DESCRIPTION
**Pull request by Quentin-M**
This bumps the TPO to `v1.5.0`, which includes the TPR->CRD migration for the `AppVersion` objects.

Note: this _needs to_ land in the next release, but should be low risk as the TPO's functionality didn't change in this release, just the TPR->CRD migration was implemented by bumping the vendored dependencies.

@fabxc @pst @alexsomesan @s-urbaniak 

/cc @robszumski

### CODE REVIEW

**Comment by yifan-gu** [comment]
test upgrade from 1.7.1-tectonic.2 1.7.1-tectonic.2

**Comment by Quentin-M** [comment]
ok to test

**Comment by Quentin-M** [comment]
retest this please

**Comment by Quentin-M** [comment]
This passed all the smoke tests ..... wait wat? O_O'

**Comment by yifan-gu** [comment]
@Quentin-M Need a rebase. Also the test failure shows a tco bug. I am fixing it.

**Comment by Quentin-M** [comment]
Closed for https://github.com/coreos/tectonic-installer/pull/1740 due to GH permission issue..

**Comment by Quentin-M** [comment]
@yifan-gu for some reason, GitHub now refuses my force push to that branch. It probably lost track of contributor permissions since this is not the original PR from @brancz but a re-PR to a different target. I will create a third-one therefore..

**Pull request closed without merging**
