### PR TITLE
Bump Tectonic Console to v6.0.5 for 1.9.6.

### PR DESCRIPTION
**Pull request by coverprice**
Cherry-pick of #3194

### CODE REVIEW

**Comment by coverprice** [comment]
ok to test

**Comment by yifan-gu** [comment]
@coverprice `v1.9.6-kvo.4` is out for kvo

**Comment by yifan-gu** [comment]
test upgrade from 1.8.9-tectonic.2 1.8.9-tectonic.2

**Comment by coverprice** [comment]
There are failing aws/basic tests, but these passed in previous runs so I'm going to put that down to a flakey test.

**Pull request merged**
