### PR TITLE
tests/ci: add upstream-terraform-trigger as jenkins script

### PR DESCRIPTION
**Pull request by cpanato**
this fixes https://github.com/coreos/tectonic-installer/issues/1559

waiting for #1444 to be merged then I can update this PR to remove some unnecessary files.

cc @mxinden @squat

### CODE REVIEW

**Comment by mxinden** [comment]
@cpanato #1444 is merged now. Is there anything else here we need to wait for?

**Comment by cpanato** [comment]
@mxinden I will rebase then we can merge and delete the old job

**Comment by cpanato** [comment]
@mxinden rebased

**Comment by mxinden** [comment]
@cpanato Can you update the PR to remove the [upstream-terraform-trigger.groovy](https://github.com/coreos/tectonic-installer/blob/master/upstream-terraform-trigger.groovy)?

**Comment by cpanato** [comment]
done @mxinden

**Comment by cpanato** [comment]
when we merge this we need delete the old jenkins job

**Comment by mxinden** [comment]
@cpanato Let's please not delete the old *terraform-upstream* Jenkins job, because we still want to analyse the test results.

**Comment by cpanato** [comment]
@mxinden reverted

**Comment by mxinden** [comment]
I have deactivated the old job. I have run the Jenkins seed job. Looks good. Running right now here: https://jenkins-tectonic-installer.prod.coreos.systems/job/tectonic-installer/job/master/82/console

**Pull request merged**
