### PR TITLE
test: add new argument to logstash

### PR DESCRIPTION
**Pull request by cpanato**

### CODE REVIEW

**Comment by cpanato** [comment]
retest this please. on aws

**Comment by mxinden** [comment]
@erikkn Is this needed for the *amount-of-started-clusters* graph? Why not just count the number of ['HOORAY! The cluster is up'](https://github.com/coreos/tectonic-installer/blob/master/tests/rspec/lib/cluster.rb#L242) in a given timeframe?

**Comment by erikkn** [comment]
@mxinden , you are right, we can use this line to create a visualization. I discussed this with Carlos as well, and I think that we could still use this attribute to create something useful. I'll update the Jira ticket and let's discuss this when you are back.
Status: Let's keep the PR open until Max is back

**Comment by cpanato** [comment]
@mxinden @erikkn  should we merge this? or this makes no sense?

**Comment by erikkn** [comment]
Discussed this with Max and we actually don't need this PR. Closing PR.

**Pull request closed without merging**
