### PR TITLE
platforms/*: Fix variable duplication

### PR DESCRIPTION
**Pull request by lander2k2**
An old commit got overlaid during a rebase (I think) which caused proxy variables to be duplicated.  This fixes that.

@kalmog

### CODE REVIEW

**Comment by cpanato** [comment]
How about govcloud? this change does not apply on that? @enxebre  @lander2k2  @kalmog

**Comment by enxebre** [comment]
@cpanato @lander2k2 @kalmog This PRs address some inconsistencies missed for govcloud in this regard https://github.com/coreos/tectonic-installer/pull/2764 https://github.com/coreos/tectonic-installer/pull/2759 We need to make sure we keep it aligned for follow ups. Note that at the moment govcloud has it's own platform/govcloud and own modules/govcloud for etcd, masters and workers

**Comment by cpanato** [comment]
ok to test

**Comment by cpanato** [comment]
one test in aws failed. retest this please. AWS only

**Comment by cpanato** [comment]
saw these errors:

```
  Getting source "../../modules/tls/kube/user-provided"

Error getting plugins: 2 problems:


- module "masters": missing required argument "ign_profile_env_id"

- module "workers": missing required argument "ign_profile_env_id"

make: *** [terraform-init] Error 1
```

@lander2k2 @kalmog @enxebre

**Comment by kalmog** [comment]
duplicate of #2767

**Pull request closed without merging**
