### PR TITLE
modules/aws/vpc - Better security for master nodes

### PR DESCRIPTION
**Pull request by mrwacky42**
For a VPC with master nodes in a public subnet, they are reachable
from the entire internet. Usually, one will communicate with them via
an ELB, and not directly. This change limits access to 80/443 TCP and
ICMP to only nodes within the VPC and cluster.

### CODE REVIEW

**Comment by squat** [comment]
@mrwacky42 IMO this is actually not a good idea. Connections via an ELB are understandably loadbalanced across all the pool nodes. Thus, SSHing through a loadbalancer typically results in broken SSH connections after a few minutes. You should always SSH either:
1. directly into a master node; or
2. via a designated, non-loadbalanced jumpbox/bastion host.

We intend to add support for the second option very soon to address your concerns.

Closing for now.

**Comment by mrwacky42** [comment]
@squat  - I think you misunderstand the purpose of this PR, or I misunderstand your response.

Currently, any IP on the entire internet can connect to the master public IP addresses. We see lots of attempts at SSH brute forcing, and I can assume others are attempting to attack the API servers on port 80/443.

As far as I can tell, nothing external to the cluster talks directly to port 80/443 on the master nodes. This change limits the security group to only the VPC CIDR network. This grants access to:
* AWS for the purpose of load balancing
* Things inside the cluster

We have configured our test cluster this way to reduce our attack surface.

**Comment by squat** [comment]
Ah sorry rereading this now I see that I misunderstood this PR as limiting SSH, rather than http/https. Sure this could definitely make sense. However, the ELB forwards all requests to the API servers, so how much better is this really?

**Comment by mrwacky42** [comment]
It's better because we limit access to the API with security groups attached to the ELB!
😀

**Comment by mxinden** [comment]
We did some changes (https://github.com/coreos/tectonic-installer/pull/2082) to the testing process. Please rebase on to current master, so that the `basic-tests` PR status is reported correctly.

**Comment by mrwacky42** [comment]
*rebased*

**Comment by enxebre** [comment]
retest this please

**Comment by enxebre** [comment]
retest this please

**Comment by enxebre** [comment]
retest this please

**Pull request merged**
