### PR TITLE
tests/ci: convert tectonic-release as jenkins job code

### PR DESCRIPTION
**Pull request by cpanato**
Create the jenkins code for the tectonic-release job

cc @mxinden

### CODE REVIEW

**Comment by mxinden** [comment]
@cpanato Like discussed for https://github.com/coreos/tectonic-installer/pull/1564, could you check if we can use just the `script` keyword, without parsing a string or loading an additional Groovy file.

**Comment by mxinden** [comment]
//CC @Quentin-M any objections against moving this job to a Jenkins Job DSL Groovy script?

**Comment by Quentin-M** [comment]
@mxinden As long as it still continues to operate normally until the release process is extracted out of this repository - so we can still do releases, all good 👍

**Comment by cpanato** [comment]
@mxinden @Quentin-M ok :)

**Comment by cpanato** [comment]
oh wait, @Quentin-M the idea is remove this job out from this jenkins? if this is the idea I will close this PR and will keep the job as is today.

**Comment by Quentin-M** [comment]
@cpanato Yeah, everything is going to change.

**Comment by cpanato** [comment]
closing this because the job will be removed from tectonic-installer jenkins

**Pull request closed without merging**
