### PR TITLE
Bump TCO to allow minor version upgrade to 1.7.

### PR DESCRIPTION
**Pull request by yifan-gu**
PR against 1.6.7 branch.

/cc @robszumski @aaronlevy @diegs @Quentin-M @rithujohn191

### CODE REVIEW

**Comment by alexsomesan** [comment]
test this please

**Comment by alexsomesan** [comment]
retest this please

**Comment by alexsomesan** [comment]
retest this please

**Comment by alexsomesan** [comment]
@yifan-gu this change is based on a pretty old master. That's the reason for the CI failure - builder Docker image is an old one with known flaws.

I've tried rebasing it and it's quite a big diff. It might be more effective if you start from current master again and just cherry-pick this onto it.

**Comment by Quentin-M** [comment]
@yifan-gu Could you make that PR to master, then we can get that one in too (or I can do the cherry-pick myself if necessary).

**Comment by yifan-gu** [comment]
test upgrade from 1.6.7-tectonic.1

**Comment by yifan-gu** [comment]
@alexsomesan But a PR to master will have a different payload generation result.

**Comment by yifan-gu** [comment]
test upgrade from 1.6.7-tectonic.1

**Comment by yifan-gu** [comment]
test upgrade from 1.6.6-tectonic.1

**Pull request merged**
