### PR TITLE
Fix terraform resource churn

### PR DESCRIPTION
**Pull request by mrwacky42**
Possibly related to this issue with the Terraform AWS provider:
terraform-providers/terraform-provider-aws#1521

Terraform or the AWS API report `0` IOPS for `gp2` volumes after creation.
If I create a `gp2` volume with these modules, every subsequent run of
Terraform will attempt to destroy and recreate the LC in order to make
IOPs match. This change sets IOPS to 0 for non-`io1` type volumes.

Since the number of IOPS for `gp2` volume is based on the size, Terraform
arguably should only accept the `iops` parameter for `io1` volumes.

Interestingly, for the etcd nodes, this problem does not occur because
the Terraform state shows 100 IOPS even for `gp2` volumes.

### CODE REVIEW

**Comment by squat** [comment]
@mrwacky42 this generally looks pretty good but seems fragile. Why not update the etcd node launch config as well? And what happens when that node's IOPs in Terraform state is no longer 100?

**Comment by mrwacky42** [comment]
@squat - I based this change on the current behavior of Terraform and AWS.

The etcd nodes are not using autoscaling, so there is no launch configuration, just `aws_instance` resources. 

For `aws_instance` resources, Terraform state currently reports `100` iops (for non-`io1` EBS volumes). For `aws_launch_configuration` resources, Terraform state currently reports `0` iops.

There is a PR attached to the original issue I linked above to fix the `aws_instance` to behave consistent with `aws_launch_configuration`: https://github.com/terraform-providers/terraform-provider-aws/pull/1573

**Comment by squat** [comment]
thank I see now. From the issue you linked, it looks like even settings iops to 100 for gp2 volumes will not always work. @fraenkel writes that for large volume sizes the iops can be reported to be 150, so we may still have resource churn.

**Comment by squat** [comment]
As @mrwacky42 correctly, notes, iops defaults to 0 for gp2 volumes in launch configurations, but defaults to size/3 for instance resources. This rcplsind why @simnalamburt was seeing the issue in https://github.com/coreos/tectonic-installer/pull/1397#issuecomment-317329260 for only the volumes used in launch configurations but not the volumes used etcd nodes. This PR partially undoes https://github.com/coreos/tectonic-installer/pull/1397. We should merge https://github.com/coreos/tectonic-installer/pull/953 next to ensure that iops is set correctly for volumes in instance resources.

**Comment by squat** [comment]
closing and reopening to trigger tests

**Comment by squat** [comment]
ok to test

**Comment by squat** [comment]
@mrwacky42 This is failing with:
```
misformatted files (run 'terraform fmt .' to fix): platforms/aws/variables.tf
```
can you please fix the formatting?

**Comment by mrwacky42** [comment]
*pushes a fixed commit*

**Comment by squat** [comment]
@mrwacky42 no, rebasing was good :+1:. Linting is still failing. Can you please `make docs && make examples` and commit the result?

**Comment by mrwacky42** [comment]
I cheated and ran `make docs examples`, then rebased again.

😀

**Comment by squat** [comment]
@mrwacky42 had an unrelated flake in one of the azure tests. Merging!

**Pull request merged**
