### PR TITLE
config.tf, payload.json: Bump TCO to 0.4.0.

### PR DESCRIPTION
**Pull request by yifan-gu**
CHANGELOG:
- Add support to get a specific version of payload
- Add support to list all payloads in order
- Bump operator client
- Refactor on TCO and allow TCO to upgrade through every intermediate versions
- Allow TCO to upgrade across minor versions

### CODE REVIEW

**Comment by yifan-gu** [comment]
Update would fail, blocked on a new KVO release, which is blocked on https://github.com/coreos-inc/kube-version-operator/pull/200

**Comment by Quentin-M** [comment]
This PR only contains the payload. The TCO bump was merged in https://github.com/coreos/tectonic-installer/pull/1522. Thus, merging.

**Comment by diegs** [comment]
Hey, well at least we got the CHANGELOG :)

**Pull request merged**
