### PR TITLE
azure/vnet: custom vnet error when using module

### PR DESCRIPTION
**Pull request by rossedman**
Prevents issue where when providing an external vnet id errors are thrown

### CODE REVIEW

**Comment by rossedman** [comment]
If providing custom VNet ID this error is provided:

```
* module.kubernetes.module.vnet.azurerm_virtual_network.tectonic_vnet: azurerm_virtual_network.tectonic_vnet: value of 'count' cannot be computed
```

**Comment by squat** [comment]
ok to test

**Comment by squat** [comment]
@rossedman does this really fix the error?

**Comment by squat** [comment]
Regardless, it is a good change to get in.

**Comment by rossedman** [comment]
@squat blah didn't fix. will look into it more. 😢

**Comment by squat** [comment]
That’s unfortunately what I expected. We’ll have to dig into this

**Pull request merged**
