### PR TITLE
Cluster config: mark a few vars that have defaults as (optional)

### PR DESCRIPTION
**Pull request by alexsomesan**
With this change, the affected variables will be included in the autogenerated example as comments only.

I think this better instructs users that these are not required and should focus them more on the required ones.

### CODE REVIEW

**Comment by alexsomesan** [comment]
retest this please

**Comment by squat** [comment]
@alexsomesan sorry, tests are failing because of fmt. Fix: #1727

**Comment by squat** [comment]
retest this please

**Comment by squat** [comment]
Good, it's getting further now. We just need to `make docs`

**Comment by s-urbaniak** [comment]
@alexsomesan CI failure says:
```
outdated docs (run 'make docs' to fix)
Makefile:130: recipe for target 'structure-check' failed
```

**Comment by cpanato** [comment]
Flaky test :/

**Comment by cpanato** [comment]
@squat @s-urbaniak could you guys please review when having some time? thanks!

**Comment by alexsomesan** [comment]
retest this please

**Pull request merged**
