### PR TITLE
Reconcile

### PR DESCRIPTION
**Pull request by enxebre**
Merge master into ut2-integration

### CODE REVIEW

**Comment by enxebre** [comment]
cc @alexsomesan @squat

**Comment by squat** [comment]
@enxebre looks like tests are red because bazel build is failing after the rebase

**Comment by enxebre** [comment]
@squat `'//:platforms/aws/variables.tf': target 'platforms/aws/variables.tf' not declared in package`
should change the variables.bzl to `PLATFORMS["aws"] = "//:steps"` just work?

**Comment by enxebre** [comment]
@squat PTAL https://github.com/coreos/tectonic-installer/pull/2953/commits/839b2b89bc72510559aaecba5430762ddfd9b851

**Comment by enxebre** [comment]
the tectonic binary still does not get generated :/

**Comment by alexsomesan** [comment]
retest this please

**Comment by enxebre** [comment]
seems some go deps are missing:
```
 	installer/pkg/workflow/utils.go: import of k8s.io/client-go/kubernetes, which is not a direct dependency
	installer/pkg/workflow/utils.go: import of k8s.io/client-go/tools/clientcmd, which is not a direct dependency
```

**Comment by enxebre** [comment]
Should be good now

**Pull request merged**
