### PR TITLE
platforms,modules: Add metal "profiles" module

### PR DESCRIPTION
**Pull request by dghubble**
* Move bare-metal profiles into a Terraform module (similar to upstream matchbox profiles https://github.com/coreos/matchbox/tree/master/examples/terraform#modules)
* Rename `coreos-install` to `cached-container-linux-install` profile
* Add a `container-linux-install` profile users can manually switch to if they prefer to pull images from the public site (slower)

### CODE REVIEW

**Comment by Quentin-M** [comment]
I'd like to see the move to modules/ happen :)

**Comment by dghubble** [comment]
Yeah, I'm hoping to give this another go this week and possibly re-write this. https://github.com/coreos/matchbox/tree/master/examples/terraform/bootkube-install has proven out some of my thinking on how to structure it.

**Comment by sym3tri** [comment]
bump.
@dghubble are you still working on this? No activity for 3 weeks. close?

**Comment by dghubble** [comment]
I commented 6 days ago, I think it'll be a fresh PR though. This draft is well out of date.

**Pull request closed without merging**
