### PR TITLE
digitalocean: Add support for DigitalOcean 

### PR DESCRIPTION
**Pull request by kalmog**
rebase of #2862 on top of branch 1.8.7

This extends Tectonic Installer to also support the DigitalOcean cloud
provider.

### CODE REVIEW

**Comment by aknuds1** [comment]
Yay!!

**Comment by kalmog** [comment]
smoke tests: running metal

**Comment by kalmog** [comment]
retest this please

**Comment by kalmog** [comment]
metal is green. testing azure.
retest this please.

**Comment by cpanato** [comment]
retest this please. `metal/azure` are green. testing `aws`.

**Comment by kalmog** [comment]
Retest this please. Govcloud

**Comment by aknuds1** [comment]
🎉 🙌

**Comment by aknuds1** [comment]
@kalmog Will I be credited for implementing DigitalOcean support in the release notes?

**Comment by cpanato** [comment]
this is a question for @robszumski

**Comment by robszumski** [comment]
As this is pre-alpha, we're gonna start with a post to the coreos-users mailing list with an announcement, known limitations, etc. I want to you get all the credit for this, you deserve it!

**Comment by aknuds1** [comment]
Thanks @robszumski! :)

**Comment by ggreer** [comment]
This PR adds broken bazel symlinks: https://github.com/coreos/tectonic-installer/commit/bc6c0bc36a#diff-9f1ea139e996d7cc11b88667b6712296

**Comment by squat** [comment]
Yeah that’s definitely wrong. I can push a fix for it @ggreer

**Pull request merged**
