### PR TITLE
server: Calculate tectonic_kube_etcd_service_ip from service CIDR.

### LINKED ISSUE #535: ETCD Self-hosted Operator doesn't use custom cluster CIDRs
Version: 1.6.2
Installation Method: AWS Terraform

Expected Results: If non-standard Pod and Service CIDRs are entered into the Web UI the self-hosted ETCD operator would create the ETCD services using the defined CIDR to determine the proper ClusterIP of the service.

Observed Results: When non-standard Pod and Service CIDR's are entered into the Web UI the self-hosted ETCD operator attempts to create the ETCD service using a default value for the ClusterIP of `10.3.0.15`
```
May 03 23:43:52 ip-10-252-227-66 bash[6936]: [ 1670.453676] bootkube[5]: E0503 23:43:52.116072       5 create.go:34] Error creating assets: error when creating "/assets/manifests/etcd-service.yaml": Service "etcd-service" is invalid: spec.clusterIP: Invalid value: "10.3.0.15": provided IP is not in the valid range
May 03 23:43:52 ip-10-252-227-66 bash[6936]: [ 1670.453941] bootkube[5]: Error creating assets: error when creating "/assets/manifests/etcd-service.yaml": Service "etcd-service" is invalid: spec.clusterIP: Invalid value: "10.3.0.15": provided IP is not in the valid range
May 03 23:43:52 ip-10-252-227-66 bash[6936]: [ 1670.454225] bootkube[5]: NOTE: Bootkube failed to create some cluster assets. It is important that manifest errors are resolved and resubmitted to the apiserver.
May 03 23:43:52 ip-10-252-227-66 bash[6936]: [ 1670.454495] bootkube[5]: For example, after resolving issues: kubectl create -f <failed-manifest>
```

Additional Info:
 "podCIDR": "172.16.0.0/16",
 "serviceCIDR": "192.168.128.0/20",

### PR DESCRIPTION
**Pull request by ggreer**
Fixes #535.

### CODE REVIEW

**Comment by ggreer** [comment]
I booted a cluster using a pod CIDR of 172.16.0.0/16 and a service CIDR of 192.168.128.0/20.

**Comment by sym3tri** [comment]
@ggreer did you also enable experimental operators and validate the etcd cluster IP?

**Comment by ggreer** [comment]
No I did not. Retrying.

**Comment by sym3tri** [comment]
code LGTM once a tests is confirmed

**Comment by ggreer** [comment]
OK, booted a cluster with experimental operators enabled and non-default pod & service CIDRs.

**Pull request merged**
