### PR TITLE
platform/*: trigger bootkube/tectonic via path unit

### PR DESCRIPTION
**Pull request by lucab**
This removes the need for the last ssh command to the bootkubing
master, which was triggering/running the bootkube/tectonic service
manually in a synchronous way.
This allows for the bootkubing process to be carried-on across
reboots and other failures. The new bootkube trigger is based
on the existence of the shell scripts in /opt.

---

This just updates platform/metal, @s-urbaniak will take over for the other platforms (INST-224). Remaining tasks for this PR:
 * [x] move bootkube/tectonic service+path content to ~~`modules/ignition`~~ `modules/bootkube` and `modules/tectonic` (as discussed OOB we decided against putting them in the ignition module, but rather in their respective modules.
 * [x] switch metal bootkubing to use `modules/bootkube`/`modules/tectonic`
 * [x] update aws to use path units
 * [x] update azure to use path units
 * [x] update vmware to use path units
 * [x] update openstack to use path units
 * [x] run tests on the whole result (local preliminary test on metal is green)

### CODE REVIEW

**Comment by lucab** [comment]
This is currently based on https://github.com/coreos/tectonic-installer/pull/1824, which is pending review.

**Comment by cpanato** [comment]
can we squash some commits?

**Comment by cpanato** [comment]
saw this error in the bare metal test:
```
+ make apply
Using build directory [/jenkins/workspace/tectonic-installer_PR-1852-KDETDJFCNXFUYVJHUBOHMAV3ZZVWPB73QBNYJKU2B7M7VI75QEBQ/build/tf-metal-PR-1852-6]
mkdir -p /jenkins/workspace/tectonic-installer_PR-1852-KDETDJFCNXFUYVJHUBOHMAV3ZZVWPB73QBNYJKU2B7M7VI75QEBQ/build/tf-metal-PR-1852-6/terraform.d/plugins/linux_amd64
ln -s /jenkins/workspace/tectonic-installer_PR-1852-KDETDJFCNXFUYVJHUBOHMAV3ZZVWPB73QBNYJKU2B7M7VI75QEBQ/installer/bin/linux/terraform-provider-* /jenkins/workspace/tectonic-installer_PR-1852-KDETDJFCNXFUYVJHUBOHMAV3ZZVWPB73QBNYJKU2B7M7VI75QEBQ/build/tf-metal-PR-1852-6/terraform.d/plugins/linux_amd64
cd /jenkins/workspace/tectonic-installer_PR-1852-KDETDJFCNXFUYVJHUBOHMAV3ZZVWPB73QBNYJKU2B7M7VI75QEBQ/build/tf-metal-PR-1852-6 && terraform init  /jenkins/workspace/tectonic-installer_PR-1852-KDETDJFCNXFUYVJHUBOHMAV3ZZVWPB73QBNYJKU2B7M7VI75QEBQ/platforms/metal
Downloading modules...
Get: file:///jenkins/workspace/tectonic-installer_PR-1852-KDETDJFCNXFUYVJHUBOHMAV3ZZVWPB73QBNYJKU2B7M7VI75QEBQ/modules/ignition
Get: file:///jenkins/workspace/tectonic-installer_PR-1852-KDETDJFCNXFUYVJHUBOHMAV3ZZVWPB73QBNYJKU2B7M7VI75QEBQ/modules/ignition
Get: file:///jenkins/workspace/tectonic-installer_PR-1852-KDETDJFCNXFUYVJHUBOHMAV3ZZVWPB73QBNYJKU2B7M7VI75QEBQ/modules/bootkube
Get: file:///jenkins/workspace/tectonic-installer_PR-1852-KDETDJFCNXFUYVJHUBOHMAV3ZZVWPB73QBNYJKU2B7M7VI75QEBQ/modules/tectonic
Get: file:///jenkins/workspace/tectonic-installer_PR-1852-KDETDJFCNXFUYVJHUBOHMAV3ZZVWPB73QBNYJKU2B7M7VI75QEBQ/modules/net/flannel-vxlan
Get: file:///jenkins/workspace/tectonic-installer_PR-1852-KDETDJFCNXFUYVJHUBOHMAV3ZZVWPB73QBNYJKU2B7M7VI75QEBQ/modules/net/calico-network-policy
Error getting plugins: module root: 
    resource 'matchbox_group.controller' config: systemd_path_unit is not a valid output for module bootkube
    resource 'matchbox_group.controller' config: systemd_service is not a valid output for module bootkube
Makefile:37: recipe for target 'terraform-init' failed
make: *** [terraform-init] Error 1

```

**Comment by s-urbaniak** [comment]
@cpanato it most certainly is, thanks! looking into it.

**Comment by s-urbaniak** [comment]
fixed CI failure, build was all green but somehow github was left in the "building" (orange) state.

**Comment by lucab** [comment]
@s-urbaniak thanks for finalizing this!

**Pull request merged**
