### PR TITLE
frontend/tests: Add Nightwatch navigation tests & more test clean up

### PR DESCRIPTION
**Pull request by kyoto**
Write a single test function in `wizard.js` that runs the tests that are common to every page.
- Remove all the duplicate nextStep definitions and actions.
- Pass the input JSON to each page's test function so they don't all need to build the JSON themselves.

Add tests for the Previous / Next buttons and sidebar links.

Split page tests into separate Nightwatch steps to make it easier to read the output.

Other clean up.

### CODE REVIEW

**Comment by ggreer** [comment]
ok to test

**Comment by ggreer** [comment]
These tests pass locally for me, but [fail in jenkins with odd errors](https://jenkins-tectonic-installer.prod.coreos.systems/blue/organizations/jenkins/tectonic-installer/detail/PR-1762/4/pipeline/70#step-268-log-317). I'm not sure why, but I didn't look into it much.

**Comment by kyoto** [comment]
ok to test

**Comment by kyoto** [comment]
ok to test

**Comment by cpanato** [comment]
Fix the Jenkins side, all tests are green now

**Pull request merged**
