### PR TITLE
bump tf aws provider to 1.7.0

### PR DESCRIPTION
**Pull request by enxebre**
bump tf aws provider to 1.7.0

### CODE REVIEW

**Comment by squat** [comment]
ok to test

**Comment by enxebre** [comment]
@squat govcloud doesn't like the new version, let me dig into this before triggering again

**Comment by squat** [comment]
@enxebre I saw timeouts on the destroy causing the failures.

**Comment by enxebre** [comment]
retest this please

**Comment by enxebre** [comment]
retest this please

**Pull request merged**
