### PR TITLE
Cherry pick PR 2954

### PR DESCRIPTION
**Pull request by sym3tri**
I forgot to apply my changes in https://github.com/coreos/tectonic-installer/pull/2954 to master

### CODE REVIEW

**Comment by sym3tri** [comment]
ok to test

**Comment by coverprice** [comment]
ok to test

**Comment by coverprice** [comment]
retest this please

**Comment by coverprice** [comment]
retest this please

**Comment by coverprice** [comment]
Last test run failed on azure/external_spec but it passed in a previous run, so I'm going to put that down to a flaky test and merge anyway.

**Pull request merged**
