### PR TITLE
config.tf: Update hyperkube+KVO for Kubernetes 1.6.10

### PR DESCRIPTION
**Pull request by rithujohn191**

### CODE REVIEW

**Comment by rithujohn191** [comment]
test upgrade from 1.6.8-tectonic.1 to 1.6.10-tectonic.1

**Comment by Quentin-M** [comment]
Smoke tests on the 1.6.x branch cannot run. Please ignore.

**Comment by rithujohn191** [comment]
test upgrade from 1.6.8-tectonic.1 to 1.6.8-tectonic.1

**Comment by rithujohn191** [comment]
test upgrade from 1.6.8-tectonic.1 to 1.6.8-tectonic.1

**Comment by rithujohn191** [comment]
test upgrade from 1.6.8-tectonic.1 1.6.8-tectonic.1

**Comment by rithujohn191** [comment]
Nope seeing failures

**Comment by Quentin-M** [comment]
Is someone looking into it?

**Comment by rithujohn191** [comment]
yes

**Comment by rithujohn191** [comment]
test upgrade from 1.6.8-tectonic.1 1.6.8-tectonic.1

**Comment by yifan-gu** [comment]
@Quentin-M Upgrade test failed last time because a `1.6.9` package was on the testing coreupdate server. I removed it now.

**Comment by diegs** [comment]
@yifan-gu TCO is downloading a `1.6.10` payload but still trying to upgrade to `1.6.9` and failing:

```
I0920 22:50:21.287528       1 main.go:97] Update check started
I0920 22:50:22.641359       1 main.go:144] Received TectonicVersion: &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name: GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} Version:1.6.10-tectonic.1 Deployments:[{TypeMeta:{Kind:Deployment APIVersion:extensions/v1beta1} ObjectMeta:{Name:tectonic-channel-operator GenerateName: Namespace:tectonic-system SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[k8s-app:tectonic-channel-operator managed-by-channel-operator:true] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} Spec:{Replicas:0xc420303f04 Selector:&LabelSelector{MatchLabels:map[string]string{k8s-app: tectonic-channel-operator,},MatchExpressions:[],} Template:{ObjectMeta:{Name: GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[tectonic-app-version-name:tectonic-cluster k8s-app:tectonic-channel-operator] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} Spec:{Volumes:[{Name:certs VolumeSource:{HostPath:&HostPathVolumeSource{Path:/usr/share/ca-certificates,} EmptyDir:nil GCEPersistentDisk:nil AWSElasticBlockStore:nil GitRepo:nil Secret:nil NFS:nil ISCSI:nil Glusterfs:nil PersistentVolumeClaim:nil RBD:nil FlexVolume:nil Cinder:nil CephFS:nil Flocker:nil DownwardAPI:nil FC:nil AzureFile:nil ConfigMap:nil VsphereVolume:nil Quobyte:nil AzureDisk:nil PhotonPersistentDisk:nil Projected:nil PortworxVolume:nil ScaleIO:nil StorageOS:nil}}] InitContainers:[] Containers:[{Name:tectonic-channel-operator Image:quay.io/coreos/tectonic-channel-operator:0.4.2 Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[{Name:CLUSTER_ID Value: ValueFrom:&EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:&ConfigMapKeySelector{LocalObjectReference:LocalObjectReference{Name:tectonic-config,},Key:clusterID,Optional:nil,},SecretKeyRef:nil,}}] Resources:{Limits:map[cpu:{i:{value:20 scale:-3} d:{Dec:<nil>} s:20m Format:DecimalSI} memory:{i:{value:52428800 scale:0} d:{Dec:<nil>} s:50Mi Format:BinarySI}] Requests:map[cpu:{i:{value:20 scale:-3} d:{Dec:<nil>} s:20m Format:DecimalSI} memory:{i:{value:52428800 scale:0} d:{Dec:<nil>} s:50Mi Format:BinarySI}]} VolumeMounts:[{Name:certs ReadOnly:false MountPath:/etc/ssl/certs SubPath:}] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath: TerminationMessagePolicy: ImagePullPolicy: SecurityContext:nil Stdin:false StdinOnce:false TTY:false}] RestartPolicy:Always TerminationGracePeriodSeconds:<nil> ActiveDeadlineSeconds:<nil> DNSPolicy: NodeSelector:map[] ServiceAccountName: DeprecatedServiceAccount: AutomountServiceAccountToken:<nil> NodeName: HostNetwork:false HostPID:false HostIPC:false SecurityContext:&PodSecurityContext{SELinuxOptions:nil,RunAsUser:*65534,RunAsNonRoot:*true,SupplementalGroups:[],FSGroup:nil,} ImagePullSecrets:[{Name:coreos-pull-secret}] Hostname: Subdomain: Affinity:nil SchedulerName: Tolerations:[] HostAliases:[]}} Strategy:{Type: RollingUpdate:nil} MinReadySeconds:0 RevisionHistoryLimit:<nil> Paused:false RollbackTo:nil ProgressDeadlineSeconds:<nil>} Status:{ObservedGeneration:0 Replicas:0 UpdatedReplicas:0 ReadyReplicas:0 AvailableReplicas:0 UnavailableReplicas:0 Conditions:[] CollisionCount:<nil>}} {TypeMeta:{Kind:Deployment APIVersion:extensions/v1beta1} ObjectMeta:{Name:container-linux-update-operator GenerateName: Namespace:tectonic-system SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[k8s-app:container-linux-update-operator managed-by-channel-operator:true] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} Spec:{Replicas:0xc4201c842c Selector:&LabelSelector{MatchLabels:map[string]string{k8s-app: container-linux-update-operator,},MatchExpressions:[],} Template:{ObjectMeta:{Name:container-linux-update-operator GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[k8s-app:container-linux-update-operator] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} Spec:{Volumes:[] InitContainers:[] Containers:[{Name:update-operator Image:quay.io/coreos/container-linux-update-operator:v0.2.1 Command:[/bin/update-operator] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[{Name:POD_NAMESPACE Value: ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}}] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath: TerminationMessagePolicy: ImagePullPolicy: SecurityContext:nil Stdin:false StdinOnce:false TTY:false}] RestartPolicy: TerminationGracePeriodSeconds:<nil> ActiveDeadlineSeconds:<nil> DNSPolicy: NodeSelector:map[] ServiceAccountName: DeprecatedServiceAccount: AutomountServiceAccountToken:<nil> NodeName: HostNetwork:false HostPID:false HostIPC:false SecurityContext:nil ImagePullSecrets:[] Hostname: Subdomain: Affinity:nil SchedulerName: Tolerations:[] HostAliases:[]}} Strategy:{Type: RollingUpdate:nil} MinReadySeconds:0 RevisionHistoryLimit:<nil> Paused:false RollbackTo:nil ProgressDeadlineSeconds:<nil>} Status:{ObservedGeneration:0 Replicas:0 UpdatedReplicas:0 ReadyReplicas:0 AvailableReplicas:0 UnavailableReplicas:0 Conditions:[] CollisionCount:<nil>}} {TypeMeta:{Kind:Deployment APIVersion:extensions/v1beta1} ObjectMeta:{Name:kube-version-operator GenerateName: Namespace:tectonic-system SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[k8s-app:kube-version-operator managed-by-channel-operator:true] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} Spec:{Replicas:0xc4201c884c Selector:&LabelSelector{MatchLabels:map[string]string{k8s-app: kube-version-operator,},MatchExpressions:[],} Template:{ObjectMeta:{Name: GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[k8s-app:kube-version-operator tectonic-app-version-name:kubernetes] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} Spec:{Volumes:[] InitContainers:[] Containers:[{Name:kube-version-operator Image:quay.io/coreos/kube-version-operator:v1.6.10-kvo.1 Command:[/kube-version-operator --cache-images=true --version-mapping=/upgrade-spec.json] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath: TerminationMessagePolicy: ImagePullPolicy: SecurityContext:nil Stdin:false StdinOnce:false TTY:false}] RestartPolicy: TerminationGracePeriodSeconds:<nil> ActiveDeadlineSeconds:<nil> DNSPolicy: NodeSelector:map[] ServiceAccountName: DeprecatedServiceAccount: AutomountServiceAccountToken:<nil> NodeName: HostNetwork:false HostPID:false HostIPC:false SecurityContext:&PodSecurityContext{SELinuxOptions:nil,RunAsUser:*65534,RunAsNonRoot:*true,SupplementalGroups:[],FSGroup:nil,} ImagePullSecrets:[{Name:coreos-pull-secret}] Hostname: Subdomain: Affinity:nil SchedulerName: Tolerations:[] HostAliases:[]}} Strategy:{Type: RollingUpdate:nil} MinReadySeconds:0 RevisionHistoryLimit:<nil> Paused:false RollbackTo:nil ProgressDeadlineSeconds:<nil>} Status:{ObservedGeneration:0 Replicas:0 UpdatedReplicas:0 ReadyReplicas:0 AvailableReplicas:0 UnavailableReplicas:0 Conditions:[] CollisionCount:<nil>}} {TypeMeta:{Kind:Deployment APIVersion:extensions/v1beta1} ObjectMeta:{Name:tectonic-etcd-operator GenerateName: Namespace:tectonic-system SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[k8s-app:tectonic-etcd-operator managed-by-channel-operator:true] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} Spec:{Replicas:0xc4201c8ccc Selector:&LabelSelector{MatchLabels:map[string]string{k8s-app: tectonic-etcd-operator,},MatchExpressions:[],} Template:{ObjectMeta:{Name: GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[k8s-app:tectonic-etcd-operator tectonic-app-version-name:tectonic-etcd] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} Spec:{Volumes:[] InitContainers:[] Containers:[{Name:tectonic-etcd-operator Image:quay.io/coreos/tectonic-etcd-operator:v0.0.1 Command:[/usr/local/bin/tectonic-etcd-operator] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[cpu:{i:{value:100 scale:-3} d:{Dec:<nil>} s:100m Format:DecimalSI} memory:{i:{value:134217728 scale:0} d:{Dec:<nil>} s: Format:BinarySI}] Requests:map[cpu:{i:{value:20 scale:-3} d:{Dec:<nil>} s:20m Format:DecimalSI} memory:{i:{value:52428800 scale:0} d:{Dec:<nil>} s:50Mi Format:BinarySI}]} VolumeMounts:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath: TerminationMessagePolicy: ImagePullPolicy: SecurityContext:nil Stdin:false StdinOnce:false TTY:false}] RestartPolicy:Always TerminationGracePeriodSeconds:<nil> ActiveDeadlineSeconds:<nil> DNSPolicy: NodeSelector:map[] ServiceAccountName: DeprecatedServiceAccount: AutomountServiceAccountToken:<nil> NodeName: HostNetwork:false HostPID:false HostIPC:false SecurityContext:&PodSecurityContext{SELinuxOptions:nil,RunAsUser:*65534,RunAsNonRoot:*true,SupplementalGroups:[],FSGroup:nil,} ImagePullSecrets:[{Name:coreos-pull-secret}] Hostname: Subdomain: Affinity:nil SchedulerName: Tolerations:[] HostAliases:[]}} Strategy:{Type: RollingUpdate:nil} MinReadySeconds:0 RevisionHistoryLimit:<nil> Paused:false RollbackTo:nil ProgressDeadlineSeconds:<nil>} Status:{ObservedGeneration:0 Replicas:0 UpdatedReplicas:0 ReadyReplicas:0 AvailableReplicas:0 UnavailableReplicas:0 Conditions:[] CollisionCount:<nil>}} {TypeMeta:{Kind:Deployment APIVersion:extensions/v1beta1} ObjectMeta:{Name:tectonic-prometheus-operator GenerateName: Namespace:tectonic-system SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[managed-by-channel-operator:true k8s-app:tectonic-prometheus-operator] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} Spec:{Replicas:0xc4201c91cc Selector:&LabelSelector{MatchLabels:map[string]string{k8s-app: tectonic-prometheus-operator,},MatchExpressions:[],} Template:{ObjectMeta:{Name: GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[k8s-app:tectonic-prometheus-operator tectonic-app-version-name:tectonic-monitoring] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} Spec:{Volumes:[] InitContainers:[] Containers:[{Name:tectonic-prometheus-operator Image:quay.io/coreos/tectonic-prometheus-operator:v1.3.0 Command:[] Args:[-logtostderr=true -v=4] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[cpu:{i:{value:20 scale:-3} d:{Dec:<nil>} s:20m Format:DecimalSI} memory:{i:{value:52428800 scale:0} d:{Dec:<nil>} s:50Mi Format:BinarySI}] Requests:map[cpu:{i:{value:20 scale:-3} d:{Dec:<nil>} s:20m Format:DecimalSI} memory:{i:{value:52428800 scale:0} d:{Dec:<nil>} s:50Mi Format:BinarySI}]} VolumeMounts:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath: TerminationMessagePolicy: ImagePullPolicy: SecurityContext:nil Stdin:false StdinOnce:false TTY:false}] RestartPolicy:Always TerminationGracePeriodSeconds:0xc4201c9720 ActiveDeadlineSeconds:<nil> DNSPolicy: NodeSelector:map[] ServiceAccountName: DeprecatedServiceAccount: AutomountServiceAccountToken:<nil> NodeName: HostNetwork:false HostPID:false HostIPC:false SecurityContext:&PodSecurityContext{SELinuxOptions:nil,RunAsUser:*65534,RunAsNonRoot:*true,SupplementalGroups:[],FSGroup:nil,} ImagePullSecrets:[{Name:coreos-pull-secret}] Hostname: Subdomain: Affinity:nil SchedulerName: Tolerations:[] HostAliases:[]}} Strategy:{Type: RollingUpdate:nil} MinReadySeconds:0 RevisionHistoryLimit:<nil> Paused:false RollbackTo:nil ProgressDeadlineSeconds:<nil>} Status:{ObservedGeneration:0 Replicas:0 UpdatedReplicas:0 ReadyReplicas:0 AvailableReplicas:0 UnavailableReplicas:0 Conditions:[] CollisionCount:<nil>}}] DesiredVersions:[{Name:kubernetes Version:1.6.10+tectonic.1} {Name: Version:0.0.1} {Name: Version:1.3.0}]}
E0920 22:50:40.142003       1 main.go:248] Failed to update to version "1.6.9-tectonic.1": failed to get payload for version "1.6.9-tectonic.1": signature validation failed: openpgp: invalid data: tag byte does not have MSB set
```

This happens repeatedly until the test times out.

**Comment by rithujohn191** [comment]
test upgrade from 1.6.8-tectonic.1 1.6.8-tectonic.1

**Comment by Quentin-M** [comment]
@rithujohn191 Except if the automated upgrade tests uses that script, it is not used anywhere in the repository anymore (and dropped from master).

**Comment by rithujohn191** [comment]
@yifan-gu said it should we used only for the 1.6 upgrades. Not sure if it needs to be in master

**Comment by rithujohn191** [comment]
```
 --- FAIL: TestUpgrade/after_upgrade (0.33s)
    	upgrade_test.go:131: failed to run kubectl: exit status 1, output: "error: resource name may not be empty\n"
```

is that an issue with the payload itself?

**Comment by yifan-gu** [comment]
test upgrade from 1.6.8-tectonic.1 1.6.8-tectonic.1

**Comment by rithujohn191** [comment]
Upgrade tests passed :) if someone could give me another LGTM...I'll ship it.

**Comment by Quentin-M** [comment]
test upgrade from 1.6.8-tectonic.1 1.6.8-tectonic.1

**Pull request merged**
