### PR TITLE
azure: add udev rules needed by k8s cloudprovider (#1618)

### PR DESCRIPTION
**Pull request by Quentin-M**
Cherry-picks https://github.com/coreos/tectonic-installer/pull/1618 in the 1.7.1 release branch.

### CODE REVIEW

**Comment by squat** [comment]
@Quentin-M we need to terraform fmt this. Otherwise looks good

**Comment by Quentin-M** [comment]
Oh gosh ... it got merged in https://github.com/coreos/tectonic-installer/pull/1618 with `do-no-test` and therefore it went through without any kind of testing, not even the `structure-check`...

**Comment by Quentin-M** [comment]
So the cherry-pick/conflict resolution broke it.. 👍 Good catch, thanks.

**Comment by squat** [comment]
Aghh it *did* get merged without the newline in one of the files. Grr

**Comment by Quentin-M** [comment]
Due to the `do-not-test` label..

**Comment by Quentin-M** [comment]
We good, just Azure failures due to subscription.

**Pull request merged**
