### PR TITLE
Bare metal - Replaced hyphens with underscores in .tf files

### PR DESCRIPTION
**Pull request by jasmingacic**
This pull request is addressing #993

### CODE REVIEW

**Comment by jasmingacic** [comment]
retest this please

**Comment by squat** [comment]
ok to test

**Comment by jasmingacic** [comment]
@squat is there anything I should do?

**Comment by jasmingacic** [comment]
ok to test

**Comment by squat** [comment]
ok to test

**Comment by jasmingacic** [comment]
ok to test

**Comment by jasmingacic** [comment]
Is there anything we can do for this to get merged?

**Pull request merged**
