### PR TITLE
Added AWS ES support

### PR DESCRIPTION
**Pull request by amitkumarj441**
Added logging infrastructure for AWS Elasticsearch. #1478

### CODE REVIEW

**Comment by amitkumarj441** [comment]
@chancez Can you please review this patch so that we can move forward with #1478 ?

**Comment by chancez** [comment]
I've built a patched version of the container that works for AWS ES, but I'm not currently happy with it, as it's got some issues. I'm currently looking into what other options there are, short of forking the fluent-plugin-aws-elasticsearch-service plugin. 

I'd like to figure out what we're going to do about that before we try to officially support a logging setup that uses AWS Elasticsearch. I'll try and get back to you soon on what we figure out for supporting AWS ES, then I'll review this.

**Comment by amitkumarj441** [comment]
Thanks @chancez for letting me know about the current work on AWS ES.
I have written a fluentd config for AWS ES and asked in #1478 to open a new PR for this but I didn't find any relevant folder to push.

**Comment by sym3tri** [comment]
Thanks for the contribution, but our website docs moved to https://github.com/coreos/tectonic-docs

Can you please submit your pull-request there?

**Comment by amitkumarj441** [comment]
Thanks @sym3tri for the reminder.
Just done with [PR](https://github.com/coreos/tectonic-docs/pull/26).

**Pull request closed without merging**
