### PR TITLE
config.tf: kvo to v1.7.5-kvo.7

### PR DESCRIPTION
**Pull request by diegs**
Also regenerate update payload.

### CODE REVIEW

**Comment by diegs** [comment]
test upgrade from 1.7.3-tectonic.3 1.7.3-tectonic.3

**Comment by yifan-gu** [comment]
Upgrade test will fail because I changed to test the prometheus test, changing back

**Comment by yifan-gu** [comment]
test upgrade from 1.7.3-tectonic.3 1.7.3-tectonic.3

**Comment by yifan-gu** [comment]
Hmm, actually the problem is the upgrade test is using old tectonic builder image

**Comment by yifan-gu** [comment]
test upgrade from 1.7.3-tectonic.3 1.7.3-tectonic.3

**Comment by yifan-gu** [comment]
test upgrade from 1.7.3-tectonic.3 1.7.3-tectonic.3

**Comment by diegs** [comment]
retest this please

**Comment by diegs** [comment]
Azure test passed but teardown failed.

**Comment by sudhaponnaganti** [comment]
These tests are passing before. So shouldn't be failing now. Can the failed tests be fixed now otherwise they keep failing for next releases. There is no good time to fix them. Thank you

**Comment by sym3tri** [comment]
@cpanato @alexsomesan Seems this is a release blocker. Can you look into the test failure?

**Comment by alexsomesan** [comment]
destroy failed on one test - looks like a flake
i think we're good to merge

**Comment by sudhaponnaganti** [comment]
Ok - smoke tests have flakes. Upgrades tests do not have. So we are good to go if upgrades are successful 
@diegs  - can you merge this. We will be good to release RC today unless another CVE is pening

**Comment by diegs** [comment]
All this test talk appears to have kicked the tests off again... will wait for the run to complete, and then merge.

**Comment by diegs** [comment]
Azure destroy passed but destroy failed again. Merging.

**Pull request merged**
