### PR TITLE
resources: add container-linux-updater

### PR DESCRIPTION
**Pull request by euank**
Mask locksmithd as well.

Marked do-not-merge for now because it uses my personal test build of CLUO, pending a merge+release there.

### CODE REVIEW

**Comment by euank** [comment]
I've updated the tag to the actual release tag

I've also masked locksmithd in a bunch more places.

The intent is that it's only run on the etcd nodes now (since they're not part of k8s, there's not much I can do about them).

**Comment by euank** [comment]
cc @dghubble @ethernetdan as possible reviewers I guess?

**Comment by dghubble** [comment]
I think you missed these https://github.com/coreos/tectonic-installer/tree/master/platforms/metal/cl if it was a goal to do this for bare-metal.

**Comment by euank** [comment]
@dghubble added it there too and rebased

**Comment by s-urbaniak** [comment]
General question: Is this feature supposed to be gated by `tectonic_experimental` or is the update operator to be on by default?

**Comment by euank** [comment]
@s-urbaniak That is intentional. The reasoning basically goes "we need either locksmithd or cluo to be in any way safe, and migrating between them is a little tricky (they're mutually exclusive) so making it optional means more work for us later".

If there's good reason to make it experimental, we can, but that means that we'll have to do extra work to be able to migrate it to stable in the future.

I personally am fine with either and willing to do the "more work" if it's necessary, so I'm leaving the call up to @sym3tri

**Comment by dghubble** [comment]
Are you sure this works? Looking at that image, it seems to be private and doesn't include licensed Tectonic users so I'd expect pulls to fail across all platforms.

**Comment by euank** [comment]
@dghubble the repo's public?

`docker pull quay.io/coreos/container-linux-update-operator:v0.2.0` works fine for me on a non-logged-in-machine.

**Comment by dghubble** [comment]
Thanks, testing for bare-metal.

**Pull request merged**
