### PR TITLE
Adds cookie based affinity to tectonic ingress (sticky sessions) ...

### PR DESCRIPTION
**Pull request by kans**
which is necessary for planned security updates to Bridge.

@diegs in case we need a migration...

### CODE REVIEW

**Comment by diegs** [comment]
No migration needed! We just need to make sure we include these in the next KVO upgradespec.

**Comment by enxebre** [comment]
ok to test

**Comment by kans** [comment]
@diegs This PR has been updated.

**Comment by diegs** [comment]
cc @thorfour 

@kans can you please submit another PR to tectonic-operators, since the original version was merged? Thanks!

**Comment by kans** [comment]
@diegs still no migration needed with the split ingresses?

**Comment by diegs** [comment]
@kans yeah we'll need to do something to add the new one.

**Comment by diegs** [comment]
cc @thorfour KVO doesn't install new manifests by default. You will need to add a migration that creates the new one.

**Comment by ggreer** [comment]
Just FYI, this is a release blocker. I'd update the labels, but I don't have permission.

**Comment by enxebre** [comment]
retest this please

**Comment by squat** [comment]
ok to test

**Pull request merged**
