### PR TITLE
Update KVO to v1.6.4-kvo.3

### PR DESCRIPTION
**Pull request by diegs**
Also generate a new update-payload.

### CODE REVIEW

**Comment by diegs** [comment]
test upgrade from v1.6.2-tectonic.1

**Comment by kans** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
Upgrade test failed with the following, looking...

```
    --- FAIL: TestUpgrade/after_upgrade (0.01s)
    	upgrade_test.go:170: expected current version 1.2.0 got 1.1.0 for AppVersion tectonic-monitoring
```

**Comment by diegs** [comment]
Ahh, hm. The versions in `config.tf` are still 1.6.2. I think we need to update those too.

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by derekparker** [comment]
lgtm on my end.

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
Upgrade test timed out because it hung for 15 minutes in the cache pre-warming phase. I'm going to kick it one more time, and otherwise we may need to disable cache pre-warming.

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
Updated to v1.6.4-kvo.3 which includes console v1.6.3.

This is ready to merge. The upgrade test issue was root caused to a bug in the `kubelet-wrapper` that ships with coreos linux:

https://github.com/coreos/bugs/issues/1831
https://github.com/coreos/coreos-overlay/pull/2508

Changing our upgrade tests to use the `beta` coreos channel has eliminated the issue.

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
Running one more upgrade test with the latest kvo just for kicks. But we've had 3 successful runs now.

**Comment by s-urbaniak** [comment]
@diegs I still see upgrade failures like this:

```
=== RUN   TestUpgrade/upgrade
F0527 00:41:13.567441    2812 client.go:37] Cannot load config for REST client: Error loading config file "/kubeconfig": read /kubeconfig: is a directory
goroutine 35 [running]:
github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog.stacks(0x2a84000, 0xc400000000, 0x9a, 0xed)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog/glog.go:769 +0xa5
github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog.(*loggingT).output(0x2a63ac0, 0xc400000003, 0xc42021e600, 0x29e8815, 0x9, 0x25, 0x0)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog/glog.go:720 +0x357
github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog.(*loggingT).printf(0x2a63ac0, 0xc400000003, 0x1d48def, 0x26, 0xc4204fbd68, 0x1, 0x1)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog/glog.go:655 +0x14c
github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog.Fatalf(0x1d48def, 0x26, 0xc4204fbd68, 0x1, 0x1)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/golang/glog/glog.go:1148 +0x67
github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/coreos-inc/operator-client/pkg/client.NewClient(0xc420010090, 0xb, 0xc420010090, 0xb)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/vendor/github.com/coreos-inc/operator-client/pkg/client/client.go:37 +0x26f
github.com/coreos-inc/tectonic-upgrade-test/tests.newKubeClient(0xc42021e540, 0xc4203a6c00, 0xc4201a8a00)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/tests/upgrade_test.go:57 +0x69
github.com/coreos-inc/tectonic-upgrade-test/tests.upgradeTest(0xc42021e540)
	/go/src/github.com/coreos-inc/tectonic-upgrade-test/tests/upgrade_test.go:105 +0x34d
testing.tRunner(0xc42021e540, 0x1ddecc8)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
exit status 255
FAIL	github.com/coreos-inc/tectonic-upgrade-test/tests	0.093s
Finishing the test
```

As I am unaware of the code path taken here, I cannot evaluate the severity, so leaving the PR open.

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Comment by diegs** [comment]
@s-urbaniak I've never seen that particular error before, investigating now.

**Comment by diegs** [comment]
test upgrade from 1.6.2-tectonic.1

**Pull request merged**
