### PR TITLE
Jenkinsfile: fail test if terraform destroy failed

### PR DESCRIPTION
**Pull request by ggreer**
Terraform destroy was failing in jenkins for days and we didn't notice.

### CODE REVIEW

**Comment by Quentin-M** [comment]
Can you add a loup around this? Try a few times before failing. Will help when a gateway cannot detached etc. Less chance of leaking and doing false positive. It's pretty much accepted that users would have to retry sometimes on destroy due time AWS eventual consistency vs Terraform internal state.

**Comment by ggreer** [comment]
I guess, but it'll fail 100% of the time right now because `terraform destroy` never works when `tectonic_etcd_count` is > 0.

**Comment by Quentin-M** [comment]
For sure, this one issue here is going to fail the _n_ allowed times :)

**Comment by ggreer** [comment]
It looks like the first `terraform destroy` failure was https://jenkins-tectonic-installer.prod.coreos.systems/job/coreos%20-%20tectonic-installer/job/tectonic-installer/job/PR-708/1/console which is for #708. The error-squelching (the other part of this bug) was introduced in #551.

**Pull request merged**
