### PR TITLE
ci/tests: fix build status in the readme.md

### PR DESCRIPTION
**Pull request by cpanato**
cc @mxinden @squat

### CODE REVIEW

**Comment by squat** [comment]
@cpanato did you change permission on jenkins?

**Comment by cpanato** [comment]
@squat  no, I tested in an incognito window and with my 3gb network and the badge appears without issues

**Comment by cpanato** [comment]
@squat removed the link to Jenkins, can you please check again?

thanks

**Comment by cpanato** [comment]
@squat when you have some time can you please do another check?

**Pull request merged**
