### PR TITLE
Bump Tectonic Console to v2.0.3

### PR DESCRIPTION
**Pull request by ggreer**
Includes:

- Fix styling for cluo update.
- More accurate queries for some gauge graphs on the front page.

This should get merged into the release branch.

### CODE REVIEW

**Comment by Quentin-M** [comment]
Unless this is a critical bug fix or a deal-breaker for product requirements, I would argue that this does not have to be in the release branch (and require yet another KVO bump).

/cc @sudhaponnaganti @robszumski

**Comment by ggreer** [comment]
This doesn't need a new release of the installer, KVO, etc, but I think it should get in the release eventually. It's just some minor bug fixes.

**Comment by alexsomesan** [comment]
running the smokes

**Comment by sudhaponnaganti** [comment]
@ggreer - I will make RC5 tomorrow. So can you cherry-pick this in to 1.7.5 if applicable. I understood from notes above that this doens't have any other dependencies and can be merged cleanly in to 1.7.5. As we are close to 1.7.5, wanted to reduce impact.

**Pull request merged**
