### PR TITLE
Add public IP DNS entry to designate and route53

### LINKED ISSUE #1868: openstack: flannel pod crash looping on worker nodes
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): a0884ce9
* Terraform version (`terraform version`): Terraform v0.10.4
* Platform (aws|azure|openstack|metal): openstack

## What happened?
Flannel pods crash loop on worker nodes:
```
kube-system   po/kube-flannel-3fg7q                             1/2       CrashLoopBackOff   6          10m
kube-system   po/kube-flannel-3xc00                             2/2       Running            1          10m
kube-system   po/kube-flannel-6q4zc                             1/2       CrashLoopBackOff   6          10m
kube-system   po/kube-flannel-9bws2                             1/2       CrashLoopBackOff   6          10m
kube-system   po/kube-flannel-d0p94                             2/2       Running            0          10m
kube-system   po/kube-flannel-dstsr                             2/2       Running            1          10m
```

This appears to be related to 32680518, which changed the worker DNS entries to the public floating IP address. As far as I can tell, this results in the node InternalIP address being set to the wrong address. Compare:

```
Name:			levi-neutron-master-0
Role:			
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/os=linux
			kubernetes.io/hostname=levi-neutron-master-0
			node-role.kubernetes.io/master=
Annotations:		flannel.alpha.coreos.com/backend-data={"VtepMAC":"9a:c4:b1:8e:b8:70"}
			flannel.alpha.coreos.com/backend-type=vxlan
			flannel.alpha.coreos.com/kube-subnet-manager=true
			flannel.alpha.coreos.com/public-ip=192.168.1.9
			node.alpha.kubernetes.io/ttl=0
			volumes.kubernetes.io/controller-managed-attach-detach=true

...

Addresses:
  InternalIP:	192.168.1.9
  Hostname:	levi-neutron-master-0
```
```
Name:			levi-neutron-worker-0
Role:			
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/os=linux
			kubernetes.io/hostname=levi-neutron-worker-0
			node-role.kubernetes.io/node=
Annotations:		node.alpha.kubernetes.io/ttl=0
			volumes.kubernetes.io/controller-managed-attach-detach=true

...

Addresses:
  InternalIP:	148.62.13.208
  Hostname:	levi-neutron-worker-0
```

## What you expected to happen?
All flannel pods should be Running. The `InternalIP` field on the workers should probably be on the private subnet.

## How to reproduce it (as minimally and precisely as possible)?
Launch a cluster with the OpenStack provider.

## Anything else we need to know?
Regression introduced by 32680518.

For some reason, everything works properly if the cloud provider is set. In that case, the `Addresses` field on the k8s nodes have both `InternalIP` and `ExternalIP` set correctly.

```
Name:			levi-foo-master-0
Role:			
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/os=linux
			failure-domain.beta.kubernetes.io/region=RegionOne
			failure-domain.beta.kubernetes.io/zone=nova
			kubernetes.io/hostname=levi-foo-master-0
			node-role.kubernetes.io/master=
Annotations:		flannel.alpha.coreos.com/backend-data={"VtepMAC":"56:19:00:17:72:fc"}
			flannel.alpha.coreos.com/backend-type=vxlan
			flannel.alpha.coreos.com/kube-subnet-manager=true
			flannel.alpha.coreos.com/public-ip=10.0.0.16
			node.alpha.kubernetes.io/ttl=0
			volumes.kubernetes.io/controller-managed-attach-detach=true

...

Addresses:
  InternalIP:	10.0.0.16
  ExternalIP:	172.99.77.19
  Hostname:	levi-foo-master-0
```
```
Name:			levi-foo-worker-0
Role:			
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/os=linux
			failure-domain.beta.kubernetes.io/region=RegionOne
			failure-domain.beta.kubernetes.io/zone=nova
			kubernetes.io/hostname=levi-foo-worker-0
			node-role.kubernetes.io/node=
Annotations:		flannel.alpha.coreos.com/backend-data={"VtepMAC":"92:65:74:f8:61:ef"}
			flannel.alpha.coreos.com/backend-type=vxlan
			flannel.alpha.coreos.com/kube-subnet-manager=true
			flannel.alpha.coreos.com/public-ip=10.0.0.10
			node.alpha.kubernetes.io/ttl=0
			volumes.kubernetes.io/controller-managed-attach-detach=true

...

Addresses:
  InternalIP:	10.0.0.10
  ExternalIP:	172.99.77.26
  Hostname:	levi-foo-worker-0
```

/cc @s-urbaniak

### PR DESCRIPTION
**Pull request by lblackstone**
Fixes #1868 

I'm still not sure about the root cause of the linked bug, but this change sidesteps the problem by creating a separate DNS entry for the public IP. (Each node created by the OpenStack plan currently had a private IP on a private subnet, and a public floating IP).

/cc @s-urbaniak

### CODE REVIEW

**Comment by cpanato** [comment]
ok to test

**Comment by cpanato** [comment]
@lblackstone thanks for the pr.
Have a small misformatted file, would you be able to fix it? thanks!
```
misformatted files (run 'terraform fmt .' to fix): platforms/openstack/neutron/main.tf
```

**Comment by lblackstone** [comment]
@cpanato Sorry about that! Fixed.

**Comment by cpanato** [comment]
@lblackstone don't need to say sorry! thanks so much, I will check tomorrow the issues in CI
Thanks again for your PR

**Comment by cpanato** [comment]
Saw this errors on CI

```
Error applying plan:

2 error(s) occurred:

* module.vpc.aws_nat_gateway.nat_gw[5]: index 5 out of range for list aws_subnet.master_subnet.*.id (max 5) in:

${aws_subnet.master_subnet.*.id[count.index]}
* module.vpc.aws_route_table_association.route_net[5]: index 5 out of range for list aws_subnet.master_subnet.*.id (max 5) in:

${aws_subnet.master_subnet.*.id[count.index]}
```

and

```
2 error(s) occurred:

* module.vpc.aws_security_group_rule.worker_ingress_https: 1 error(s) occurred:

* aws_security_group_rule.worker_ingress_https: No security group with ID "sg-1331c560"
* module.vpc.aws_security_group_rule.worker_ingress_flannel: 1 error(s) occurred:

* aws_security_group_rule.worker_ingress_flannel: Error finding matching ingress Security Group Rule (sgrule-781446878) for Group sg-1331c560
```

cc @s-urbaniak @alexsomesan

**Comment by lblackstone** [comment]
Those errors look unrelated to this change, AFAICT.

**Comment by cpanato** [comment]
I guess so, I was checking your PR. I will re-trigger the build @lblackstone thanks! :)

**Comment by lblackstone** [comment]
Any update, @cpanato ? Looks like CI failed again, but I'm not able to see the logs.

**Comment by squat** [comment]
Two of the AWS smoke clusters failed to come up. These may have been flakes. Let's retest.

**Comment by squat** [comment]
ok to test

**Comment by squat** [comment]
ok to test

**Comment by lblackstone** [comment]
Looks like it failed again. I just rebased on master to see if that helps.

**Comment by cpanato** [comment]
Tests passed, fail in one Azure while trying to destroy. I guess we can move on.

**Pull request merged**
