### PR TITLE
docs: updating master node label.

### PR DESCRIPTION
**Pull request by zbwright**

### CODE REVIEW

**Comment by zbwright** [comment]
for https://github.com/coreos/tectonic-installer/pull/1045

**Comment by joshix** [comment]
does this supersede #1045 or what's the deal?

**Comment by zbwright** [comment]
@joshix looks like both aleks and I submitted a PR for exactly the same changes. I must have looked at his, and thought it was an issue, rather than a PR? this one can be closed.

**Comment by joshix** [comment]
in favor of #1045

**Pull request closed without merging**
