### PR TITLE
test: remove hard coded CL version

### PR DESCRIPTION
**Pull request by cpanato**
cc @s-urbaniak

### CODE REVIEW

**Comment by cpanato** [comment]
ok to test

**Comment by squat** [comment]
Rather than set the defaultValue to ‘’ can we remove that block for the variable entirely?

**Comment by cpanato** [comment]
@squat we can remove, but since we have that, we can reuse in future for other tests.

**Comment by cpanato** [comment]
@squat if want to remove I will remove, let me know

**Comment by squat** [comment]
I prefer to remove it to avoid any confusion

**Comment by cpanato** [comment]
@squat done

**Pull request merged**
