### PR TITLE
metal: Removing extra "[]" from metal templates

### PR DESCRIPTION
**Pull request by edevenport**
#1071 This addresses the unnecessary "[]" in the metal templates.

### CODE REVIEW

**Comment by edevenport** [comment]
@alexsomesan @squat This PR was successfully tested locally, but I'm not sure why the jenkins test is failing.

**Comment by squat** [comment]
@edevenport it looks like the branch is failing terrafrom linting for the following files
* modules/bootkube/tls_kube.tf 
* modules/tectonic/crypto.tf

can you run `terraform fmt` and push again?

**Comment by edevenport** [comment]
@squat - `terraform fmt` has been run and pushed again.

**Comment by squat** [comment]
ok to test

**Pull request merged**
