### PR TITLE
bumped console, kvo and tectonic version

### PR DESCRIPTION
**Pull request by thorfour**
bumped console, kvo and tectonic version

### CODE REVIEW

**Comment by thorfour** [comment]
test upgrade from 1.8.4-tectonic.3 1.8.4-tectonic.3

**Comment by sudhaponnaganti** [comment]
I see the govcloud related failures are due to login @cpanato - do you know who built these tests?

**Comment by enxebre** [comment]
@sudhaponnaganti we were hitting aws govcloud limits, cleaned it and govcloud should be ok now. aws and azure are red too. To retest only on govcloud remove the other labels and comment with "retest this please" or close/reopen the PR

**Comment by sudhaponnaganti** [comment]
@enxebre @cpanato - Not sure why other tests are failing. Ideally they should be passing too.

**Comment by cpanato** [comment]
retest this please

**Comment by cpanato** [comment]
this did not pass because the conformance tests label was set. and most of the time the conformance tests fail because the delete pods/namespaces issue.

re-running again for all platforms only smoke tests

**Comment by cpanato** [comment]
retest this please. only Azure.

**Comment by sudhaponnaganti** [comment]
thanks carlos

**Pull request merged**
