### PR TITLE
Open-source the Tectonic installer

### PR DESCRIPTION
**Pull request by Quentin-M**
This PR open-sources the existing Tectonic installer. This includes the integrality of the backend code for the provisioning of [AWS](https://coreos.com/tectonic/docs/latest/install/aws/index.html) and [bare-metal](https://coreos.com/tectonic/docs/latest/install/bare-metal/index.html) clusters, as well as the GUI for doing so.

Pull Request authorized by @philips in person.

# Summary

The installer introduced in this pull request is the one that has been developed internally at CoreOS and used for the (almost) two past years by several key players of the industry to deploy Kubernetes/Tectonic clusters on AWS ([based on AWS CloudFormation](https://aws.amazon.com/cloudformation/)) and bare-metal (using [matchbox](https://github.com/coreos/matchbox)). Today, the installer is shifting towards using [TerraForm](https://www.terraform.io/) exclusively and expanding to various other cloud providers. Recently, the GUI has been granted the ability to deploy clusters on AWS using TerraForm (alpha). In the near future, the GUI will also let users deploy TerraForm-based clusters on bare-metal, OpenStack, Azure, etc, while deprecating and slowly removing the legacy provisioning methods. By moving the existing installer's codebase into this repository, we are easing the integration between TerraForm and the GUI installer and making the overall story more consistent.

# Commits

Here is a description of the main commits you'd want to look at:

- The first three commits actually introduces the existing Tectonic installer's codebase into this repository (copy files, merge Jenkinsfile, rename repository).
- The fourth commit begins the integration rework by reading the TerraForm templates directly from this repository rather than from the ones we used to vendor inside the installer's binary.
- The fifth commit improves the method used to vendor TerraForm plugins in the installer so any public or internal providers can be used. The next three follows up with vendoring and necessary renames.
- The ninth and tenth commits updates the documentation and usage process for developers.

Note: This is up to 4ad8552edb6f464b535820a8422fb8e094f20cb6 of the old repository.

# How to test?

### Manually

The documentation has been updated accordingly to this change in order to let developers use the project. Note that proper documentation, that will use the release rather than `master` will need to be written for real world users / customers.

Here is the TD;LR:
- Switch back to using upstream/vanilla TerraForm v0.8.8
- Build the installer: `(cd installer && make build)`
- Initialize a TerraForm configuration file and tell TerraForm to use it:
```
INSTALLER_PATH=$(pwd)/installer/bin/linux/installer # Edit the platform name.
sed "s|<PATH_TO_INSTALLER>|$INSTALLER_PATH|g" terraformrc.example > terraformrc
export TERRAFORM_CONFIG=$(pwd)/terraformrc
```
- Run TerraForm _get_ as usual: `terraform get platforms/aws`
- Run TerraForm _apply_ as usual: `terraform apply -var-file=build/${CLUSTER}/terraform.tfvars platforms/${PLATFORM}`

### With the GUI Installer

- Switch back to using upstream/vanilla TerraForm v0.8.8
- Build the installer: `(cd installer && make build)`
- Run the installer in dev mode: `./installer/bin/linux/installer -dev` # Edit the platform name.
- Follow the steps

# What's next?

- The release process has to be restored and updated accordingly to this PR. 
- All the tests that used to run on the former repository (sanity, smoke, format, external updating tests, ...) must be updated.

See this [doc](https://docs.google.com/document/d/1wAxrwgJgMgOWOUDMXBkqn-eRyPQA9TjpSB6mcUm_QvM) for more details.

### CODE REVIEW

**Comment by philips** [comment]
Woo! Excited for this to land. Thanks for getting the PR together.

**Comment by Quentin-M** [comment]
Vendoring of the providers and RPC routing coming right up, got slowed down by nested glide issue and operator code. Almost almost done there. I expect to have something that works and can be tested by noon tomorrow.

Then it'll be packaging work for the release and work towards restoring the tests.

**Comment by Quentin-M** [comment]
@s-urbaniak @alexsomesan This is out of WIP state. Could you guys take a look? As soon as this is merged, we can drop the code in the old repository and stop the struggle of pulling the changes from there non-stop - and I can start working on prepping for the release.

From my test, it seems like the GUI is broken in the sense of it will not print the logs properly but I saw a whole bunch of commits in the past days to the Installer that we'll have to cherry-pick here.

**Comment by chancez** [comment]
What exactly is the plan around `modules/tectonic/resources/manifests` and `installer/assets`?

**Comment by Quentin-M** [comment]
@chancez As stated by the document linked at the very end of the PR description, the legacy provisioning methods will be removed as soon as both platforms get full feature parity and to a stable state. The `installer/` will then essentially become a tool to assist the GUI by providing data from the various cloud providers (i.e. which SSH key can be used), validate the data, call TerraForm on the behalf of the user, and perform status checks that it will feed back to the GUI.

**Comment by Quentin-M** [comment]
I just fixed some more. It now actually deploys clusters both via the GUI or manually. Tests pass too. So it should be good to go!

**Comment by pst** [comment]
> Wonder what happens when I push this button...
:tada:

**Pull request merged**
