### PR TITLE
1.8.2: kvo to v1.8.2-kvo.2

### PR DESCRIPTION
**Pull request by diegs**
Also update KVO manifest to use YAML upgrade spec.

### CODE REVIEW

**Comment by diegs** [comment]
test upgrade from 1.7.9-tectonic.2 1.7.9-tectonic.2

**Comment by yifan-gu** [comment]
test upgrade from 1.7.9-tectonic.2 1.7.9-tectonic.2

**Comment by yifan-gu** [comment]
Inspecting the cluster, found that the kvo didn't come up correctly:
```
kubectl logs kube-version-operator-3912901974-0j303 -n tectonic-system
I1129 00:03:39.027570       1 main.go:50] update operator running
F1129 00:03:39.027692       1 kube_version_operator.go:58] error parsing external mapping: open /upgrade-spec.json: no such file or directory
```

**Comment by diegs** [comment]
test upgrade from 1.7.9-tectonic.2 1.7.9-tectonic.2

**Comment by diegs** [comment]
test upgrade from 1.7.9-tectonic.2 1.7.9-tectonic.2

**Comment by diegs** [comment]
@yifan-gu good catch, done

**Comment by diegs** [comment]
test upgrade from 1.7.9-tectonic.2 1.7.9-tectonic.2

**Comment by diegs** [comment]
test upgrade from 1.7.9-tectonic.2 1.7.9-tectonic.2

**Comment by diegs** [comment]
retest this please

**Comment by sudhaponnaganti** [comment]
thanks

**Pull request merged**
