### PR TITLE
platforms/metal: unify kubelet, install as enabled

### PR DESCRIPTION
**Pull request by lucab**
This updates kubelet setup on bare-metal to unify with all other
platforms. It gets rid of path activation and enables kubelet.service
directly from ignition.

### CODE REVIEW

**Comment by lucab** [comment]
NB: not saying that a crash-looping kubelet.service is better than a path-activated one (global approach can be revisited later by the team if they wish). This just unifies all platforms so that it's easier to reason about the bootstrapping flow.

**Comment by lucab** [comment]
Gentle ping for a review.

**Comment by s-urbaniak** [comment]
ok to test

**Comment by s-urbaniak** [comment]
ok to test

**Comment by s-urbaniak** [comment]
CI failure is unrelated (Azure), hence merging.

**Pull request merged**
