### PR TITLE
config.tf: Bumps console to v1.9.3

### PR DESCRIPTION
**Pull request by amrutac**

### CODE REVIEW

**Comment by amrutac** [comment]
cc: @sudhaponnaganti

**Comment by squat** [comment]
Closing and reopening to trigger tests

**Comment by Quentin-M** [comment]
This already was merged in the release branch and thus must merge in master too.

**Comment by amrutac** [comment]
The tests passed on the other PR, so I merged and I am expecting the same for this one too. These tests were triggered at around the same time, wasn't expecting them to take this long. I'll merge as soon as the tests are done.

**Comment by amrutac** [comment]
I spoke too soon..

**Comment by Quentin-M** [comment]
Good enough, merging. Thanks!

**Pull request merged**
