### PR TITLE
module/bootkube: update k8s addons

### PR DESCRIPTION
**Pull request by squat**
Update kube-dns and kube-proxy to match upstream better match upstream.

cc @yifan-gu @aaronlevy 

Fixes: INST-1024

Related: #3178

### CODE REVIEW

**Comment by squat** [comment]
was blocked by: https://github.com/coreos/tectonic-installer/pull/3150

**Comment by squat** [comment]
ok to test

**Comment by squat** [comment]
@cpanato same here regarding the AMI

**Comment by cpanato** [comment]
@squat all green

**Pull request merged**
